elastic/observability-docs

docs/en/observability/observability-introduction.asciidoc, docs/en/observability/observability-ui.asciidoc
We need to mark these topics as "coming" because they are shown under the current tag.
Note that the tag renders as:
=> Add coming tags for incomplete topics

docs/en/ingest-management/troubleshooting.asciidoc, docs/en/logs/logs-installation.asciidoc, docs/en/metrics/metrics-installation.asciidoc
Updates links to reflect changes added in elastic/beats#19302.
This change applies to 7.9 and later.
@EamonnTP Hope these changes don't conflict with the ones you're making.  My fix isn't meant to replace yours; just made minimal changes so the linking makes more sense.
=> Change links to refactored Beats getting started docs

.ci/Jenkinsfile
This PR updates the documentation preview comment:
* Turns the preview into a link so that it's easily clickable
* Maps the preview link to `master` instead of `current`
* Adds a link to the HTML diff which is useful for debugging purposes.
**Current:**
**Proposed:**
=> docs: update preview comment

docs/en/ingest-management/getting-started.asciidoc
- Remove standalone suffix from the documentation. (#29)
=> [7.x] Remove standalone suffix from the documentation. (#29)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
=> Fix errors in ingest management examples

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
Backports the following commits to 7.8:
- Fix errors in examples (#37)
=> [7.8] Fix errors in examples (#37)

docs/en/uptime/install.asciidoc
Starting in 7.9, the Beats getting started guides are refactored and reduced to a single page. 
Follow-up to elastic/beats#19302.
=> Update link to Heartbeat quick start

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Clean up heading tags in ingest management docs (#46)
=> [7.x] Clean up heading tags in ingest management docs (#46)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Clean up heading tags in ingest management docs (#46)
=> [7.9] Clean up heading tags in ingest management docs (#46)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
Backports the following commits to 7.8:
- Clean up heading tags in ingest management docs (#46)
=> [7.8] Clean up heading tags in ingest management docs (#46)

docs/en/ingest-management/troubleshooting.asciidoc
Moves content about stopping Elastic Agent to a more prominent location that's easier to discover through a search.
Requires https://github.com/elastic/beats/pull/19971.
(Build won't pass until after 19971 is merged.)
=> Move content about how to stop Elastic Agent

docs/en/ingest-management/troubleshooting.asciidoc
Backports the following commits to 7.8:
- Move content about how to stop Elastic Agent (#49)
=> [7.8] Move content about how to stop Elastic Agent (#49)

tutorial-template.asciidoc
This PR adds a template for guidance when creating tutorial-type guides within the Observability documentation. 
For the time being, I have placed the file outside of the docs directory. 
https://github.com/elastic/observability-dev/issues/664
=> Template for tutorial-type guides

docs/en/ingest-management/getting-started.asciidoc
Updates ingest management docs to indicate that the agent must be run under the SYSTEM user to use the Endpoint integration.
Users will run into a "Agent process is not root/admin or validation failed" error on Win if they don't run under SYSTEM.
- Closes elastic/beats#19955
- Related to https://github.com/elastic/beats/pull/20172
(I'm also writing a troubleshooting topic with more detail. I'll add the link here when it's ready.)
Note that the current docs do not show platform-specific commands. I will fix that...just waiting for the final design of our tabbed panel widget to avoid having to redo the work.
=> [docs] Add info about SYSTEM user requirement to the ingest Getting Started

docs/en/ingest-management/getting-started.asciidoc
- [docs] Add info about SYSTEM user requirement to the ingest Getting Started (#65)
=> [7.x] [docs] Add info about SYSTEM user requirement to the ingest Getting Started (#65)

docs/en/ingest-management/getting-started.asciidoc
- [docs] Add info about SYSTEM user requirement to the ingest Getting Started (#65)
=> [7.9] [docs] Add info about SYSTEM user requirement to the ingest Getting Started (#65)

docs/en/metrics/metrics-installation.asciidoc, docs/en/metrics/metrics-overview.asciidoc
This PR updates the [Installing metrics](https://www.elastic.co/guide/en/metrics/guide/current/install-beats-for-metrics.html) content to provide a better user experience to what is currently offered.
The content now includes step procedures:
1. Download and install Metricbeat.
1. Configure Metricbeat.
1. Start Metricbeat.
1. Verify your data in Kibana.
https://observability-docs_58.docs-preview.app.elstc.co/guide/en/metrics/guide/master/install-metrics-monitoring.html
Closes https://github.com/elastic/observability-docs/issues/11
=> Metrics monitoring guide: update getting started content

docs/en/metrics/metrics-installation.asciidoc
- Metrics monitoring guide: update getting started content (#58)
=> [7.x] Metrics monitoring guide: update getting started content (#58)

docs/en/metrics/metrics-installation.asciidoc
- Metrics monitoring guide: update getting started content (#58)
=> [7.9] Metrics monitoring guide: update getting started content (#58)

tutorial-template.asciidoc
Changes:
- Fixed the tutorial template to use `discrete` instead of `float` tags (preferred for asciidoctor--see https://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/#blocks).
- Commented out introductory text (allows you to build template without errors).
- Made a couple of minor tweaks to phrasing.
Also, the "What you need" and "Learn more" sections are a little different from what other tutorials in our library use. We're really all over the floor in terms of consistency, but I think it might be worth presenting this format to the larger doc group to get some feedback before we start writing tutorials.
In other docs, I see mostly "Before you begin" or "Prerequisites", and "Next steps" or "What's next?" but I haven't done a thorough inventory.
@EamonnTP @bmorelli25 WDYT?
=> [docs] Use discrete tags instead of float

docs/en/observability/page_header.html
The observability guide won't be ready until 7.9 and therefore `master` is marked as the current branch. This is a really confusing experience for users because all the content is marked as "coming". It might help to have a simple statement (without links) at the top of each page until the guide is ready.
Note: Creating this initially as a draft to make sure the doc build still supports overriding the default banner.
=> Override banner until docs are ready

docs/en/observability/page_header.html
- Override banner until docs are ready (#79)
=> [7.9] Override banner until docs are ready (#79)

docs/en/observability/page_header.html
- Override banner until docs are ready (#79)
=> [7.x] Override banner until docs are ready (#79)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/ingest-management-limitations.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- [docs] Promote ingest management to beta (#70)
=> [7.x] [docs] Promote ingest management to beta (#70)

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/ingest-management-limitations.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- [docs] Promote ingest management to beta (#70)
=> [7.9] [docs] Promote ingest management to beta (#70)

docs/en/ingest-management/troubleshooting.asciidoc
Adds a troubleshooting topic for users who try to run endpoint under a user other than system.
This is a follow-up to https://github.com/elastic/beats/pull/20172
=> [docs] Add troubleshooting topic about running under SYSTEM for Endpoint

docs/en/ingest-management/ingest-management-limitations.asciidoc
- document limits on Cloud for 7.9  (#98)
=> [7.x] document limits on Cloud for 7.9 (#98)

docs/en/ingest-management/ingest-management-limitations.asciidoc
- document limits on Cloud for 7.9  (#98)
=> [7.9] document limits on Cloud for 7.9 (#98)

docs/en/ingest-management/troubleshooting.asciidoc
Updates the troubleshooting description about Endpoint to address feedback in https://github.com/elastic/observability-docs/issues/90.
(Changes made after discussion with writers on the Elastic Security team.)
Replaces https://github.com/elastic/observability-docs/pull/71
=> Update description of Endpoint integration in troubleshooting

docs/en/ingest-management/getting-started.asciidoc
- [Docs]Ingest Manager quick start guide type (#106)
=> [7.x] [Docs]Ingest Manager quick start guide type (#106)

docs/en/ingest-management/getting-started.asciidoc
- [Docs]Ingest Manager quick start guide type (#106)
=> [7.9] [Docs]Ingest Manager quick start guide type (#106)

docs/en/ingest-management/troubleshooting.asciidoc
- [docs] Add steps for making agent persistent on macos (#105)
=> [7.9] [docs] Add steps for making agent persistent on macos (#105)

docs/en/observability/page_header.html
- Remove prerelease banner (#113)
=> [7.x] Remove prerelease banner (#113)

docs/en/observability/page_header.html
- Remove prerelease banner (#113)
=> [7.9] Remove prerelease banner (#113)

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
The troubleshooting topic was getting quite long. I think it's worth having an FAQ right now. Eventually all the topics in the FAQ should be covered in the main docs or no longer necessary when the software is GA. At that time, we might want to remove the FAQ.
=> Make troubleshooting and FAQ separate topics

docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/ingest-management-limitations.asciidoc, docs/en/ingest-management/ingest-management-overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
I don't usually advocate putting things in bold font, but in this case, it might help. We have warnings in the docs, but users aren't seeing them, so I propose that we add this text to every page in the ingest management docs.
TODOs:
=> Strengthen language about ingest management upgrade restriction in 7.8

docs/en/observability/install-observability.asciidoc
- docs: link to apm server ref (#138)
=> [7.9] docs: link to apm server ref (#138)

docs/en/observability/install-observability.asciidoc
- docs: link to apm server ref (#138)
=> [7.x] docs: link to apm server ref (#138)

docs/en/ingest-management/faq.asciidoc
Closes #118.
I still plan to add an architecture overview, but hopefully this will help Beats users who are trying to understand how agent is different from standalone Beats.
@EricDavisX Let me know if you want me to backport this to 7.9, too.
=> Add FAQ topics about how agent accesses integrations

docs/en/ingest-management/faq.asciidoc
- Add FAQ topics about how agent accesses integrations (#143)
=> [7.x] Add FAQ topics about how agent accesses integrations (#143)

docs/en/ingest-management/faq.asciidoc
- Add FAQ topics about how agent accesses integrations (#143)
=> [7.9] Add FAQ topics about how agent accesses integrations (#143)

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
Changes the URL of the Elastic Package Registry to include version info for 7.9 only.
@ruflin From what I understand, we only want to document this for 7.9, not other releases. Please let me know if that's not correct.
=> Fix URL for Elastic Package Registry

docs/en/uptime/install.asciidoc, docs/en/uptime/overview.asciidoc
Due to build failures on the [Kibana docs PR](https://github.com/elastic/kibana/pull/79978), this PR updates links to the Logs app content. 
This update gives us the opportunity to link directly to the Logs app content in the Observability guide, rather than to the new content in the Kibana PR. 
Doc build failures are expected until the following PR is merged:
https://github.com/elastic/observability-docs/pull/162
https://github.com/elastic/kibana/pull/79978
=> Update links to Uptime app content

docs/en/observability/ingest-uptime.asciidoc
- add observer.geo.name for maps and machine learning (#171)
=> [7.10] add observer.geo.name for maps and machine learning (#171)

docs/en/observability/ingest-uptime.asciidoc
- add observer.geo.name for maps and machine learning (#171)
=> [7.x] add observer.geo.name for maps and machine learning (#171)

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
Closes issue #130.
Related PR: https://github.com/elastic/beats/pull/21458
=> Update endpoint-related terminology

docs/en/observability/monitor-java-app.asciidoc, docs/en/observability/tail-logs.asciidoc, docs/en/observability/view-infrastructure-metrics.asciidoc, docs/en/observability/view-monitor-status.asciidoc
=> [7.10] Update links (#195)

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/create-alerts.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/monitor-uptime.asciidoc
The section names that we currently use are not really the terms that users search on when looking for our docs.
To align our docs better with industry standard terminology and provide a better structure for including topics like synthetics monitoring, I've renamed the major sections.
=> Rename sections in observability guide

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/create-alerts.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/monitor-uptime.asciidoc
- Rename sections in observability guide (#198)
=> [7.x] Rename sections in observability guide (#198)

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/create-alerts.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/monitor-uptime.asciidoc
- Rename sections in observability guide (#198)
=> [7.10] Rename sections in observability guide (#198)

docs/en/observability/monitor-java-app.asciidoc
This PR fixes a broken link to the Lens section in the Kibana docs.
NOTE: The fix is required only for the master, 7.x, and 7.10 branches.
https://observability-docs_217.docs-preview.app.elstc.co/guide/en/observability/master/monitor-java-app.html
https://github.com/elastic/observability-docs/issues/215
https://github.com/elastic/docs/pull/1994
=> Fix broken link

docs/en/observability/whats-new.asciidoc
Adds a "what's new" tagged region to `master` and `7.x`.
Related: https://github.com/elastic/observability-docs/pull/216/files
=> docs: add whats new tagged region

docs/en/observability/whats-new.asciidoc
- docs: add tagged region (#223)
=> [7.x] docs: add tagged region (#223)

docs/en/observability/whats-new.asciidoc
This PR updates the 7.10 What's new content to use cross-doc links instead of local links. This change is required because the content is reused in the stack-docs installation and upgrade guide.
For https://github.com/elastic/stack-docs/pull/1437
=> [7.10] Update what's new links

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/getting-started.asciidoc
Updates observability docs to support changes in https://github.com/elastic/beats/pull/22290.
The build here will fail until the beats PR is merged.
=> Update installation and standalone agent content

docs/en/observability/whats-new.asciidoc
DoubleValueRecorder and LongValueRecorder are not yet supported.
=> Fix OpenTelemetry Metrics code example

docs/en/observability/whats-new.asciidoc
* Document the indices used to store metrics
* Indicate that `DoubleValueRecorder` and `LongValueRecorder` are not yet supported
=> Better Otel Metrics docs

docs/en/observability/synthetics-quickstart.asciidoc
This PR updates the synthetic quickstart by consolidating steps three and four. The new recommend way to run synthetics is:
```
sh run.sh {version} \
-E cloud.id=<cloud-id> \
-E cloud.auth=elastic:<cloud-pass>
```
_or_
```
sh run.sh {version} \
-E output.elasticsearch.hosts=["localhost:9200"] \
-E output.elasticsearch.username=elastic \
-E output.elasticsearch.password=changeme \
```
=> Update synthetics quickstart

docs/en/observability/synthetics-quickstart.asciidoc
The SSH URL only works if you have valid SSH creds w/ push pull which applies to us Elastic employees but no one else
=> Use un-authenticated git URL for synthetics examples

docs/en/observability/synthetics-quickstart.asciidoc
- Use un-authenticated git URL for synthetics examples (#279)
=> [7.10] Use un-authenticated git URL for synthetics examples (#279)

docs/en/observability/synthetics-quickstart.asciidoc
- Use un-authenticated git URL for synthetics examples (#279)
=> [7.x] Use un-authenticated git URL for synthetics examples (#279)

docs/en/observability/synthetic-monitoring.asciidoc
- docs: make it clear that docker is the only option (#283)
=> [7.10] docs: make it clear that docker is the only option (#283)

docs/en/observability/synthetic-monitoring.asciidoc
- docs: make it clear that docker is the only option (#283)
=> [7.x] docs: make it clear that docker is the only option (#283)

docs/en/observability/monitor-java-app.asciidoc
As part of the 7.10 Kibana docs changes, I've updated this link to match the section title. 
Related to https://github.com/elastic/kibana/pull/84000.
=> [DOCS] Updates link to Kibana Lens

docs/en/observability/infrastructure-threshold-alert.asciidoc, docs/en/observability/logs-threshold-alert.asciidoc, docs/en/observability/metrics-threshold-alert.asciidoc
Currently in the **Create a logs threshold alert** topic we have a [Settings](https://www.elastic.co/guide/en/observability/current/logs-threshold-alert.html#settings) section describing that it's not possible to set an explicit index pattern as part of the configuration. 
This PR adds the Settings content to both the Infrastructure threshold alert and the metrics threshold alert.
Preview:
https://observability-docs_291.docs-preview.app.elstc.co/guide/en/observability/master/metrics-threshold-alert.html
=> Add settings info for metrics alerts

docs/en/observability/synthetics-create-test.asciidoc
This can be confusing for users, since running npx commands outside of the `todos` folder, but within the synthetics repo causes weird issues since that repo defines the synthetics package itself.
In the future we should find a better method than asking users to clone the repo, if they could just get the examples folder that would reduce the number of places errors creep in.
=> Clarify where to run examples

docs/en/observability/synthetics-create-test.asciidoc
- Clarify where to run examples (#289)
=> [7.10] Clarify where to run examples (#289)

docs/en/observability/synthetics-create-test.asciidoc
- Clarify where to run examples (#289)
=> [7.x] Clarify where to run examples (#289)

docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-configuration-example.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent_configuration_example.yml, docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/run-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/stop-elastic-agent.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/index.asciidoc
This PR moves v7.8 of the Elastic Agents docs to the observability-docs repo where other related docs live.
Related PR: https://github.com/elastic/beats/pull/23249
=> Move v7.8 Elastic Agent docs to the observability-docs repo

docs/en/ingest-management/fleet-overview.asciidoc
Add documentation about namespace length limit introduced in https://github.com/elastic/kibana/pull/78522. The length is based on bytes, I borrowed wording from [ES create index API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params).
=> Add info about namespace length limit

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/apm.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/user-experience.asciidoc
- docs: Add quickstart videos (#324)
=> [7.10] docs: Add quickstart videos (#324)

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/apm.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/user-experience.asciidoc
- docs: Add quickstart videos (#324)
=> [7.x] docs: Add quickstart videos (#324)

docs/en/observability/synthetics-quickstart.asciidoc
Fixes the cloning snippet, otherwise:
```
$ git clone https://github.com/elastic/synthetics.git &&\
cd examples/docker
Cloning into 'synthetics'...
remote: Enumerating objects: 1600, done.
remote: Total 1600 (delta 0), reused 0 (delta 0), pack-reused 1600
Receiving objects: 100% (1600/1600), 599.57 KiB | 1.66 MiB/s, done.
Resolving deltas: 100% (985/985), done.
cd: no such file or directory: examples/docker
```
Fixes the zsh shell with quoting, otherwise:
```
$ echo $SHELL
/bin/zsh
$ sh run.sh 7.10.2 \
-E output.elasticsearch.hosts=["localhost:9200"] \
-E output.elasticsearch.username=elastic \
-E output.elasticsearch.password=changeme
zsh: no matches found: output.elasticsearch.hosts=[localhost:9200]
$ sh run.sh "7.10.2" \ 
'-E output.elasticsearch.hosts=["localhost:9200"]' \
'-E …
```
=> Update snippet for cloning and running the synthetics-quickstart

docs/en/observability/synthetics-quickstart.asciidoc
- Update snippet for cloning and running the synthetics-quickstart (#339)
=> [7.x] Update snippet for cloning and running the synthetics-quickstart (#339)

docs/en/observability/synthetics-quickstart.asciidoc
- Update snippet for cloning and running the synthetics-quickstart (#339)
=> [7.11] Update snippet for cloning and running the synthetics-quickstart (#339)

docs/en/observability/synthetics-quickstart.asciidoc
- Update snippet for cloning and running the synthetics-quickstart (#339)
=> [7.10] Update snippet for cloning and running the synthetics-quickstart (#339)

docs/en/observability/synthetics-quickstart.asciidoc
- hardcode-synthetics-docker-image-to-7.10.0 (#346)
=> Hardcode synthetics docker image to {minor}.0 (#346)

docs/en/observability/synthetics-quickstart.asciidoc
- hardcode-synthetics-docker-image-to-7.10.0 (#346)
=> [7.x] hardcode-synthetics-docker-image-to-7.10.0 (#346)

docs/en/observability/synthetics-quickstart.asciidoc
- hardcode-synthetics-docker-image-to-7.10.0 (#346)
=> [7.11] hardcode-synthetics-docker-image-to-7.10.0 (#346)

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/apm.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/user-experience.asciidoc
This PR conditionally displays videos in the observability guide when `is-current-version == true`. When `false`, backup screenshots are displayed instead. I've looked at this a million different ways, and this is by far the easiest way to accomplish this. This PR requires two lines in the `elastic/docs` repo to be changed on each minor release.
* This PR is a follow-up to https://github.com/elastic/observability-docs/pull/324. 
* For #323
This PR requires an additional change in the `elastic/docs` repo before merging: https://github.com/elastic/docs/pull/2044
=> Conditionally display videos in current version

docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
Closes #287 
See the preview here: https://observability-docs_344.docs-preview.app.elstc.co/guide/en/fleet/master/run-elastic-agent-standalone.html
I think it's a little weird to show the API call inside of the steps, but I think it's Ok since we will hopefully replace the example with the role name when it's available.
TODO:
=> Add privileges required to run Elastic Agent standalone

docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
- Add privileges required to run Elastic Agent standalone (#344)
=> [7.x] Add privileges required to run Elastic Agent standalone (#344)

docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
- Add privileges required to run Elastic Agent standalone (#344)
=> [7.10] Add privileges required to run Elastic Agent standalone (#344)

docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
- Add privileges required to run Elastic Agent standalone (#344)
=> [7.11] Add privileges required to run Elastic Agent standalone (#344)

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/apm.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/user-experience.asciidoc
- docs: conditionally display videos in obs-docs (#350)
=> [7.11] docs: conditionally display videos in obs-docs (#350)

docs/en/ingest-management/faq.asciidoc
Closes #282 
This FAQ topic was added in an earlier release. Looks like the config has changed quite a bit so that this topic is no longer relevant. 
The Agents tab clearly lists the policy that is assigned to each enrolled agent, so I don't think we need an FAQ topic for this.
=> Update FAQ info about agent policies

docs/en/observability/whats-new.asciidoc
As per notification from @tbragin, this PR removes content relating to synchronizing time across apps from the 7.11 What's new. When it's ready, it's due for the 7.12 release. 
**HTML preview**: https://observability-docs_370.docs-preview.app.elstc.co/guide/en/observability/7.11/whats-new.html
=> Remove sync time across apps content from What's new

docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
the proposed config for Filebeat with auto discover and labels is not working as the `fileset` settings is only working (and [documented](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html) ) on annotations with auto discover and hints but not with simple auto discover  on labels.
the commit propose a config that is working but a better solution might be available.
=> fix Filebeat config step 5 labels

docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
- docs: fix Filebeat config step 5 (#373)
=> [7.x] docs: fix Filebeat config step 5 (#373)

docs/en/templates/tutorial-template.asciidoc
Adds a brief explanation to tutorial template to help users understand how to get tutorials into the doc build.
Also pruned the opening description because I don't think we need to explain the value of using a template.
=> Explain where to add tutorials

.backportrc.json
The latest release of the backport tool (thanks, Søren!) provides an option to auto-merge backports **after** all PR checks successfully pass. You can specify that a backport shouldn't be auto-merged with the autoMerge flag: `--autoMerge=false`.
This has already been added to the `kibana` and `apm-server` repo. How does @elastic/obs-docs feel about adding this feature to the `observability-docs` repo?
=> Update backports to auto-merge after checks pass

.backportrc.json
Sorry, just found one more improvement I'd like to propose: branch label matching.
When using the backport tool, `7.x` has always automatically been checked. This PR allows PR labels to also automatically check boxes. For example, if a PR has the `v7.12.0` label, `7.12` will be checked in the backport tool. If you're cherry-picking to `master`, just add the `v8.0.0` label and `master` will be checked.
=> Add branchLabelMapping to the backport tool

docs/en/shared/install-apm-agents-kube/php.asciidoc, docs/en/shared/install-apm-agents-kube/widget.asciidoc
This PR adds PHP agent information to the Kubernetes tutorial.
For https://github.com/elastic/observability-docs/issues/383.
=> docs: add PHP agent info to k8s tutorial

docs/en/shared/install-apm-agents-kube/php.asciidoc, docs/en/shared/install-apm-agents-kube/widget.asciidoc
- docs: add PHP agent info to k8s tutorial (#393)
=> [7.x] docs: add PHP agent info to k8s tutorial (#393)

docs/en/shared/install-apm-agents-kube/php.asciidoc, docs/en/shared/install-apm-agents-kube/widget.asciidoc
- docs: add PHP agent info to k8s tutorial (#393)
=> [7.12] docs: add PHP agent info to k8s tutorial (#393)

docs/en/observability/ingest-metrics.asciidoc
Since `Kibana` has been replaced with `Analytics` in the main menu, I removed `Kibana`, and updated to text to match what we use in the Kibana docs.
=> [DOCS] Updates Kibana path for Metricbeat

docs/en/observability/ingest-logs.asciidoc
Since `Kibana` has been replaced with `Analytics` in the main menu, I removed `Kibana`, and updated to text to match what we use in the Kibana docs.
=> [DOCS] Updates Kibana path for Filebeat

docs/en/observability/ingest-metrics.asciidoc
- [DOCS] Updates Kibana path for Metricbeat (#414)
=> [7.12] [DOCS] Updates Kibana path for Metricbeat (#414)

docs/en/ingest-management/data-streams.asciidoc, docs/en/ingest-management/fleet-overview.asciidoc, docs/en/ingest-management/index.asciidoc
- Add data stream docs to Fleet user guide (#429)
=> [7.12] Add data stream docs to Fleet user guide (#429)

docs/en/ingest-management/data-streams.asciidoc, docs/en/ingest-management/fleet-overview.asciidoc, docs/en/ingest-management/index.asciidoc
- Add data stream docs to Fleet user guide (#429)
=> [7.x] Add data stream docs to Fleet user guide (#429)

docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/tab-widgets/prereq.asciidoc
* Adds missing links to APM integration docs
* Updates ess product links to `{ess-product}`
For https://github.com/elastic/apm-server/issues/4494.
=> Add missing links to APM integration

docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/tab-widgets/prereq.asciidoc
- Add missing links to APM integration (#451)
=> [7.12] Add missing links to APM integration (#451)

docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/tab-widgets/prereq.asciidoc
- Add missing links to APM integration (#451)
=> [7.x] Add missing links to APM integration (#451)

docs/en/observability/ingest-logs.asciidoc, docs/en/observability/synthetics-command-reference.asciidoc, docs/en/observability/synthetics-create-test.asciidoc, docs/en/observability/synthetics-quickstart.asciidoc
Updated for the 7.12.0 release. You'll want to test this by substituting `7.12.0-SNAPSHOT` as the version in any docker commands, since 8.0.0 isn't as relevant to actual users. When the release goes live the version will be the same, but without `SNAPSHOT`.
This includes significant changes to the config syntax.
=> 7.12 Synthetics Docs Changes

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This might help a little with the confusion around installing vs enrolling in Fleet. More work is definitely required though.
=> Minor change to title for agent installation instructions

docs/en/observability/tail-logs.asciidoc
Add video about the logs app to `current` documentation.
Part of https://github.com/elastic/observability-docs/issues/389.
=> docs: add logs app video

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- Update install-elastic-agent.asciidoc (#462)
=> [7.12] Update install-elastic-agent.asciidoc (#462)

docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc, docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc, docs/en/ingest-management/index.asciidoc
This PR is required before we can merge elastic/docs#2097.
Note that some of the file refactoring you'll see in other branches is not present in this PR because it's already implemented in another open PR. I just want to make the minimal changes needed to switch over the chunk level. The other refactoring will be backported after https://github.com/elastic/observability-docs/pull/424 is merged.
=> [7.12] Refactor files to prep for book changing chunk level

docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
This PR adds docs for the `kuberentes_secrets` provider added in https://github.com/elastic/beats/pull/24789
cc: @blakerouse @exekias @ph
=> Add kubernetes_secrets provider docs

docs/en/observability/configure-uptime-settings.asciidoc
Updates the security authorization note for configuring uptime settings.
The existing note is pointing to a tutorial that we wish to replace as part of https://github.com/elastic/kibana/pull/94158.
This updates the link to point to a more appropriate location, and adjusts the note text to indicate that this privilege does not in fact grant cluster administration operations.
=> Update security note for configuring uptime settings

docs/en/observability/configure-uptime-settings.asciidoc
- Update security note for configuring uptime settings (#485)
=> [7.x] Update security note for configuring uptime settings (#485)

docs/en/observability/configure-uptime-settings.asciidoc
- Update security note for configuring uptime settings (#485)
=> [7.10] Update security note for configuring uptime settings (#485)

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/tab-widgets/install-layout.asciidoc
- Document location of Beats logs (#459)
=> [7.12] Document location of Beats logs (#459)

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/tab-widgets/install-layout.asciidoc
- Document location of Beats logs (#459)
=> [7.x] Document location of Beats logs (#459)

.ci/Jenkinsfile
This PR adds a link to the Fleet User Guide to each `apmmachine` comment. See below for an example.
<sup>Oh, and it also adds emojis<sup>because I like emojis</sup></sup>
=> Add Fleet user guide to quick links

docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
This PR adds docs for `kubernetes_leaderelection` provider introduced at https://github.com/elastic/beats/pull/24913
=> Add leaderelection docs

docs/en/ingest-management/tab-widgets/prereq.asciidoc
Adds pointer to docs about generating encryption keys.
Related issue: https://github.com/elastic/kibana/pull/82838. I [said we would add this info](https://github.com/elastic/kibana/pull/82838#issuecomment-730027156), but lost track of the change.
(writers: try to ignore the passive voice. :-) it works better with the current bulleted list structure)
=> Mention command for generating encryption keys

docs/en/ingest-management/tab-widgets/prereq.asciidoc
- Mention command for generating encryption keys (#508)
=> [7.12] Mention command for generating encryption keys (#508)

docs/en/ingest-management/tab-widgets/prereq.asciidoc
- Mention command for generating encryption keys (#508)
=> [7.x] Mention command for generating encryption keys (#508)

docs/en/ingest-management/fleet-overview.asciidoc
- quick fleet server blurb (#539)
=> [7.13] quick fleet server blurb (#539)

docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
This PR changes documentation of how to run Agent on k8s so as to match the leaderelection approach we have adopted. This is quite similar to what we have for Beats (https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html)
=> Improve k8s docs

docs/en/observability/index.asciidoc, docs/en/observability/monitor-aws.asciidoc, docs/en/observability/monitor-azure.asciidoc, docs/en/observability/monitor-gcp.asciidoc, docs/en/observability/tutorials.asciidoc, docs/en/shared/install-configure-filebeat.asciidoc, docs/en/shared/install-configure-metricbeat.asciidoc
- tuts: single source Filebeat and Metricbeat instructions (#633)
=> [7.x] tuts: single source Filebeat and Metricbeat instructions (#633)

docs/en/observability/index.asciidoc, docs/en/observability/monitor-aws.asciidoc, docs/en/observability/monitor-azure.asciidoc, docs/en/observability/monitor-gcp.asciidoc, docs/en/observability/tutorials.asciidoc, docs/en/shared/install-configure-filebeat.asciidoc, docs/en/shared/install-configure-metricbeat.asciidoc
- tuts: single source Filebeat and Metricbeat instructions (#633)
=> [7.13] tuts: single source Filebeat and Metricbeat instructions (#633)

docs/en/observability/index.asciidoc, docs/en/observability/monitor-aws.asciidoc, docs/en/observability/monitor-azure.asciidoc, docs/en/observability/monitor-gcp.asciidoc, docs/en/observability/tutorials.asciidoc, docs/en/shared/install-configure-filebeat.asciidoc, docs/en/shared/install-configure-metricbeat.asciidoc
- tuts: single source Filebeat and Metricbeat instructions (#633)
=> [7.12] tuts: single source Filebeat and Metricbeat instructions (#633)

docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
Changes to get the K8s documentation building.
These docs still need more work (for example, there are inconsistencies across the topics and they should be tested for usability).
TODO:
=> Get K8s documentation building

docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
- Get K8s documentation building (#645)
=> [7.x] Get K8s documentation building (#645)

docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
- Get K8s documentation building (#645)
=> [7.13] Get K8s documentation building (#645)

.gitignore
The obs-docs `.gitignore` file only exists in master. I think it'd be useful to add this file to other production branches so the `html_docs` directory isn't always getting in the way.
=> Add .gitignore to 7.x

.gitignore
- Add .gitignore to 7.x (#676)
=> [7.13] Add .gitignore to 7.x (#676)

docs/en/observability/configure-uptime-settings.asciidoc, docs/en/observability/create-alerts.asciidoc, docs/en/observability/infrastructure-threshold-alert.asciidoc, docs/en/observability/inspect-uptime-duration-anomalies.asciidoc, docs/en/observability/logs-threshold-alert.asciidoc, docs/en/observability/metrics-threshold-alert.asciidoc, docs/en/observability/monitor-status-alert.asciidoc, docs/en/observability/observability-introduction.asciidoc, docs/en/observability/observability-ui.asciidoc, docs/en/observability/synthetics-visualize.asciidoc, docs/en/observability/uptime-duration-anomaly-alert.asciidoc, docs/en/observability/uptime-tls-alert.asciidoc, docs/en/observability/view-monitor-status.asciidoc
- Update alerting terminology (#679)
=> [7.x] Update alerting terminology (#679)

docs/en/observability/synthetics-create-test.asciidoc
- Clarify no import dependencies can be used with inline scripts (#682)
=> [7.13] Clarify no import dependencies can be used with inline scripts (#682)

docs/en/observability/synthetics-create-test.asciidoc
- Clarify no import dependencies can be used with inline scripts (#682)
=> [7.x] Clarify no import dependencies can be used with inline scripts (#682)

docs/en/ingest-management/fleet/fleet-limitations.asciidoc
Providing feature updates here. This still doesn't have updated limits on the number of agents, but tracking that here https://github.com/elastic/fleet-server/issues/134
=> Updating limitations for 7.13

docs/en/ingest-management/fleet/fleet-limitations.asciidoc
- Updating limitations for 7.13 (#694)
=> [7.x] Updating limitations for 7.13 (#694)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Preview is [here](https://observability-docs_702.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-7.13.0.html).
Summary of changes:
- Moved the breaking changes section to match order in Kibana docs.
- Commented out sections that do not yet have content: Security updates, Deprecations, New features, sub-sections for Elastic Agent.
- Added Fleet-related info copied from the Kibana release notes. Duplicating through copy/paste for now (not ideal, but we can figure out a better long-term solution for GA).
We need to add items for Elastic Agent because they are currently missing, but it's vital that we get this merged before the release goes live.
=> Clean up release notes and add items from Kibana

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
The breaking change about removing agent routes needs to be qualified so it's clear in the title that we're talking about Kibana.
=> Clarify breaking changes for 7.13

docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- Add link to Fleet settings topic (#713)
=> [7.x] Add link to Fleet settings topic (#713)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Clarify breaking changes for 7.13 (#712)
=> [7.13] Clarify breaking changes for 7.13 (#712)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Clarify breaking changes for 7.13 (#712)
=> [7.x] Clarify breaking changes for 7.13 (#712)

docs/en/ingest-management/fleet/fleet-server.asciidoc
Closes #643 and https://github.com/elastic/observability-docs/issues/640
This info was dumped into a meta issue awhile back ago. Need confirmation that the details are correct.
=> Add stack compatibility info to Fleet Server docs

docs/en/ingest-management/fleet/fleet-server.asciidoc
- Add stack compatibility info to Fleet Server docs (#731)
=> [7.13] Add stack compatibility info to Fleet Server docs (#731)

docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
@EricDavisX  It sounds like this note would be useful to macOS users, so I've added it back in.
Do we want to say where the extension lives?
=> Add note about removing system extension during uninstall

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Adds 7.13.1 Elastic Agent and Fleet release notes (#744)
=> [7.x] Adds 7.13.1 Elastic Agent and Fleet release notes (#744)

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Adds 7.13.1 Elastic Agent and Fleet release notes (#744)
=> [7.13] Adds 7.13.1 Elastic Agent and Fleet release notes (#744)

docs/en/observability/configure-logs-sources.asciidoc
This PR adds content regarding Kibana index patterns that are available for selection in the Logs app settings. 
https://observability-docs_725.docs-preview.app.elstc.co/guide/en/observability/master/configure-data-sources.html#edit-config-settings
=> Logs app: Add index pattern content

docs/en/observability/configure-logs-sources.asciidoc
- Logs app: Add index pattern content (#725)
=> [7.13] Logs app: Add index pattern content (#725)

docs/en/observability/configure-logs-sources.asciidoc
- Logs app: Add index pattern content (#725)
=> [7.x] Logs app: Add index pattern content (#725)

docs/en/ingest-management/troubleshooting.asciidoc
This PR updates the Kibana config file settings called out in the Troubleshooting topic. For 7.13, the `xpack.fleet.agents.tlsCheckDisabled: true` setting was removed.
https://observability-docs_772.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-troubleshooting.html#fleet-server-not-in-kibana-cloud
Closes https://github.com/elastic/observability-docs/issues/526
=> Fleet troubleshooting: update Kibana config file settings

docs/en/ingest-management/troubleshooting.asciidoc
- Fleet troubleshooting: update Kibana config file settings (#772)
=> [7.13] Fleet troubleshooting: update Kibana config file settings (#772)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Copies over release notes from Kibana so that they appear in the Fleet User Guide.
Do we need to add anything else? Anything for Elastic Agent?
=> Add Fleet and Agent release notes for 7.13.2

docs/en/observability/create-alerts.asciidoc, docs/en/observability/observability-ui.asciidoc
Some recent PRs have moved around some of the alerting docs within the Kibana docs, so some of the links need to be updated.
Relevant PRs:
* https://github.com/elastic/kibana/pull/101323
* https://github.com/elastic/kibana/pull/101498
* https://github.com/elastic/kibana/pull/101420
=> [Docs] Update cross-document links to Kibana Alerting docs

docs/en/observability/create-alerts.asciidoc, docs/en/observability/observability-ui.asciidoc
- [Docs] Update cross-document links to Kibana Alerting docs (#779)
=> [7.x] [Docs] Update cross-document links to Kibana Alerting docs (#779)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add release notes for 7.13.2 (#787)
=> [7.x] Add release notes for 7.13.2 (#787)

docs/en/ingest-management/fleet/fleet-server.asciidoc
Adds ECE 2.10 prereq for using Fleet Server. When the 2.10 is live and the docs are available, we can add links to the documentation about wildcard domains and certificates
=> Add ECE 2.10 requirements for Fleet Server

docs/en/ingest-management/fleet/fleet-server.asciidoc
- Add ECE 2.10 requirements for Fleet Server (#778)
=> [7.13] Add ECE 2.10 requirements for Fleet Server (#778)

docs/en/observability/logs-threshold-alert.asciidoc
- [Logs] Add some performance recommendations for the log threshold rule type (#804)
=> [7.x] [Logs] Add some performance recommendations for the log threshold rule type (#804)

docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
This PR removes section for managed elastic-agent on k8s since we don't currently officially support it.
K8s manifests are also being removed: https://github.com/elastic/beats/pull/26368
=> Remove docs for managed agent on k8s

docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- Hide docs for mamanaged agent on k8s (#799)
=> [7.x] Hide docs for mamanaged agent on k8s (#799)

docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- Hide docs for mamanaged agent on k8s (#799)
=> [7.13] Hide docs for mamanaged agent on k8s (#799)

docs/en/observability/index.asciidoc, docs/en/observability/synthetics-params-secrets.asciidoc
Fixes #805
Adds docs for params and secrets.
Backport of https://github.com/elastic/observability-docs/pull/806
=> [7.x][Backport][Synthetics] Docs on secrets and params 

docs/en/ingest-management/fleet/fleet-server.asciidoc
Adds asterisks that were inadvertently gobbled by GitHub in the original issue.
This point needs more details, but it will be added by a follow-up PR tracked in https://github.com/elastic/observability-docs/issues/825.
=> Adds missing asterisks to a Fleet Server requirement related to wildcard domains

docs/en/observability/metrics-threshold-alert.asciidoc
The [example](https://www.elastic.co/guide/en/observability/7.13/metrics-threshold-alert.html#metrics-conditions) documentation page for the metrics threshold is a bit unclear on the fact that the conditions are combined. This small change tries to make it more explicit that both conditions need to be met in order for the alert to be triggered.
@elastic/obs-docs
=> Make more clear in the example that conditions accumulate

docs/en/ingest-management/elastic-agent/elastic-agent-logging.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/tab-widgets/logging-widget.asciidoc, docs/en/ingest-management/tab-widgets/logging.asciidoc
This PR adds the logging content for Elastic agent. 
https://observability-docs_808.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-standalone-logging-config.html
Closes https://github.com/elastic/observability-docs/issues/699
=> Elastic agent: Add logging content

docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/tab-widgets/logging-widget.asciidoc, docs/en/ingest-management/tab-widgets/logging.asciidoc
- Elastic agent: Add logging content (#808)
=> [7.x] Elastic agent: Add logging content (#808)

docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/tab-widgets/logging-widget.asciidoc, docs/en/ingest-management/tab-widgets/logging.asciidoc
- Elastic agent: Add logging content (#808)
=> [7.13] Elastic agent: Add logging content (#808)

docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/tab-widgets/logging-widget.asciidoc, docs/en/ingest-management/tab-widgets/logging.asciidoc
- Elastic agent: Add logging content (#808)
=> [7.14] Elastic agent: Add logging content (#808)

docs/en/ingest-management/fleet/fleet-server.asciidoc
- Adds missing asterisks to limitation about wildcard domains (#829)
=> [7.13] Adds missing asterisks to limitation about wildcard domains (#829)

docs/en/ingest-management/fleet/fleet-server.asciidoc
- Adds missing asterisks to limitation about wildcard domains (#829)
=> [7.14] Adds missing asterisks to limitation about wildcard domains (#829)

docs/en/ingest-management/fleet/fleet-server.asciidoc
- Adds missing asterisks to limitation about wildcard domains (#829)
=> [7.x] Adds missing asterisks to limitation about wildcard domains (#829)

docs/en/observability/index.asciidoc, docs/en/observability/synthetics-configuration.asciidoc, docs/en/observability/synthetics-params-secrets.asciidoc
=> add synthetics configuration docs

docs/en/observability/index.asciidoc, docs/en/observability/synthetics-configuration.asciidoc, docs/en/observability/synthetics-params-secrets.asciidoc
- add synthetics configuration docs (#847)
=> [7.x] add synthetics configuration docs (#847)

docs/en/ingest-management/fleet/fleet-settings.asciidoc
Closes elastic/observability-docs#758.
This PR assumes that we will continue to provide Fleet kibana.yml settings along with the other config settings in the Kibana Guide.
If we decide to provide kibana.yml settings in the Fleet User guide, we should pull in the topic from the Kibana docs so that it appears in both places.
@jen-huang Let me know which approach you prefer (a link as shown in this PR, or an include that pulls in the Fleet settings). Pulling settings in from Kibana would add another dependency to the doc build. I think we will always have some problems with fragmentation until we move to a doc system where documentation no longer lives in separate silos.
=> Add pointer to docs about kibana.yml settings

docs/en/ingest-management/fleet/fleet-settings.asciidoc
- Add pointer to docs about kibana.yml settings (#821)
=> [7.14] Add pointer to docs about kibana.yml settings (#821)

docs/en/fleet-developer/fleet-architecture.asciidoc, docs/en/fleet-developer/fleet-ports.asciidoc, docs/en/fleet-developer/fleet-security-model.asciidoc, docs/en/ingest-management/agent-policies.asciidoc, docs/en/ingest-management/commands.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc, docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc, docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/fleet/fleet-limitations.asciidoc, docs/en/ingest-management/fleet/fleet-server.asciidoc, docs/en/ingest-management/fleet/fleet-settings.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
Closes #820
Removes the following warning from the published docs for Fleet and Elastic Agent:
=> Remove beta admonitions from Fleet and Elastic Agent docs

docs/en/ingest-management/agent-policies.asciidoc, docs/en/ingest-management/commands.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc, docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc, docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/fleet/fleet-limitations.asciidoc, docs/en/ingest-management/fleet/fleet-server.asciidoc, docs/en/ingest-management/fleet/fleet-settings.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Remove beta admonitions from Fleet and Elastic Agent docs (#871)
=> [7.14] Remove beta admonitions from Fleet and Elastic Agent docs (#871)

docs/en/ingest-management/agent-policies.asciidoc, docs/en/ingest-management/commands.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc, docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc, docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/fleet/fleet-limitations.asciidoc, docs/en/ingest-management/fleet/fleet-server.asciidoc, docs/en/ingest-management/fleet/fleet-settings.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/overview.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Remove beta admonitions from Fleet and Elastic Agent docs (#871)
=> [7.x] Remove beta admonitions from Fleet and Elastic Agent docs (#871)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
This PR adds a placeholder for 7.13.3 and 7.13.4 release notes that are missing.
We need to fill in details so that the download page has something to link to.
=> Add missing relnotes for 7.13.3 and 7.13.4

docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
This PR adds a note about avoid using leaderelection in large clusters and instead consider using a Deployment in addition to the Daemonset so as to specify different resources according to the cluster's needs.
We have a similar note for Beats too: https://www.elastic.co/guide/en/beats/metricbeat/7.13/running-on-kubernetes.html#_deploying_metricbeat_to_collect_cluster_level_metrics_in_large_clusters
=> Add note about avoid using leaderelection in large clusters

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- [Elastic Agent] Document usage inside a container (#757)
=> [7.14] [Elastic Agent] Document usage inside a container (#757)

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- [Elastic Agent] Document usage inside a container (#757)
=> [7.x] [Elastic Agent] Document usage inside a container (#757)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add missing relnotes for 7.13.3 and 7.13.4 (#883)
=> [7.14] Add missing relnotes for 7.13.3 and 7.13.4 (#883)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add missing relnotes for 7.13.3 and 7.13.4 (#883)
=> [7.13] Add missing relnotes for 7.13.3 and 7.13.4 (#883)

docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add missing relnotes for 7.13.3 and 7.13.4 (#883)
=> [7.x] Add missing relnotes for 7.13.3 and 7.13.4 (#883)

docs/en/ingest-management/fleet/fleet-api-docs.asciidoc, docs/en/ingest-management/index.asciidoc
Hello, this is a first part of support to fix / implement the Fleet API Docs per:
https://github.com/elastic/observability-docs/issues/881
I'm not 100% sure if I have all the bits in place to instantiate a new file and have it show up in the right hand side widget.  But I'll try it out.
2 subsequent prs (one to elasticsearch and one more to observability-docs) will follow to point to this new 'api docs' home page location.  we can change whats on the page anytime, but it seemed prudent to have it in place for google searchability and linking from other projects, etc.
=> small placeholder file and link to git repo api docs

docs/en/ingest-management/fleet/fleet-api-docs.asciidoc, docs/en/ingest-management/index.asciidoc
- small placeholder file and link to git repo api docs (#882)
=> [7.x] small placeholder file and link to git repo api docs (#882)

docs/en/ingest-management/fleet/fleet-api-docs.asciidoc, docs/en/ingest-management/index.asciidoc
- small placeholder file and link to git repo api docs (#882)
=> [7.14] small placeholder file and link to git repo api docs (#882)

docs/en/ingest-management/overview.asciidoc
one more contribution towards:
https://github.com/elastic/observability-docs/issues/881
just a quick hyperlink addition.
=> Link Fleet Overview to Fleet API Docs page

docs/en/ingest-management/overview.asciidoc
- Link Fleet Overview to Fleet API Docs page (#903)
=> [7.14] Link Fleet Overview to Fleet API Docs page (#903)

docs/en/ingest-management/overview.asciidoc
- Link Fleet Overview to Fleet API Docs page (#903)
=> [7.x] Link Fleet Overview to Fleet API Docs page (#903)

docs/en/ingest-management/faq.asciidoc
- example for resetting a package to bring back the dashboard assets (#898)
=> [7.x] example for resetting a package to bring back the dashboard assets (#898)

docs/en/ingest-management/faq.asciidoc
- example for resetting a package to bring back the dashboard assets (#898)
=> [7.14] example for resetting a package to bring back the dashboard assets (#898)

docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
This PR adds Logstash output information to the existing topic about agent policy settings and moves the topic to appear nested under the topic about running standalone.
Why? https://github.com/elastic/observability-docs/pull/460 is a work-in-progress and will require a thorough review. This PR provides users with essential info while we wait for the longer, more detailed PR to land.
https://observability-docs_904.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-configuration.html
=> Add logstash section to existing elastic agent configuration docs

docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- Add logstash section to existing configuration docs (#904)
=> [7.x] Add logstash section to existing configuration docs (#904)

docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- Add logstash section to existing configuration docs (#904)
=> [7.14] Add logstash section to existing configuration docs (#904)

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add known issue about secrets entered in Kibana (#896)
=> [7.14] Add known issue about secrets entered in Kibana (#896)

docs/en/ingest-management/faq.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add known issue about secrets entered in Kibana (#896)
=> [7.x] Add known issue about secrets entered in Kibana (#896)

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc
Closes #770.
Most of the info requested in #770 is already covered in #897.
The docs build for this PR will fail until https://github.com/elastic/observability-docs/pull/897 is merged.
=> Mention Elastic Agent monitoring in the Fleet docs

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc
- Mention Elastic Agent monitoring in the Fleet docs (#899)
=> [7.14] Mention Elastic Agent monitoring in the Fleet docs (#899)

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc
- Mention Elastic Agent monitoring in the Fleet docs (#899)
=> [7.x] Mention Elastic Agent monitoring in the Fleet docs (#899)

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/tab-widgets/install.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Add info about --insecure flag to agent install docs (#902)
=> [7.14] Add info about --insecure flag to agent install docs (#902)

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/getting-started-traces.asciidoc, docs/en/ingest-management/getting-started.asciidoc, docs/en/ingest-management/tab-widgets/install.asciidoc, docs/en/ingest-management/troubleshooting.asciidoc
- Add info about --insecure flag to agent install docs (#902)
=> [7.x] Add info about --insecure flag to agent install docs (#902)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Remove review comments and add missing support statement (#932)
=> [7.x] Remove review comments and add missing support statement (#932)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Remove review comments and add missing support statement (#932)
=> [7.14] Remove review comments and add missing support statement (#932)

docs/en/ingest-management/data-streams.asciidoc
- docs: update apm ds naming scheme (#946)
=> [7.x] docs: update apm ds naming scheme (#946)

docs/en/ingest-management/data-streams.asciidoc
- docs: update apm ds naming scheme (#946)
=> [7.14] docs: update apm ds naming scheme (#946)

docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add Fleet-related Kibana relnotes (#951)
=> [7.x] Add Fleet-related Kibana relnotes (#951)

docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add Fleet-related Kibana relnotes (#951)
=> [7.14] Add Fleet-related Kibana relnotes (#951)

docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add known issue about problem with agents enrolled through a proxy (#961)
=> [7.x] Add known issue about problem with agents enrolled through a proxy (#961)

docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add known issue about problem with agents enrolled through a proxy (#961)
=> [7.14] Add known issue about problem with agents enrolled through a proxy (#961)

docs/en/ingest-management/troubleshooting.asciidoc
This adds an entry to the 7.14 Fleet [troubleshooting page](https://www.elastic.co/guide/en/fleet/7.14/fleet-troubleshooting.html), since version 7.14 of Fleet is not working with the recently released ECE 2.10. Here's an [issue with the details](https://github.com/elastic/support-known-issues/issues/791). I'm putting similar warnings in the Cloud ECE docs
Please note that the workaround isn't ready yet so we need to wait for that before merging.
I'd really appreciate any help with labels, and I assume there's no backporting since this affects and targets only the 7.14 release.
=> Add issue to Fleet troubleshooting page for ECE 2.10 / Fleet 7.14 issue

docs/en/ingest-management/troubleshooting.asciidoc
Sorry for the churn! This is a small update to #968 to fix my "Elastic Elastic Stack" references on the troubleshooting page (I didn't realize that `{stack}` resolves to `Elastic Stack`).
=> Update troubleshooting page to remove my "Elastic Elastic Stack" references

docs/en/ingest-management/fleet/fleet-settings.asciidoc
Minor change, but since there are settings in multiple places (UI, Kibana config, agent policy), I think it helps to disambiguate.
=> Clarify topic title for Fleet UI settings

docs/en/ingest-management/troubleshooting.asciidoc
- Remove SDH reference in documentation (#976)
=> [7.x] Remove SDH reference in documentation (#976)

docs/en/ingest-management/troubleshooting.asciidoc
- Remove SDH reference in documentation (#976)
=> [7.13] Remove SDH reference in documentation (#976)

docs/en/ingest-management/troubleshooting.asciidoc
- Remove SDH reference in documentation (#976)
=> [7.14] Remove SDH reference in documentation (#976)

docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
The workaround I provided for #938 is not totally accurate as it's not working in cloud where pre configured policies have different ids and properties.
That PR update the instructions so it's working in cloud too.
=> [Fleet] Fix workaround for missing Fleet server policies for cloud

docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
Add details for how logging.metrics.enabled is used by the agent and underlying beats.
=> Add details for logging.metrics.enabled

docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-standalone-logging.asciidoc
Backport the following commit to 7.x:
- Add details for logging.metrics.enabled (#853)
=> [7.x] Add details for logging.metrics.enabled (#853)

docs/en/ingest-management/index.asciidoc
Fixes a bug that broke links from `observability-docs` to `apm-agent-php`. Closes https://github.com/elastic/observability-docs/issues/990.
=> docs: fix links to PHP agent documentation

docs/en/ingest-management/index.asciidoc
- docs: fix links to PHP agent documentation (#992)
=> [7.x] docs: fix links to PHP agent documentation (#992)

docs/en/ingest-management/index.asciidoc
- docs: fix links to PHP agent documentation (#992)
=> [7.15] docs: fix links to PHP agent documentation (#992)

docs/en/ingest-management/index.asciidoc
- docs: fix links to PHP agent documentation (#992)
=> [7.14] docs: fix links to PHP agent documentation (#992)

docs/en/ingest-management/beats-agent-comparison.asciidoc
Add capabilities to beats and agent comparison table to highlight benefits of Elastic Agent and Fleet, and capabilities that only Beats supports
CC @nimarezainia
=> Add capabilities to beats and agent comparison table

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Add capabilities to beats and agent comparison table (#943)
=> [7.x] Add capabilities to beats and agent comparison table (#943)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Add capabilities to beats and agent comparison table (#943)
=> [7.14] Add capabilities to beats and agent comparison table (#943)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Add capabilities to beats and agent comparison table (#943)
=> [7.15] Add capabilities to beats and agent comparison table (#943)

docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Preview link: https://observability-docs_1010.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-7.14.1.html 
@andresrc I know the new changelog process is not ready, but we still need some kind of release notes for Fleet and Elastic Agent in 7.14.1. So I've created this placeholder where we can add stuff.
For  Elastic Agent, should I pull changes from the [changelog](https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/CHANGELOG.next.asciidoc)? It looks like developers are still updating CHANGELOG.next.asciidoc, but no one has created a versioned changelog since 7.9. If someone can tell me what to add for 7.14.x, I'll include any relevant info here.
I'll leave the placeholder text in 7.14.0 in case we want to add anything to that section.
=> Add skeleton files for 7.14.1 release notes

docs/en/ingest-management/fleet/fleet-server.asciidoc
- Update Fleet Server docs with link to related ECE info (#1020)
=> [7.x] Update Fleet Server docs with link to related ECE info (#1020)

docs/en/observability/monitor-aws.asciidoc
Minor change from gerund to a simple verb for consistency.
=> Make AWS monitoring tutorial title consistent with other tutorials

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
This PR adds metrics endpoint debugging information.
Closes https://github.com/elastic/observability-docs/issues/891.
=> Add metrics endpoint debugging info for container docs

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- Add metrics endpoint debugging info for container docs (#1014)
=> [7.x] Add metrics endpoint debugging info for container docs (#1014)

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- Add metrics endpoint debugging info for container docs (#1014)
=> [7.15] Add metrics endpoint debugging info for container docs (#1014)

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- Add metrics endpoint debugging info for container docs (#1014)
=> [7.14] Add metrics endpoint debugging info for container docs (#1014)

docs/en/observability/index.asciidoc, docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc, docs/en/observability/troubleshoot-uptime.asciidoc
Resolves https://github.com/elastic/observability-docs/issues/1018.
The goal of this PR is to introduce a troubleshooting page we can link to from the Uptime app in certain cases. Today, the only issue we have is this mapping problem.
Our goal is to link to this docs page from the Uptime UI when this issue occurs.
=> [Uptime] Add troubleshooting page for Uptime guide

docs/en/ingest-management/beats-agent-comparison.asciidoc
I noticed that we are missing Endpoint security and Osquery in the beats/agent comparison docs https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html.  These are key advantages and reasons to adopt Elastic Agent so we should include them in the comparison.
CC @melissaburpo @caitlinbetz
=> Add Endpoint security and Osquery to beats/agent comparison

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Add Endpoint security and Osquery to beats/agent comparison (#1058)
=> [7.x] Add Endpoint security and Osquery to beats/agent comparison (#1058)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Add Endpoint security and Osquery to beats/agent comparison (#1058)
=> [7.15] Add Endpoint security and Osquery to beats/agent comparison (#1058)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Add Endpoint security and Osquery to beats/agent comparison (#1058)
=> [7.14] Add Endpoint security and Osquery to beats/agent comparison (#1058)

docs/en/ingest-management/overview.asciidoc
Adds link to improve visibility of integrations documentation, which currently lives in the new doc system.
=> Link to Integrations documentation from overview

docs/en/ingest-management/overview.asciidoc
- Link to Integrations documentation from overview (#1076)
=> [7.x] Link to Integrations documentation from overview (#1076)

docs/en/ingest-management/overview.asciidoc
- Link to Integrations documentation from overview (#1076)
=> [7.15] Link to Integrations documentation from overview (#1076)

docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
Prior to this change the docs didn't factor in standalone agent. They now do, and correctly describe what to do in this case. In this
situation they must be vague because the standalone agent use case gives users a lot of power and discretion over how they set things up. We can only give a rough guide.
=> [Uptime] Clarify docs around mapping issues / standalone agent

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.15.asciidoc
Link to preview: https://observability-docs_1080.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-7.15.0.html
Adds placeholder file for the release notes. 
We are still building the release notes by hand, so I need folks from the Fleet and Elastic Agent teams to identify missing stuff (especially the agent team...I need to know anything from the changelog that you want to highlight).
=> Add 7.15 release notes

docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Preview: https://observability-docs_1081.docs-preview.app.elstc.co/guide/en/fleet/7.14/release-notes-7.14.2.html
Adds placeholder file for the release notes.
We are still building the release notes by hand, so I need folks from the Fleet and Elastic Agent teams to identify missing stuff (especially the agent team...I need to know anything from the changelog that you want to highlight).
=> Add 7.14.2  release notes

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- Update elastic-agent Url docker official repo (#1099)
=> [7.x] Update elastic-agent Url docker official repo (#1099)

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- Update elastic-agent Url docker official repo (#1099)
=> [7.15] Update elastic-agent Url docker official repo (#1099)

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- Update elastic-agent Url docker official repo (#1099)
=> [7.14] Update elastic-agent Url docker official repo (#1099)

docs/en/ingest-management/overview.asciidoc
While working on https://github.com/elastic/kibana/pull/113858, I was looking for if we have any documentation around licensing for custom registry URL that needs to be corrected. I did not find any, but came across this which needs to be updated to reflect the `ingestManager` -> `fleet` setting renaming that happened a long time ago.
Could whoever reviews this help me with merging and backporting this to all versions of the docs that contain this? (Looks like >= 7.13)
=> Fix Fleet setting key for registry proxy URL

docs/en/ingest-management/overview.asciidoc
- Fix Fleet setting key for custom registry URL (#1114)
=> [7.x] Fix Fleet setting key for custom registry URL (#1114)

docs/en/ingest-management/overview.asciidoc
- Fix Fleet setting key for custom registry URL (#1114)
=> [7.13] Fix Fleet setting key for custom registry URL (#1114)

docs/en/ingest-management/overview.asciidoc
- Fix Fleet setting key for custom registry URL (#1114)
=> [7.15] Fix Fleet setting key for custom registry URL (#1114)

docs/en/ingest-management/overview.asciidoc
- Fix Fleet setting key for custom registry URL (#1114)
=> [7.14] Fix Fleet setting key for custom registry URL (#1114)

.ci/Jenkinsfile, README.md, docs/en/ingest-management/index.asciidoc, docs/en/integrations/air-gapped.asciidoc
Changes the name of the Fleet User Guide as described in elastic/observability-docs#1104.
Related to https://github.com/elastic/docs/pull/2238 and https://github.com/elastic/observability-docs/issues/1104
=> Rename Fleet User Guide

docs/en/ingest-management/index.asciidoc, docs/en/integrations/air-gapped.asciidoc
- Rename Fleet User Guide (#1115)
=> [7.x] Rename Fleet User Guide (#1115)

docs/en/ingest-management/index.asciidoc, docs/en/integrations/air-gapped.asciidoc
- Rename Fleet User Guide (#1115)
=> [7.15] Rename Fleet User Guide (#1115)

docs/en/ingest-management/index.asciidoc
- Rename Fleet User Guide (#1115)
=> [7.13] Rename Fleet User Guide (#1115)

docs/en/ingest-management/index.asciidoc
- Rename Fleet User Guide (#1115)
=> [7.14] Rename Fleet User Guide (#1115)

docs/en/observability/synthetics-create-test.asciidoc, docs/en/observability/synthetics-quickstart.asciidoc
In https://github.com/elastic/synthetics/pull/378 we move to favoring the `synthetics-demo` repo for examples, and delete the examples the current docs point to. We need to update the docs to point to the equivalent resources there.
We should merge this PR first.
=> Favor synthetics-demo repo over synthetics/examples.

docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
Fixed typo, replacing `kuberentes` with `kubernetes`
=> Update elastic-agent-providers.asciidoc - Fixed typo, replacing `kuberentes` with `kubernetes`

docs/en/observability/analyze-monitors.asciidoc, docs/en/observability/categorize-logs.asciidoc, docs/en/observability/configure-logs-sources.asciidoc, docs/en/observability/configure-metrics-sources.asciidoc, docs/en/observability/configure-uptime-settings.asciidoc, docs/en/observability/infrastructure-threshold-alert.asciidoc, docs/en/observability/ingest-logs.asciidoc, docs/en/observability/ingest-metrics.asciidoc, docs/en/observability/ingest-uptime.asciidoc, docs/en/observability/inspect-log-anomalies.asciidoc, docs/en/observability/inspect-metric-anomalies.asciidoc, docs/en/observability/inspect-uptime-duration-anomalies.asciidoc, docs/en/observability/instrument-apps.asciidoc, docs/en/observability/logs-threshold-alert.asciidoc, docs/en/observability/metrics-app-fields.asciidoc, docs/en/observability/metrics-threshold-alert.asciidoc, docs/en/observability/monitor-aws-services.asciidoc, docs/en/observability/monitor-servers.asciidoc, docs/en/observability/monitor-status-alert.asciidoc, docs/en/observability/synthetics-params-secrets.asciidoc, docs/en/observability/synthetics-quickstart-fleet.asciidoc, docs/en/observability/synthetics-visualize.asciidoc, docs/en/observability/tail-logs.asciidoc, docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc, docs/en/observability/uptime-duration-anomaly-alert.asciidoc, docs/en/observability/uptime-tls-alert.asciidoc, docs/en/observability/view-infrastructure-metrics.asciidoc, docs/en/observability/view-monitor-status.asciidoc
This PR adds missing `[discrete]` markers. These updates are to prepare for increasing the chunk level to `2` within the Observability guide.
https://observability-docs_1134.docs-preview.app.elstc.co/guide/en/observability/master/index.html
https://github.com/elastic/docs/pull/2242
=> Add discrete markers to prepare for chunk level increase

docs/en/ingest-management/commands.asciidoc, docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Backport for https://github.com/elastic/observability-docs/pull/1159
=> [7.x] Docs for --fleet-server-es-insecure (#1159)

docs/en/observability/apm.asciidoc, docs/en/observability/ingest-traces.asciidoc, docs/en/observability/instrument-apps.asciidoc, docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc, docs/en/shared/configure-apm-server/content.asciidoc, docs/en/shared/spin-up-the-stack/content.asciidoc
- docs: update APM links (#1181)
=> [7.16] docs: update APM links (#1181)

docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
This PR adds a tip pointing to Fleet-managed Agent docs for ECK (similarly to the standalone section).
=> Add tip about ECK to Fleet-managed Agent section

docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
- Add tip about ECK to Fleet-managed Agent section (#1150)
=> [8.0] Add tip about ECK to Fleet-managed Agent section (#1150)

docs/en/ingest-management/fleet/fleet-server.asciidoc, docs/en/ingest-management/overview.asciidoc
Removes info from the Fleet Developer Guide in preparation for removing it from the doc build.
=> Move info from dev guide to Fleet/Agent guide

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
Mark `logging.ecs` and `logging.json` as deprecated in 7.16 as both settings will be disables (defaulted to true) in the 8.x releases as part of the Elastic Stack shipping ECS logs.
=> mark logging.ecs and logging.json as deprecated

docs/en/ingest-management/beats-agent-comparison.asciidoc
Closes #1207 
Preview: https://observability-docs_1238.docs-preview.app.elstc.co/guide/en/fleet/master/beats-agent-comparison.html
We should backport this to the earliest place where we show support.
=> Indicate that Fleet-managed agents do not support http json input

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Indicate that Fleet-managed agents do not support http json input (#1238)
=> [7.16] Indicate that Fleet-managed agents do not support http json input (#1238)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Indicate that Fleet-managed agents do not support http json input (#1238)
=> [7.15] Indicate that Fleet-managed agents do not support http json input (#1238)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Indicate that Fleet-managed agents do not support http json input (#1238)
=> [7.14] Indicate that Fleet-managed agents do not support http json input (#1238)

docs/en/ingest-management/beats-agent-comparison.asciidoc
- Indicate that Fleet-managed agents do not support http json input (#1238)
=> [8.0] Indicate that Fleet-managed agents do not support http json input (#1238)

docs/en/observability/gcp-dataflow.asciidoc, docs/en/observability/gcp-topic.asciidoc, docs/en/observability/monitor-gcp.asciidoc
I just realized that the steps for creating the GCP Pub/Sub subscription should be used in both **Monitor Google Cloud Platform** and **GCP Dataflow templates** tutorials. I'm sending this PR to amend this.
=> [monitor-gcp] create Pub/Sub subscription in both GCP tutorials

docs/en/logs/page_header.html, docs/en/metrics/page_header.html, docs/en/uptime/page_header.html
Closes https://github.com/elastic/observability-docs/issues/793
7.9 versions of our old docs are not flagged as outdated. These files add a header to the page that redirects users to the current version of the observability docs.
Previews of the header are here:
https://observability-docs_1264.docs-preview.app.elstc.co/guide/en/uptime/7.9/index.html
https://observability-docs_1264.docs-preview.app.elstc.co/guide/en/logs/guide/current/index.html
https://observability-docs_1264.docs-preview.app.elstc.co/guide/en/metrics/guide/current/index.html
=> Add header to legacy observability docs

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Add some explanation for the agent.monitoring.pprof option, and when to
disable it, in the stand-alone documentation.
=> Add agent.monitoring.pprof doc

docs/en/ingest-management/fleet/add-fleet-server.asciidoc, docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc, docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc, docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc, docs/en/ingest-management/fleet/fleet-server.asciidoc, docs/en/ingest-management/index.asciidoc
We've added so much content to the Fleet Server topic that it's hard to find the basic steps for adding a Fleet Server, especially in our current doc system. I was using the docs today and felt a bit frustrated scrolling through all the stuff I didn't want to see.
So I propose that we break this page down into multiple pages. WDYT? Any objections?
Feel free to scan the content. The only new parts are the list of links and small tweaking of intros to make the pages work better on their onw.
=> Reorganize Fleet Server content

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
* Add agent.monitoring.pprof doc
Add some explanation for the agent.monitoring.pprof option, and when to
disable it, in the stand-alone documentation.
* Apply suggestions from code review
Co-authored-by: DeDe Morton <dede.morton@elastic.co>
Co-authored-by: DeDe Morton <dede.morton@elastic.co>
=> Backport #1265

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
As discussed in https://github.com/elastic/beats/issues/29108 we will be changing the default `agent.monitoring.pprof` option to false.
Behaviour of the option has also slightly changed to also apply to beats that the agent runs: https://github.com/elastic/beats/pull/29155
=> Change agent pprof default to false

docs/en/observability/ingest-splunk.asciidoc
The docs PR to upgrade to `7.16` (elastic/docs#2299) is failing due to a broken link in the observability-docs repo:
```
14:29:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/7.13/ingest-splunk.html contains broken links to:
14:29:51 INFO:build_docs:   - en/fleet/current/fleet-quick-start.html
14:29:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/7.14/ingest-splunk.html contains broken links to:
14:29:51 INFO:build_docs:   - en/fleet/current/fleet-quick-start.html
14:29:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/7.15/ingest-splunk.html contains broken links to:
14:29:51 INFO:build_docs:   - en/fleet/current/fleet-quick-start.html
```
This PR needs to be backported to `7.14` and `7.13`.
=> [7.15] docs: fix bad link for 7.16

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Adds release notes to the Elastic Agent and Fleet Guide.
Preview link: https://observability-docs_1319.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-7.16.0.html 
Reviewers: Please respond to these questions:
https://github.com/elastic/beats/pull/28165
https://github.com/elastic/beats/pull/28260
https://github.com/elastic/beats/pull/28096
NOTE: The diff includes a template for the next update. You can ignore everything after after:
```
// ---------------------
//TEMPLATE
```
Closes #1319
=> Add 7.16 release notes for Elastic Agent and Fleet

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
- Add 7.16 release notes for Elastic Agent and Fleet (#1319)
=> [7.16] Add 7.16 release notes for Elastic Agent and Fleet (#1319)

.mergify.yml
This is just a proposal to use mergify in order to:
* create the backports automatically
* notify when a backport has a conflict to be resolved.
* notify in the original PR when there is no v\d* labels or backport-skip labels.
* notify when backports are not merged but have been reviewed, this happens once a week.
**NOTE**:
This is a complementary service, so contributors can decide to opt-in and use the labels to automate the backports or use any other kind of process to do the backports
This is a SaaS that works out of the box with public repositories. So it can simplify your backport.
It's stateless, so it does not track if a particular PR should have been backported, it backports any PR only if:
1) It was merged and tagged with the labels -> https://docs.mergify.io/actions/backport/ …
=> [mergify] in order to automate the backport and notifications

docs/en/ingest-management/commands.asciidoc
Closes https://github.com/elastic/beats/issues/27245
This is a loose backport of https://github.com/elastic/observability-docs/pull/1091 without most of the changes/improvements from the later PR. My main goal is to get the syntax right for 7.14 with minimal changes since we don't currently release doc bug fixes for 7.14 and earlier.
=> Indicate --url is required when enrolling a fleet server with a cert

docs/en/ingest-management/fleet/fleet-settings.asciidoc
This is a re-do of #1355 since I'm unsure/nervous about rebasing in this repo. :-)
Customers using the AWS, GCP, or Azure private link services need to make sure that the Fleet Server hosts field is populated. This warning has been added to the Cloud docs via this PR, but it's worth calling out in the Fleet Server docs as well.
Rel: elastic/sdh-cloud#30443
Rel: elastic/cloud#93165
=> Update fleet-settings.asciidoc with caveat for Fleet URL, take2

docs/en/observability/whats-new.asciidoc
Points to the new location for the docs about using integrations in an air-gapped environ.
=> Fix link to air gapped registry docs

.github/CODEOWNERS
Since we branched 8.0 from main, the CODEOWNERS file that requires obs-docs team reviews in main now also exists in the 8.0 branch. Here’s a look at my email inbox since this started happening: :incoming_envelope: :chart_with_upwards_trend:.
I don't think we need to require code owner reviews in 8.0. What do you think?
=> [8.0] Delete CODEOWNERS

docs/en/integrations/air-gapped.asciidoc, docs/en/integrations/index.asciidoc
Closes #1305
The build will break until all links are cleaned up.
Links that need to be cleaned up:
18:58:20 INFO:build_docs:   - en/integrations-developer/current/air-gapped.html
PR: https://github.com/elastic/observability-docs/pull/1362
18:58:20 INFO:build_docs:   - en/integrations-developer/current/air-gapped.html
PR: https://github.com/elastic/observability-docs/pull/1362
18:58:20 INFO:build_docs:   - en/integrations-developer/current/air-gapped.html
18:58:20 INFO:build_docs:   - en/integrations-developer/current/air-gapped.html
18:58:20 INFO:build_docs:   - en/integrations-developer/master/air-gapped.html
PR: https://github.com/elastic/kibana/pull/121236
=> Remove air-gapped topic from the integrations dev guide

docs/en/ingest-management/overview.asciidoc
=> Fix links on "Fleet and Elastic Agent overview" page with wrong syntax

docs/en/ingest-management/overview.asciidoc
- FIx links on "Fleet and Elastic Agent overview" (#1402)
=> [8.0] FIx links on "Fleet and Elastic Agent overview" (#1402)

docs/en/ingest-management/overview.asciidoc
Backports the following commits to 7.17:
- FIx links on "Fleet and Elastic Agent overview" (#1402)
=> [7.17] FIx links on "Fleet and Elastic Agent overview" (#1402)

docs/en/ingest-management/overview.asciidoc
Backports the following commits to main:
- FIx links on "Fleet and Elastic Agent overview" (#1402)
=> [main] FIx links on "Fleet and Elastic Agent overview" (#1402)

docs/en/observability/ingest-logs.asciidoc, docs/en/observability/ingest-metrics.asciidoc
This change is related to https://github.com/elastic/beats/pull/29569.
I need to use {modulename} to set the yml name in `start.asciidoc`, so it has to be a single value rather than a list. Plus it matches the example, so it works here, too.
=> Fix example command to show one module instead of multiple

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Update the instructions to fix Fleet Server agent stuck in updating to use Fleet API instead of devtools command to avoid ghost package policy.
Using the devtool command result in ghost package policy in the agent policy UI.
=> [Fleet] Fix troubleshouting agent stuck in update to avoid ghost package policy

docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Updated changed command in docs, see https://github.com/elastic/kibana/issues/122290
Initial issue: https://github.com/elastic/kibana/pull/121180
=> Added missing --fleet-server-insecure-http to docs

docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Some vars are replaced by service_token, some are removed, some have the behaviour changed
=> Update deprecation tags for basic auth env vars for agent

docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
* Update deprecation tags for basic auth env vars for agent
* Fix syntax
* Add FLEET_SETUP env var with deprecation warning
=> [backport] Update deprecation tags for basic auth env vars for agent (#1434)

docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
Adding a placeholder for 8.0.0 release notes. 
Most of this is boilerplate text that we can change. My main concern is that we replace what's there currently (old release notes from 7.x) with something to indicate the release notes are coming later on.
If the process for generating release notes is not ready by 8.0, we'll need to populate this file with info.
TODO:
=> Add placeholder for Fleet/Agent 8.0.0 relnotes

docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Closes https://github.com/elastic/observability-docs/issues/1191.
@jen-huang Can you please confirm that "selective agent binary updates" is the feature that covers bulk selection?  I'm not very keen on the phrasing used there, but I want to make sure we mention it in the docs.
Note that we don't document specific subscription levels in the docs because we point to the subscriptions page as a single source of truth about licensing requirements. (We've been told over and over again not to mention specific license levels in the docs.)
=> Clarify licensing requirements for bulk agent upgrades

docs/en/ingest-management/beats-agent-comparison.asciidoc
Osquery Manager is no longer beta. It was released for general availability in 7.16.
Please let me know if I selected the backport labels correctly; this update applies to all doc versions from 7.16 and forward. Thanks!
=> Update beats-agent-comparison.asciidoc for osquery

docs/en/observability/ci-cd-observability.asciidoc
[CI/CD Observability] Bump Maven Extension version.
Can we backport on the 7.16 branch please?
=> [CI/CD Observability] Bump Maven Extension version

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Adds release notes for 7.17.0. Looking at the changelog, I don't see any notable changes for 7.17.0, as expected.
=> Add release notes for Elastic Agent 7.17.0

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc, docs/en/ingest-management/tab-widgets/install-layout.asciidoc, docs/en/ingest-management/troubleshooting/faq.asciidoc
We changed the log rotation method and the log file names for all Beats and Elastic Agent in 8.0. Agent starts to log into the file `elastic-agent-{date}.ndjson`. On rotation it starts a new file `elastic-agent-{date}-1.ndjon`. I updated the footnotes and other places I had found. Let me know if I missed anything.
=> Adjust names of log files in Elastic Agent documentation

docs/en/integrations/build-integration.asciidoc, docs/en/integrations/elastic-package.asciidoc, docs/en/integrations/index.asciidoc, docs/en/integrations/integration-example.asciidoc, docs/en/integrations/publish-integration.asciidoc, docs/en/integrations/system-testing.asciidoc, docs/en/observability/monitor-java-app.asciidoc
Some repositories are now main based.
I don't know where these changes should be backported, so please feel free to add the right label :)
=> Use main for integrations/ecs-logging/elastic-package

docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
Until https://github.com/elastic/kibana/issues/123150 is complete we need to make this more clear that this is experimental. The page it links to indicates this too, but this needs to be more clear in the main docs.
=> Add experimental banner to Fleet API docs page

docs/en/ingest-management/commands.asciidoc, docs/en/ingest-management/elastic-agent/debug-standalone-elastic-agent.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
=> Add docs about debugging standalone Elastic Agents

docs/en/ingest-management/fleet/air-gapped.asciidoc
We've gotten several questions about how to upgrade Agents via the UI when in an air-gapped environment. This is not yet supported until https://github.com/elastic/kibana/issues/100413 is implemented.
This adds a note to our air-gapped documentation about this limitation and how to workaround it.
Open questions:
=> Add docs on upgrading Agent in air-gapped environment

docs/en/observability/observability-ui.asciidoc
This is not the correct capitalization for the acronym which stands for Distributed Denial of Service.
=> Correct improper capitalization

docs/en/observability/observability-ui.asciidoc
Backports the following commits to 7.17:
- Correct improper capitalization (#1600)
=> [7.17] Correct improper capitalization (#1600)

docs/en/observability/observability-ui.asciidoc
- Correct improper capitalization (#1600)
=> [7.16] Correct improper capitalization (#1600)

docs/en/observability/observability-ui.asciidoc
Backports the following commits to 8.1:
- Correct improper capitalization (#1600)
=> [8.1] Correct improper capitalization (#1600)

docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Closes #1613
I don't see anything new in the change log for 7.17, but let me know if I've overlooked something. Thanks!
=> Add 7.17.1 release notes for Elastic Agent and Fleet

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Add a section on agent min requirements to the installation docs
- Closes #1543
=> Add elastic-agent min requirements

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This adds a workaround / troubleshooting step for the issue in discussed in https://github.com/elastic/kibana/issues/124785.
=> Add troubleshooting steps for failed 8.x upgrades

docs/en/ingest-management/commands.asciidoc, docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc, docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Add documentation for enabling the metrics buffer in the agent: https://github.com/elastic/beats/pull/30471 
- Relates https://github.com/elastic/beats/issues/29776
=> Add metrics buffer documentation

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
Please make sure I haven't missed anything for Elastic Agent. We should sort out a better way of handling the changelog now that Elastic Agent will be in a new repo.
=> Add 8.1.0 Fleet and Elastic Agent release notes

docs/en/observability/ingest-traces.asciidoc
Fleet-managed EA's are required for the APM integration. This PR adds a note to the APM integration quickstart.
Closes https://github.com/elastic/apm-server/issues/6921.
=> docs: Mention Fleet-managed requirement in APM quick start

docs/en/observability/synthetics-quickstart-fleet.asciidoc
Fixes the duplicate "Elastic Elastic Agent agent in a container" link
=> Remove duplicate text from Synthetics quickstart

docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
Closes #1649 
I put these release notes under "known issues" because they don't seem like breaking changes. Let me know what you think.
=> Add info about default policies to Fleet release notes

docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
Extend elastic-agent documentation:
- about running agent on managed kubenetes environments, that not all metrics and logs can be available
- add note, that container resources might be needed to adjust
Signed-off-by: Tetiana Kravchenko <tetiana.kravchenko@elastic.co>
=> Elastic-agent: add documentation about running agent on managed kubenetes environmets, need to adjust resource configuration

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
document how to use the reset API available since 8.0 to reset the cloud policy instead of having the user manipulating system indices
=> [Fleet] Use reset API instead of system indices for reseting cloud policy

docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
=> Add Fleet and Elastic Agent 8.1.1 relnotes

docs/en/ingest-management/data-streams.asciidoc, docs/en/integrations/package-spec.asciidoc, docs/en/observability/configure-logs-sources.asciidoc, docs/en/observability/ingest-logs.asciidoc, docs/en/observability/ingest-metrics.asciidoc
Related https://github.com/elastic/observability-docs/issues/1096
Related https://github.com/elastic/kibana/issues/100844
The term "index patterns" (or `index-pattern` in URLs) appears on 10 pages. It looks like it's primarily in various **Settings** pages and after looking at the Kibana UI, it looks like some of these references have been changed to "data views" but others still use index patterns.
I'm trying to figure out if all references to "index patterns" should be changed or only where the UI text has changed. Here's what I found: 
**Logs** > **Settings** > **Data view** (new option)
Pages that mention this part of the UI: 
- Also line 42?
**Metrics** > **Settings** > **Indices** > **Metric indices**
Pages that mention this part of the UI: 
**Uptime** > **Settings** > **Indices** > …
=> Replace "index patterns" with `data-source` shared attribute

docs/en/observability/monitor-java-app.asciidoc
Fixes:
```
08:40:20 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/7.10/monitor-java-app.html contains broken links to:
08:40:20 INFO:build_docs:   - en/apm/agent/java/current/config-logging.html#config-enable-log-correlation
08:40:20 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/7.11/monitor-java-app.html contains broken links to:
08:40:20 INFO:build_docs:   - en/apm/agent/java/current/config-logging.html#config-enable-log-correlation
08:40:20 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/7.12/monitor-java-app.html contains broken links to:
08:40:20 INFO:build_docs:   - en/apm/agent/java/current/config-logging.html#config-enable-log-correlation
08:40:20 INFO:build_docs: …
```
=> docs: log correlation is auto enabled

docs/en/observability/monitor-java-app.asciidoc
This will backport the following commits from `main` to `7.15`:
=> [7.15] docs: log correlation is auto enabled (#1709)

docs/en/observability/monitor-java-app.asciidoc
This will backport the following commits from `main` to `7.13`:
=> [7.13] docs: log correlation is auto enabled (#1709)

docs/en/observability/monitor-java-app.asciidoc
This will backport the following commits from `main` to `7.12`:
=> [7.12] docs: log correlation is auto enabled (#1709)

docs/en/observability/monitor-java-app.asciidoc
This will backport the following commits from `main` to `7.14`:
=> [7.14] docs: log correlation is auto enabled (#1709)

docs/en/observability/monitor-java-app.asciidoc
This will backport the following commits from `main` to `7.11`:
=> [7.11] docs: log correlation is auto enabled (#1709)

docs/en/observability/monitor-java-app.asciidoc
This will backport the following commits from `main` to `7.10`:
=> [7.10] docs: log correlation is auto enabled (#1709)

docs/en/observability/monitor-uptime-synthetics.asciidoc, docs/en/observability/synthetics-create-test.asciidoc
Fixes #1611 
Incorporates content from the [Why and how to replace end-to-end tests with synthetic monitors](https://www.elastic.co/blog/why-and-how-replace-end-to-end-tests-synthetic-monitors) blog into synthetic monitoring docs and proposes some restructuring including:
* Consistently use `context` (instead of `client`). 
* Explain what's happening in steps in more detail.
* Start with "why" so readers can quickly decide if this topic is relevant to them.
* Be explicit about the problem we're solving (i.e. end-to-end tests alone can't prove your software works).
* Outline how the solution works at a high level.
* Then get into the details of the two types of synthetic monitoring (real browser and lightweight) and link out for more details.
* Start with "if these conditions are true..." …
=> Incorporate blog content into synthetic monitoring docs

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
In https://github.com/elastic/beats/pull/30087 we added support for loading input configuration from external configuration files in Elastic Agent when running in standalone mode. The behaviour is similar to Filebeat's support. However, at the moment path to the inputs folder is not configurable.
This PR adds a few sections to the standalone agent configuration page.
=> Document loading inputs configuration from external files in standalone mode

docs/en/ingest-management/beats-agent-comparison.asciidoc
Changes the input to green.
Questions:
=> Make http json input green in support table

docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc, docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
@jlind23 I've added some details that might be adjusted. Let me know! 
Previews:
https://observability-docs_1780.docs-preview.app.elstc.co/guide/en/fleet/8.1/release-notes-8.1.2.html
https://observability-docs_1780.docs-preview.app.elstc.co/guide/en/fleet/8.1/release-notes-8.1.1.html (same)
https://observability-docs_1780.docs-preview.app.elstc.co/guide/en/fleet/8.1/fleet-troubleshooting.html#agent-upgrade-fails-with-failed-binary-verification
=> Add known problem with agent binary verification

docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Related to https://github.com/elastic/kibana/pull/129371
We should not recommend user to run Fleet server in http and should use the default self generated certificate instead.
=> [Fleet] Do not recommand user to run Fleet server in http

docs/en/observability/ingest-logs.asciidoc
Ref https://github.com/elastic/observability-docs/pull/1725#discussion_r848863081
From @bmorelli25 on the inclusion of `:release-state: released` and `:!release-state:` in [`/docs/en/observability/ingest-logs.asciidoc`](https://raw.githubusercontent.com/elastic/observability-docs/main/docs/en/observability/ingest-logs.asciidoc):
>That's a mistake and should be removed. That was added to overwrite the `:release-state:` attribute in the docs repo (https://github.com/elastic/docs/blob/master/shared/versions/stack/master.asciidoc#L21) which is always set to `unreleased` in `main` and `master`. Adding the overwrite at the beginning of the file (and then unsetting it at the end) allows the page contents to render for review purposes.
Not sure about backporting on a PR like this one!
=> Remove locally defined `release-state` variable

docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Just need folks to verify that there are no release-notes worthy changes in Fleet and Elastic Agent for 7.17.3.
=> Add Elastic Agent and Fleet 7.17.3 release notes

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/security/certificates.asciidoc, docs/en/ingest-management/security/generate-certificates.asciidoc, docs/en/ingest-management/security/logstash-certificates.asciidoc, docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Adds a placeholder topic about configuring TLS for Logstash. Preview link: https://observability-docs_1795.docs-preview.app.elstc.co/guide/en/fleet/master/secure-logstash-connections.html 
I've also reworked the TOC by adding a section about securing connections and made the section titles more consistent:
We can revisit the structure when I work on the docs.
=> Add placeholder topic about generating certs for Logstash

docs/en/observability/redirects.asciidoc
In #1725 we combined the Docker and Agent/Fleet quickstart guides. I created a redirect for the Docker guide, but missed a redirect for Agent/Fleet (because there were no links from other docs to this page). This PR adds a temporary redirect for the Agent/Fleet quickstart guide. I will open another issue to request a permanent redirect now. 
@paulb-elastic @dominiqueclarke @jeffvestal
=> Add temporary redirect for Synthetics Agent/Fleet quickstart guide

docs/en/integrations/package-spec.asciidoc
This PR fixes the issue reported by [CI build](https://elasticsearch-ci.elastic.co/job/elastic+docs+master+build/21554/) after we merged this [PR](https://github.com/elastic/package-spec/pull/323).
In general, we didn't expect that there is code accessing those files directly. We should rather migrate this doc to the package-spec repo to prevent such failures in the future.
The reason why we introduced this change to package-spec is that we're working on [supporting another type](https://docs.google.com/document/d/1vzBh2frnlxEBBcab8-ist8pu_PDZUjOHdsV-QuUn_WA/edit#).
=> Spec fallback: use integration type by default

docs/en/observability/redirects.asciidoc
In #1725 we combined the intro to Synthetics/browser monitors and lightweight monitors into one intro page. This PR adds a temporary redirect for the former individual Synthetics/browser monitors intro page. I will open another issue to request a permanent redirect now. 
cc @paulb-elastic
=> Add temporary redirect for former intro to Synthetics/browser monitors page

docs/en/observability/ingest-traces.asciidoc
Updates the APM quick start to include the new steps for adding Elastic Agents.
Related to https://github.com/elastic/observability-docs/pull/1824.
@bmorelli25 I haven't touched the steps in the widget yet, but I think they need to be updated because they still mention the default policy. Do you want to make the updates or should I?
We might want to merge this small PR first just to get the glaring changes addressed.
=> Update APM quick start with new Add agent steps

docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc
Signed-off-by: Tetiana Kravchenko <tetiana.kravchenko@elastic.co>
Extend documentation for kubernetes_leaderelection provide:
- setting to disable the leader election
- add `kube_client_options` https://github.com/elastic/elastic-agent/blob/main/internal/pkg/composable/providers/kubernetesleaderelection/config.go#L12
Closes https://github.com/elastic/elastic-agent/issues/385
=> extend doc for providers.kubernetes_leaderelection

docs/en/observability/analyze-metrics.asciidoc, docs/en/observability/monitor-logs.asciidoc
Fixes https://github.com/elastic/observability-docs/issues/1323
Changes module references to integrations in [Log monitoring](https://www.elastic.co/guide/en/observability/current/monitor-logs.html) and [Metrics monitoring](https://www.elastic.co/guide/en/observability/current/analyze-metrics.html).
=> Change module references to integrations in Logs and Metrics intros

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc, docs/en/ingest-management/tab-widgets/install-layout.asciidoc, docs/en/ingest-management/troubleshooting/faq.asciidoc
Closes #954.
Minor patch to resolve old issue that is already [fixed in 8.0](https://github.com/elastic/observability-docs/pull/1499)+
Trying to keep the changes minimal because the old log file naming strategy is a bit eccentric and is changed in 8.0+ anyhow.
=> Fix log file names in 7.17 docs

.github/workflows/add-issue-to-project.yml, .github/workflows/add-pr-to-project.yml
This PR adds two GitHub Actions to the observability-docs repo:
**Event**: When an issue is opened
**Job 1**: Add the issue to the obs-docs-project board
**Job 2**: Move the issue to the _Inbox_ column
**Event**: When a PR review is requested
**If**: If `elastic/obs-docs` is a reviewer
**Job 1**:  Add the issue to the obs-docs-project board
**Job 2**: Move the issue to the _In review_ column
**Job 3**: Add the `needs-writer-review` label
I tested the mutations with Graph<i>i</i>QL and they work. I'm not sure how to test this PR though.
~The `APM_TECH_USER_TOKEN` must be added as a repository secret for this action to work.~ It sounds like that token is APM-specific. We're working on getting a different token added to this repository.
=> Add GitHub Actions

docs/en/ingest-management/tab-widgets/add-fleet-server/widget.asciidoc, docs/en/observability/tab-widgets/add-apm-integration/widget.asciidoc
Closes #1877 
The IDs used to drive the synchronization need to be the same, or the tabs will not be synced.
=> Fix synchronization in widget tabs

docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc
Adds 8.2.3 release notes. Do not merge yet.
Waiting for build candidate to check for Elastic Agent items.
=> Add Fleet and Elastic Agent 8.2.3 release notes

docs/en/ingest-management/tab-widgets/prereq.asciidoc
We're retiring the Stack GS in favor of the new onboarding content introduced in 8.2.
=> [DOCS] Remove refs to Stack GS

docs/en/shared/spin-up-the-stack/content.asciidoc
We've retired the Stack Getting Started Guide in favor of the new onboarding content in 8.2.
=> [DOCS] Update ES & Kibana install links

docs/en/ingest-management/beats-agent-comparison.asciidoc
As of Beats 8.0, data streams are the default output to Elasticsearch.  Line 245 needs change to {y} and the phrasing in Line 248 should reflect that all three options can take advantage of data streams, easier ILM, and the data stream naming scheme.
Reference: https://github.com/elastic/beats/pull/28450 linked in https://www.elastic.co/guide/en/beats/libbeat/8.0/release-notes-8.0.0.html
=> update Beats capability for DStreams

docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
Adds entries and placeholder for bug fixes in 8.3.1.
Also cleans up 8.3.0 release notes so that we are more consistent with verb tense and style used in the Kibana release notes.
TODO:
=> Add Fleet and Elastic Agent 8.3.1 release notes

docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
Let's be explicit in the release notes when there are no bug fixes in patch releases.
=> Indicate when there are no bug fixes for Agent or Fleet

docs/en/observability/ci-cd-observability.asciidoc
https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/DASHBOARDS.md#elastic is the new URL
while https://github.com/jenkinsci/opentelemetry-plugin/tree/master/docs/dashboards/elastic is not anymore available
=> Fix breaking link to the CICD Observability dashboards

docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
With [8.2](https://github.com/elastic/obs-dc-team/issues/601), Fleet-managed Agent gained the ability to output data to Logstash. That rendered the warning on this page unnecessary.
=> Remove standalone-only warning for Logstash output

docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
Replace `{{var}}` with `${var}`.
=> Fix wrong config in elastic-agent-debug-input-configs.asciidoc

docs/en/observability/synthetics-run-test.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-content.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-widget.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-monitor-content.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-monitor-widget.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-test-content.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/manage-monitors-update-test-widget.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/run-test-configure-content.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/run-test-configure-widget.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-content.asciidoc, docs/en/observability/tab-widgets/uptime-monitoring/run-test-suite-widget.asciidoc
As discussed with @andrewvc @lucasfcosta, we should default to Heartbeat as the primary method of creating and managing monitors while other methods are still in beta.
=> [synthetics] Move Heartbeat tab to first position in all synthetics docs

docs/en/ingest-management/troubleshooting/faq.asciidoc
Manually backports relevant bits of https://github.com/elastic/observability-docs/pull/1983 to 8.2 branch.
=> [8.2] Remove old FAQ description about secure communications

docs/en/ingest-management/troubleshooting/faq.asciidoc
Manually backports relevant bits of https://github.com/elastic/observability-docs/pull/1983 to 8.1 branch.
=> [8.1] Remove old FAQ description about secure communications

docs/en/ingest-management/troubleshooting/faq.asciidoc
Manually backports relevant bits of https://github.com/elastic/observability-docs/pull/1983 to 8.0 branch.
=> [8.0] Remove old FAQ description about secure communications

docs/en/ingest-management/troubleshooting/faq.asciidoc
Manually backports relevant bits of #1983 to 7.17 branch.
=> [7.17] Remove old FAQ description about secure communications

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/integrations/package-signatures.asciidoc
Placeholder for the new page requested in #2005
=> Add placeholder for topic about integration package signatures

docs/en/ingest-management/agent-policies.asciidoc, docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc, docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc, docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc, docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc, docs/en/ingest-management/fleet/elastic-agent-logging.asciidoc, docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc, docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc, docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc, docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc, docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc, docs/en/ingest-management/security/certificates.asciidoc, docs/en/ingest-management/security/enrollment-tokens.asciidoc, docs/en/ingest-management/security/logstash-certificates.asciidoc, docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc, docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Closes https://github.com/elastic/observability-docs/issues/1619
* Removes items that are done, we don't plan to do, or are already tracked in GitHub.
I've created these issues to track remaining work:
* https://github.com/elastic/observability-docs/issues/2032
* https://github.com/elastic/observability-docs/issues/2033
=> Clean up old TODO items in source files for Fleet/Agent docs

docs/en/ingest-management/fleet/air-gapped.asciidoc, docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This PR adds a subsection to include information when the Elastic stack and EPR are deployed in air-gapped environments and custom CA are used.
Closes https://github.com/elastic/package-registry/issues/808
Closes https://github.com/elastic/observability-docs/issues/1629
Regarding backporting this PR to other branches, what labels should I add in this PR ? backport-7.17, backport-8.3 ? any other ?
=> Add subsection for custom CA in air-gapped environments

docs/en/shared/install-apm-agents-kube/nodejs.asciidoc, docs/en/shared/install-apm-agents/content.asciidoc
The "advanced-setup.html" ref was misnamed, and the
"configuring-the-agent.html" ref is a sublink of the "advanced-setup.html"
page, so doesn't add value.
@bmorelli25 Does this look reasonable? I'm new to this repo.
=> Update APM Node.js setup steps and links.

docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
Closes #2054. Preview is [here](https://observability-docs_2055.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.3.3.html).
I am using the command shown in https://github.com/elastic/elastic-agent/issues/803. I have not tested this command myself. I need reviewers to confirm that the details here are correct and that the command is valid.
=> Add known issue and workaround for enroll command failing on deb/rpm

docs/en/observability/ingest-logs.asciidoc
Starting with 8.0.0, Filebeat modules no longer have a default fileset (system), and users must explicitly enable the filesets they want to use. The Filebeat Reference was updated, but the observability guide was not.
File this under 101 reasons why we should avoid duplicating identical content.
Incidentally I usually argue against making random sentences bold, but this has apparently been a sticking point for a lot of users, so I've decided it's Ok as long as we don't put it in red all caps. :-P Too soon?
Related issue: https://github.com/elastic/observability-docs/issues/1043
=> Clarify that at least one fileset must be enabled in a filebeat module

docs/en/ingest-management/fleet/fleet-settings.asciidoc, docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Closes #1986 
Also adds minor cleanup of asciidoc bold formatting.
=> Explain why the edit hosts button in Fleet may be grayed out

docs/en/ingest-management/integrations/package-signatures.asciidoc
Closes #2051 
Any links that point directly to this topic will work, but the topic won't appear in the TOC. I'm not sure if google indexes hidden topics, but if it does, users will see that something is coming. I don't think that's a bad thing.
=> Hide topic about package signatures

docs/en/observability/categorize-logs.asciidoc, docs/en/observability/inspect-log-anomalies.asciidoc
Relates to https://github.com/elastic/stack-docs/pull/2204
This PR adds machine learning requirements to [Inspect log anomalies](https://www.elastic.co/guide/en/observability/master/inspect-log-anomalies.html) and [Categorize log entries](https://www.elastic.co/guide/en/observability/master/categorize-logs.html) in the Observability Guide. It also moves a link from the top to the bottom of the latter page, since the target provides more advanced options than are initially required. 
The requirements text is partially borrowed from the UI text here:
=> [DOCS] Add notes about security for ML anomaly detection job

docs/en/observability/create-observability-connectors.asciidoc
Relates to https://github.com/elastic/kibana/issues/124687
This PR updates https://www.elastic.co/guide/en/observability/master/cases-external-connectors.html with information about the new Webhook Case Management connector. It cannot link to more information until https://github.com/elastic/kibana/pull/137726 is merged.
This PR also removes the table that contains configuration details for each connector. Instead, it links to the appropriate pages in the Kibana Guide where those details are maintained.
=> [DOCS] Add Webhook Case Management connector to Cases

docs/en/ingest-management/agent-policies.asciidoc, docs/en/ingest-management/beats-agent-comparison.asciidoc, docs/en/ingest-management/fleet/fleet-settings.asciidoc, docs/en/ingest-management/security/logstash-certificates.asciidoc
Closes #2001 
Reviewers: I wasn't sure about per-policy outputs. I can add the Beta admonition back in if it's still beta in 8.4.
=> Remove beta admonition for Logstash output in Fleet

docs/en/observability/index.asciidoc, docs/en/observability/manage-synthetics-retention.asciidoc, docs/en/observability/synthetics-manage-retention.asciidoc
Fixes https://github.com/elastic/synthetics/issues/286
This patch adds a new docs page for the commonly requested task of altering retention periods for the space-hungry
`synthetics-browser.network` and `synthetics-browser.screenshot` indices.
While we will have better defaults in https://github.com/elastic/uptime/issues/462 we need this doc before that change makes it into 8.4. Additionally, we will always need some level of documentation here, though we can simplify it a little after that.
I've tried to keep the docs screenshot free for kibana index management, since I don't think we'll be able to track visual changes there well.
It _is_ a complex process, but I've tried my best to describe it.
Once the better defaults are merged it should be as simple as clicking on the default …
=> [Synthetics] Document changing retention on a per-data-stream basis

docs/en/observability/monitor-uptime-synthetics.asciidoc, docs/en/observability/synthetics-command-reference.asciidoc, docs/en/observability/synthetics-configuration.asciidoc, docs/en/observability/synthetics-create-test.asciidoc, docs/en/observability/synthetics-journeys.asciidoc, docs/en/observability/synthetics-manage-monitors.asciidoc, docs/en/observability/synthetics-params-secrets.asciidoc, docs/en/observability/synthetics-run-test.asciidoc, docs/en/observability/synthetics-visualize.asciidoc
In our last synthetics/docs sync, @paulb-elastic pointed out that we weren't consistent with beta notes across synthetics docs. This PR adds a beta note (rather than inline text with a popup) at the beginning of each page related to Elastic Synthetics and/or browser monitors.
=> [synthetics] Standardize beta notes across synthetics docs

docs/en/ingest-management/data-streams.asciidoc
Preview the new tutorial by clicking **[here](https://observability-docs_2094.docs-preview.app.elstc.co/guide/en/fleet/master/data-streams-pipeline-tutorial.html)**.
* Closes https://github.com/elastic/observability-docs/issues/1936
* Closes https://github.com/elastic/observability-docs/issues/748
* Related to https://github.com/elastic/observability-docs/issues/1226
=> Custom ingest pipelines

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
Adds release notes for Elastic Agent and Fleet in 8.4 based on changelog entries.
@jen-huang 
* I've edited the list of Fleet items taken from https://github.com/elastic/kibana/pull/137621. Some entries were confusing and  inconsistent. Please review, and I will make sure the changes get back into the Kibana docs.
* "Enables package signature verification feature"  shows up in the 8.4 release notes, but I thought we were going to wait and not expose this feature in 8.4 GA.
@jlind23 
Several of the Elastic Agent bug fixes were in 8.3.3, but since they showed up in the changelog and commit history for 8.4.0, I've included them. They are the first 6 in the list. Let me know if I should keep or remove them.
We need to get this merged tomorrow. 
TODO after merging:
=> Add Fleet and Elastic Agent 8.4 release notes

docs/en/observability/synthetics-manage-retention.asciidoc
Trying to fix:
```
09:42:44 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/8.3/synthetics-manage-retention.html contains broken links to:
09:42:44 INFO:build_docs:   - en/fleet/current/data-streams.html#data-streams-ilm-tutorial
09:42:44 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/8.4/synthetics-manage-retention.html contains broken links to:
09:42:44 INFO:build_docs:   - en/fleet/current/data-streams.html#data-streams-ilm-tutorial
09:42:44 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/current/synthetics-manage-retention.html contains broken links to:
09:42:44 INFO:build_docs:   - en/fleet/current/data-streams.html#data-streams-ilm-tutorial
09:42:44 INFO:build_docs: …
```
=> Fix broken link to Data Stream ILM tutorial

docs/en/observability/synthetics-manage-retention.asciidoc
Trying to fix:
```
09:42:44 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/8.3/synthetics-manage-retention.html contains broken links to:
09:42:44 INFO:build_docs:   - en/fleet/current/data-streams.html#data-streams-ilm-tutorial
09:42:44 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/8.4/synthetics-manage-retention.html contains broken links to:
09:42:44 INFO:build_docs:   - en/fleet/current/data-streams.html#data-streams-ilm-tutorial
09:42:44 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/current/synthetics-manage-retention.html contains broken links to:
09:42:44 INFO:build_docs:   - en/fleet/current/data-streams.html#data-streams-ilm-tutorial
09:42:44 INFO:build_docs: …
```
=> Fix broken link to data streams ILM tutorial

docs/en/integrations/index.asciidoc
We are changing how to handle multiple versions in the package spec repository.
To be merged after https://github.com/elastic/package-spec/pull/384.
=> Update link to future package spec

docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
Adds skeleton file for 8.4.1.
@elastic/obs-docs Someone will need to finalize this PR for the 8.4.1 release date because I'll be on PTO.
@debadair for awareness.
Before merging:
If you aren't sure what to do, just look at a previous version. :-)
=> Add Fleet and Elastic Agent 8.4.1 release notes

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
An internal user indicated that the `{version}` variable isn't rendering on the page for [running an Elastic Agent in a container](https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html). This change adds the `subs="attributes"` parameter to several code examples, which allows the `{version}` variable to be substituted with the current version.
=> [DOCS] Add "attributes" to display {version}

docs/en/observability/synthetics-quickstart.asciidoc
Manual backport of #2144. Since file structure has changed, automatic backport was not possible.
=> [Synthetics] Add cap requirement to docker section

docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
This is my first time doing the Fleet and Elastic Agent release notes so these might need some work, but here's what I did:
- I'm not sure if [the changes in this PR](https://github.com/elastic/elastic-agent/pull/1130/files#diff-867eb8a32d99eda9bb244b7b86d7abd0031618bae71d0276fe139fe697c3063dR117) should be included.
**Note:** I'm not sure if we still `credentials-error` note under "Known issues". From what I could tell it looks like it _might_ be addressed in 8.4.2 (see [the Beats release notes](https://github.com/elastic/beats/pull/33122/files#diff-cb0601935fcaac3fea29b215282428b964b8b6e1bd5a6b8c68e84d651633c9e3R13)).
=> Add Fleet and Elastic Agent 8.4.2 release notes

docs/en/ingest-management/release-notes/release-notes-8.4.asciidoc
Adds Elastic Agent release notes based on  https://github.com/elastic/elastic-agent/commits/5f09295a5dce74a20656ed5bc1d654b1fab06060 in BC2.
There are no Fleet release notes in the [Kibana relnotes PR](https://github.com/elastic/kibana/pull/141808), so I'm assuming no release notes for Fleet. Please confirm.
=> Adds Fleet/Agent 8.4.3 release notes

docs/en/ingest-management/fleet/fleet-settings.asciidoc
This came up in a discuss topic: https://discuss.elastic.co/t/endpoint-security-configuration/315486
=> Explain why output settings might be grayed out in Fleet

docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Closes #1492 
This PR doesn't fix the problem with how the term "integration" is overloaded at Elastic, but hopefully it makes the terminology in this task a bit more clear.
I could have used "integration policy" in more places, but I want the steps here to match the UI (which really glosses over the distinction between an integration and integration policy).
=> Clarify terminology around adding an integration

docs/en/observability/synthetics-create-test.asciidoc
Closes https://github.com/elastic/observability-docs/issues/2115
Adds a link to the [`request` parameter example](https://github.com/elastic/synthetics-demo/blob/main/advanced-examples/journeys/api-requests.journey.ts) in the [/synthetics-demo](https://github.com/elastic/synthetics-demo) repo.
=> [synthetics] Link to `request` parameter example

docs/en/observability/index.asciidoc, docs/en/observability/synthetics-command-reference.asciidoc
Closes #2220 
Updates [Synthetics command reference](https://observability-docs_2246.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-command-reference.html) with changes to the Elastic Synthetics CLI:
* Adds a note letting the reader know that there are interactive prompts, why they are there, and when they should expect to see them. (Note: I'm not sure if this is necessary.)
* Adds a `--yes` option and explains how it works for both deleting all monitors and duplicating monitors to a new ID.
Note: The `locations` command was documented in https://github.com/elastic/observability-docs/pull/2116. Let me know if there are any updates to make to the existing language!
I'm very open to suggestions about the language used here!
=> [synthetics] Add information about the `push` command's `--yes` option

docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
We want to highlight this restriction because we are seeing support cases related to users who have overlooked it in the docs.
=> Highlight statement that only one agent can run on a host

docs/en/observability/synthetics-command-reference.asciidoc, docs/en/observability/synthetics-create-test.asciidoc
Closes https://github.com/elastic/observability-docs/issues/2219
Documents how to import and use external NPM packages in journey code and the limitations when pushing a project that uses external packages.
cc @paulb-elastic
=> [synthetics] Document how to import NPM packages and their limitations

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Closes #2227
Link to preview: https://observability-docs_2264.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.5.0.html
Questions for reviewers:
=> Add Fleet/Agent release notes for 8.5

docs/en/ingest-management/tab-widgets/prereq.asciidoc
The setting `xpack.security.enabled` [has been removed since 8.0.0](https://github.com/elastic/kibana/pull/111681) so following these instructions will result in errors from the Kibana side. This file needs to be adjusted for versions of 8.0.0 and upwards
=> adjust for removed kibana security settings

docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
The provider var substitution syntax in the rest of the docs is `${ provider.var }` while the example on this particular page uses double curly brace syntax `{{ provider.var }}`. Proposing this change to avoid confusion.
Apologies if i'm missing some part of the process. Just clicked the "Edit" button on the docs page :)
=> Provider var substitution syntax

docs/en/observability/grant-cases-access.asciidoc, docs/en/observability/manage-cases.asciidoc
Relates to https://github.com/elastic/kibana/issues/140800
This PR updates the Observability Guide to include mention of removing alerts from cases.
=> [DOCS] Remove alerts from cases

docs/en/observability/ingest-logs-metrics-uptime.asciidoc, docs/en/observability/monitor-uptime-synthetics.asciidoc, docs/en/observability/synthetics-run-test.asciidoc
Related https://github.com/elastic/observability-docs/pull/2242
Preview: https://observability-docs_2331.docs-preview.app.elstc.co/guide/en/observability/master/ingest-logs-metrics-uptime.html
We no longer want to encourage new users to get started using the Elastic Synthetics integration to collect uptime/synthetics data. Instead, they can use Heartbeat (lightweight monitors only), the Uptime UI, or project monitors, and deciding which is best for them is a bit complex during this time of transition between _Uptime_ and _Synthetics_.
| Monitor type | Method | Notes |
|--------------|------------------|-----------------------|
| [Lightweight ](https://www.elastic.co/guide/en/observability/current/uptime-set-up.html)  | [Heartbeat](https://www.elastic.co/guide/en/observability/current/uptim …
=> [synthetics] Remove remaining references to the Elastic Synthetics integration

docs/en/ingest-management/fleet/air-gapped.asciidoc, docs/en/ingest-management/integrations/package-signatures.asciidoc
Closes #2005 
Please review. Some of the UI-related details are fuzzy because the feature is not yet turned on in the build.
Remaining questions/issues:
=> Add docs about package verification

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Since these instructions are specific to docker, it makes sense and it is clear to use a full docker run command.
=> Add docker run command

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
This will backport the following commits from `8.4` to `8.5`:
- [Add docker run command (#2291)](https://github.com/elastic/observability-docs/pull/2291)
=> [8.5] Add docker run command (#2291)

docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
This will backport the following commits from `8.4` to `main`:
- [Add docker run command (#2291)](https://github.com/elastic/observability-docs/pull/2291)
=> [main] Add docker run command (#2291)

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
The list was not correctly rendered as this is `asciidoc`, not markdown.
I think we should use `.` for numbered lists.
=> [DOC] Typos

docs/en/ingest-management/fleet/air-gapped.asciidoc
Update references about the package registry distributions available once Package Storage V2 is used.
Snapshot and staging distributions (docker images) will no longer be updated. And, there will be a new distribution named "lite" with a small subset of commonly used packages.
=> Update package registry distributions according to Package Storage V2

docs/en/ingest-management/beats-agent-comparison.asciidoc
in the capabilities table the air gap comment was not updated to reflect the capabilities.
=> Correcting the air gap comment

docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc, docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc, docs/en/ingest-management/elastic-agent/running-on-gke-standard-managed-by-fleet.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-gke-standard-managed-by-fleet.asciidoc, docs/en/ingest-management/index.asciidoc
Add documentation page for GKE environments.
Part of https://github.com/elastic/observability-dev/issues/2408.
=> Add GKE docs section

docs/en/ingest-management/data-streams.asciidoc, docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc, docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc, docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes_leaderelection-provider.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc, docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc, docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc, docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc, docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc, docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
~Removing the `[discrete]` tags allows the build to create the "On this page" links for level 3 topics in the nav, but it makes the content harder to move around. If we move the topic up a level, we'll need to add the discrete tags back in. And if we move a topic down a level, we'll need to remove the discrete tags to make sure "On this page" gets populated.~
~@gtback Is this a bug or expected behavior? I feel like we ran into this problem with other topics and fixed it, so maybe the fix just needs to be applied to level 3 topics?~
Here is an example of a level 3 topic that does not have "On this page" links: https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html
To fix this problem, we have decided to bump the heading levels on affected pages instead of removing the …
=> Fix mini toc in level 3 topics

docs/en/ingest-management/security/logstash-certificates.asciidoc
Update confusing instructions in logstash client certificate generation. 
In Fleet we force mutual TLS when using the logstash output, but the client certificate is used to verify that the agent is part of the Fleet but not to authenticate a specific agent, the client certificate is shared between all the agent using the logstash output so it should not contains IP or DNS.
=> [Fleet] Update logstash client certificate generation

docs/en/observability/monitor-k8s/monitor-k8s.asciidoc
As mentioned in the comment in the [readme](https://github.com/elastic/helm-charts/blob/master/README.md), we are no longer recommending Elastic helm charts, so we shouldn't link to them.
=> Remove link to Elastic helm charts

docs/en/ingest-management/elastic-agent/elastic-agent-encryption.asciidoc, docs/en/ingest-management/index.asciidoc
Based on https://github.com/elastic/elastic-agent/pull/398 and a discussion with @cmacknz .
It's a somewhat common ask from synthetics users.
=> [agent] Add documentation for Agent encryption at rest

docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
This will backport the following commits from `8.5` to `main`:
- [Need to get an emergency release note out for 8.5.1 (#2390)](https://github.com/elastic/observability-docs/pull/2390)
=> [main] Need to get an emergency release note out for 8.5.1 (#2390)

docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Closes https://github.com/elastic/observability-docs/issues/2383
=> Add known issue with offline agents failing to unenroll from Fleet

docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Closes #2373 
Question: Why does the [changelog fragments directory](https://github.com/elastic/elastic-agent/tree/c13f9157c438fc60cfbb822b385ea91bc91193cc/changelog/fragments) contain old entries that we documented in 8.5.1? Is this expected? Am I looking at the correct release hash?
=> Add Fleet/Agent 8.5.2 release notes

docs/en/observability/synthetics-configuration.asciidoc
The schedule interval in the monitor configuration is specified in minutes, so we have to fix this doc to show the proper information.
=> Fix docs on synthetics monitor interval

docs/en/observability/ingest-traces.asciidoc, docs/en/observability/tab-widgets/add-apm-integration/content.asciidoc
This PR updates the APM quick start to:
* Include a tip explaining the port Kubernetes and Docker users should use when setting up the APM integration.
* Links to the common problems section from the bottom of the quick start guide for users who aren't seeing any data flowing into the APM app.
Unfortunately, I think this is the best we can do until https://github.com/elastic/apm-server/issues/2107 lands and provides a nice home for this information. The `0.0.0.0` tip has existed in our [common problems](https://www.elastic.co/guide/en/apm/guide/current/common-problems.html#no-data-indexed) guide since 2018, but clearly, people aren't looking for it there. Hopefully this helps.
* Closes https://github.com/elastic/apm-server/issues/9214
=> docs: add `0.0.0.0` tip

docs/en/ingest-management/fleet/fleet-settings.asciidoc
Users who jump into this page need to scroll up to understand the context. Let's make it easier by making the context clear.
=> Provide context for procedures under Fleet Settings

docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Closes #2422
These release notes are based on the commits from BC1:
Elastic Agent: 
0a6c4f05e33ed054ce54409a59f6d7da52e07cd2
Fleet Server:
34f8a9419c90a409fabd60a7345d44a78f518ac2
Next week, someone in @elastic/obs-docs will need to:
=> Add Fleet/Agent 8.5.3 release notes

docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Closes #2447.
These release notes are based on BC1. For 7.17 and earlier, the Elastic Agent source code lives in the `beats` repo, so you need to look at those commits. The contents of this PR (created on 12/02) are from this commit hash: a2289487438f57f724e1d836f3738cadd62fd477
Next week, someone in https://github.com/orgs/elastic/teams/obs-docs will need to:
=> Add Fleet/Agent 7.17.8 release notes

docs/en/observability/application-logs.asciidoc, docs/en/observability/index.asciidoc, docs/en/observability/tab-widgets/filebeat-logs/content.asciidoc, docs/en/observability/tab-widgets/filebeat-logs/widget.asciidoc
cc @SylvainJuge 
[**Link to preview**](https://observability-docs_2452.docs-preview.app.elstc.co/guide/en/observability/master/application-logs.html)
- Replaces https://github.com/elastic/apm-server/pull/9751
- Related https://github.com/elastic/apm-agent-java/pull/2916
- Closes https://github.com/elastic/observability-docs/issues/1295
- Related https://github.com/elastic/observability-docs/issues/2362
- https://github.com/elastic/apm/blob/main/specs/agents/log-sending.md
- https://www.elastic.co/guide/en/apm/guide/8.5/log-correlation.html
- https://www.elastic.co/guide/en/apm/agent/java/current/log-correlation.html
- https://www.elastic.co/guide/en/apm/agent/dotnet/current/log-correlation.html
- https://www.elastic.co/guide/en/apm/agent/python/current/log-correlation.html
- …
=> Application logging docs

docs/en/observability/grant-cases-access.asciidoc
Relates to https://github.com/elastic/kibana/issues/141059, https://github.com/elastic/kibana/issues/141061
This PR updates the documentation for the [case requirements](https://www.elastic.co/guide/en/observability/master/grant-cases-access.html) to include mention of the server.publicBaseUrl setting.
=> [DOCS] Add server.publicBaseUrl to case setup

docs/en/ingest-management/commands.asciidoc
Prepare v2 docs update: only includes changes visible by our users.
Allow our users to know what has changed.
Relates https://github.com/elastic/elastic-agent/issues/1687
=> V2 Docs Update

docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Closes #2449
Link to preview: https://observability-docs_2450.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.6.0.html
Reviewers:
Notes for finalizing this PR:
* The dev team has developed a tool to make it easier to maintain changelogs and generate release notes, but it only works for Elastic Agent.
* Assuming we want to provide a single place for users to view Elastic Agent, Fleet, and Fleet Server relnotes, we still need to assemble the content manually.
* I've provided some boilerplate text to make this easier. You may need to modify the boilerplate text and/or the agent changelog entries to get them to work. I feel we can change the style in 8.6, if we want.
The source content for the release notes will come from the following places:
Here are some related PRs and …
=> Add Fleet/Agent 8.6.0 release notes

docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Changing the dir structure is not really a new feature, but also not a breaking change in this instance, so I am moving that item to appear under enhancements.
@pierrehilbert I think that takes care of work left over from https://github.com/elastic/observability-docs/pull/2450, but let me know if there's anything else you want me to change. Thanks!
=> Move relnotes item from features to enhancements

README.md, docs/en/observability/index.asciidoc, docs/en/observability/manage-cases.asciidoc
Relates to https://github.com/elastic/kibana/issues/140743, https://github.com/elastic/kibana/issues/142307
This PR adds a section to https://www.elastic.co/guide/en/observability/master/manage-cases.html that describes how to set up email notifications for cases. Since the instructions are the same, the content is re-used via a [tagged region](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/#tagging-regions).
NOTE: This PR must be merged after https://github.com/elastic/kibana/pull/147713 and https://github.com/elastic/docs/pull/2592
=> [DOCS] Notify assignees when assigned to a case

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
This configuration is no longer supported in version 8+, request to remove and correct the documentation.
https://discuss.elastic.co/t/heartbeat-failed-to-activate/322415
=> remove conf `xpack.security.enabled: true`

docs/en/observability/ingest-logs-metrics-uptime.asciidoc
Numbering restarts because the linter comment adds an extra line. This PR fixes the problem.
=> Fix numbering problem caused by linter comment

docs/en/observability/tab-widgets/filebeat-logs/content.asciidoc
- fix indent in filebeat config
- avoid .json suffix for plaintext log file
=> Fix app log ingest doc

docs/en/ingest-management/beats-agent-comparison.asciidoc
Addressing https://github.com/elastic/observability-docs/issues/2458
@dedemorton I couldn't find a global variable for APM server (like {apm-server} ), so just called it out.
=> Excluding APM server from the output section of compatibility page

docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Add https://github.com/elastic/elastic-agent/issues/2086 as a known issue in the release notes.
Also removes an entry about fixing duplicated events on upgrade that was not actually fixed in 8.6.
=> Add new known issue to 8.6 agent release notes

docs/en/ingest-management/overview.asciidoc
This topic was written before we had external documentation for integrations. Let's link to the integrations documentation to avoid sending users down the rabbit hole of accidentally installing Beats.
=> Update link to integrations in the Fleet/Agent overview

docs/en/ingest-management/tab-widgets/run.asciidoc
This pre-emptively fixes broken links that will occur when the docs shared `ingest-guide` attribute is repurposed.
```
15:24:17 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/fleet/7.9/ingest-management-getting-started.html contains broken links to:
15:24:17 INFO:build_docs:   - en/ingest/7.9/elastic-agent-installation.html
15:24:17 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/fleet/7.9/run-elastic-agent.html contains broken links to:
15:24:17 INFO:build_docs:   - en/ingest/7.9/elastic-agent-installation.html
```
=> Replace outdated ingest-guide attribute

docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Closes #2537
Adds release notes compiled manually from fleet-server changelog, Fleet section in Kibana release notes, and elastic-agent fragments.
=> Add Fleet/Agent 8.6.1 relnotes

docs/en/observability/application-logs.asciidoc, docs/en/observability/tab-widgets/filebeat-logs/content.asciidoc
This PR is a follow-up to https://github.com/elastic/observability-docs/pull/2452. Its main purpose is to update the Filebeat configuration with additional details and updated configuration options.
=> docs: Finish Application logging docs

docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Closes #2554
Do we want to carry over the breaking change "Fleet Server now rejects certificates signed with SHA-1" that we included in 7.17.7 and 7.17.8?
=> Add Fleet and Elastic Agent 7.17.9 release notes

docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc, docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc, docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Update  kubernetes provider documentation to clearly state the correct usage of kubernetes labels in autodiscover conditions and 8.6 release notes with a breaking change.
This is due to changes done in https://github.com/elastic/elastic-agent/pull/1398 effective in 8.6 release onwards.
Release notes have been updated, because even if this is considered a bug fix, there may be clients that have already set some templates in standalone agent or conditions in packages (the few that support it).
If in those conditions they make use of dedoted labels then when upgrading to agent 8.6,  the data sets affected won't collect logs/metrics as the conditions won't match.
They need to manually update their configuration.
Updates of this PR can be found in …
=> Update kubernetes provider documentation and 8.6 release notes

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/8.8-request.yaml, .github/workflows/add-pr-to-project.yml, .mergify.yml
=> Update mergify, issue template, and codeowners

docs/en/observability/synthetics-private-location.asciidoc
The docker run command is missing the backslashes which leads to syntax errors when copy/pasting the command
=> Include backslash in docker run command

docs/en/observability/synthetics-private-location.asciidoc
This will backport the following commits from `8.6` to `main`:
- [Including backslash in docker run command (#2586)](https://github.com/elastic/observability-docs/pull/2586)
=> [main] Including backslash in docker run command (#2586)

docs/en/observability/synthetics-private-location.asciidoc
Users often ask us for IP ranges used by the synthetics service, as for example [here](https://elasticstack.slack.com/archives/CNRTHRCLD/p1675327330988699), to allow access into private networks for monitoring purposes. The docs here explain / document that.
=> Add docs for monitoring private networks via synthetics service

docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Closes #2643 
Contains the manually created relnotes for 8.6.2.
We need to revisit this process for 8.7, which IMO is a better time to change for format. We might want to consider pointing to the Kibana release notes instead of building a consolidated file that includes relnotes for Fleet, Fleet Server, and Agent.
cc'ing @karenzone 
Preview is here: https://observability-docs_2644.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.6.2.html
TODOs:
=> Add Fleet and Elastic Agent 8.6.2 release notes

docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
The current Elastic Serverless Forwarder mentions that the `ElasticServerlessForwarderKMSKeys` option is:
> a comma delimited list of AWS KMS Keys ARNs to be used for decrypting AWS SSM Secrets, Kinesis Data Streams, or SQS queue (if any)
This is correct, but we must also mention that users should add the KMS keys to encrypt the objects in the S3 bucket (if any).
A couple of minor updates:
- Mention user should add KMS keys used in S3 buckets.
- Add a note with an example.
- https://github.com/elastic/sdh-beats/issues/3071
=> ESF: add details on using encrypted S3 buckets

docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
- Add two known issues for 8.6.1 that are high severity and fixed in 8.6.2.
- Copy the release notes for a fix in Beats that applies to agent in 8.6.2 since it fixes a critical issue and needs to be visible.
- Add a known issue in 8.6.2 for the agent failing to install on MacOS Ventura. This technically applies to every version of the agent.
=> Ensure all known issues are documented for Agent in 8.6.x

docs/en/observability/monitor-azure-agent.asciidoc
Fix a broken link to Azure Activity Logs in the "Monitor Azure with Elastic Agent" tutorial
=> Fix broken link to Azure Activity Logs

docs/en/ingest-management/fleet/api-generated/README.md, docs/en/ingest-management/fleet/api-generated/rules/fleet-apis-passthru.asciidoc
This adds a _perl_ step into the API generation README instructions and also updates the API docs output, so that the section headers have spaces between words. It's not perfect: We still have one header reading as `Enrollment APIKeys` rather than `Enrollment API Keys`, but it's better than before. The original `ElasticPackageManagerAPM` now renders as `Elastic Package Manager EPM`.
Ideally we don't want to introduce somewhat arcane code into our docs processes, but this is just a one line command, and these generated docs are essentially a stop-gap fix while we wait for a better implementation.
Note: I used perl so that the command is the same across operating systems.
**Original:**
**Fixed up:**
=> Add post-processing step to tidy up API docs section headers

docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc, docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc, docs/en/ingest-management/fleet/set-inactivity-timeout.asciidoc, docs/en/ingest-management/index.asciidoc
Closes issues [2352](https://github.com/elastic/observability-docs/issues/2352) and [2543](https://github.com/elastic/observability-docs/issues/2543).
I've added the **Set inactivity timeout** section and updated information on statuses and links regarding setting the unenrollment timeout. 
@nimarezainia In the [suggested documentation](https://docs.google.com/document/d/1sWXzljzvuIccpreHou-xD7STo6nSpy6vWhDVzdVI6jw/edit), there was some additional information on agent statuses and lifecycle. Some of that information is [here](https://www.elastic.co/guide/en/fleet/8.6/monitor-elastic-agent.html#view-agent-status), which I have linked to from the **Set inactivity timeout** doc. Maybe we can update the information there to explain that better. Let me know if this is ok.
I am also wondering …
=> Add inactivity timeout documentation

docs/en/observability/ingest-traces.asciidoc
This will backport the following commits from `8.6` to `main`:
- [Fixing content bug in step 3 notice box (#2757)](https://github.com/elastic/observability-docs/pull/2757)
=> [main] Fixing content bug in step 3 notice box (#2757)

docs/en/ingest-management/tab-widgets/install-layout.asciidoc
This adds a footnote to the Beats shippers section of the [Installation layout](https://www.elastic.co/guide/en/fleet/8.1/installation-layout.html#installation-layout) page, since those log file names now support date/timestamps.
Closes: [#30792](https://github.com/elastic/beats/issues/30792)
=> Add footnote for log file beats shipper install layout

docs/en/observability/application-logs.asciidoc, docs/en/observability/tab-widgets/filebeat-logs/content.asciidoc, docs/en/shared/install-apm-agents/content.asciidoc
- logs general correlation fields + filebeat setup
- invite users to set service version + env
=> Enhance service correlation doc

docs/en/observability/monitor-uptime-synthetics.asciidoc, docs/en/observability/monitor-uptime.asciidoc, docs/en/observability/shared/synthetics-note.asciidoc, docs/en/observability/synthetic-monitoring.asciidoc, docs/en/observability/synthetics-command-reference.asciidoc, docs/en/observability/synthetics-configuration.asciidoc, docs/en/observability/synthetics-create-test.asciidoc, docs/en/observability/synthetics-params-secrets.asciidoc, docs/en/observability/synthetics-quickstart-fleet.asciidoc, docs/en/observability/synthetics-quickstart.asciidoc, docs/en/observability/synthetics-visualize.asciidoc
Synthetics has changed significantly in 8x and is not a good experience in 7x (and is, and always will be beta in 7x).  This PR makes the suggestion not to use browser type monitors in 7x.
It's the same copy on various pages.
=> [Synthetics] Suggest not to use browser types in 7x

docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Updates the Fleet [troubleshooting page](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html) wrt the macOS file sharing issue.
**Preview:**
=> Update troubleshooting with file sharing tip for macOS

docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc, docs/en/ingest-management/index.asciidoc, docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
This adds the 8.7.0 Release Notes. See [Preview page](https://observability-docs_2788.docs-preview.app.elstc.co/guide/en/fleet/master/release-notes-8.7.0.html).   ← This preview site seems not to be updating.  `¯\_(ツ)_/¯`
**Notes**:
- Elastic Agent notes are ready. ~Elastic Agent notes are still TBD. @cmacknz will ensure that the [changelog tool](https://github.com/elastic/elastic-agent-changelog-tool) is run before release day and I'll take it from there.~
- For Fleet Server, I used this [fragments list](https://github.com/elastic/fleet-server/tree/4854b153a3d77e898993193ad6af1b52176850d5/changelog/fragments) which contained just one fragment. If anything more should be added, please let me know.
- The `kubernetes-conditions-autodiscover.asciidoc` file is included because it contained a …
=> Add Fleet/Agent 8.7.0 release notes

docs/en/observability/synthetics-create-test.asciidoc
Closes https://github.com/elastic/observability-docs/issues/2603
After some discussion in #2603, I've approached this more like _documenting the relationship between Synthetics and Playwright_ rather than just documenting that not all Playwright functionality is available in Synthetics. Here's what I've done so far:
* Added `expect` to the existing [Syntax overview](https://observability-docs_2792.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-create-test.html#synthetics-syntax) section to highlight that this functionality is built into Synthetics. 
* Added a new [Playwright syntax](https://observability-docs_2792.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-create-test.html#synthetics-playwright) section to the existing [Add …
=> [synthetics] Document that not all Playwright functionality is available in Synthetics

docs/en/ingest-management/release-notes/release-notes-8.7.asciidoc
Add an Elastic Agent known issue.
Adds a known issue to the 8.7.0 release notes for this Agent upgrade issue: https://github.com/elastic/elastic-agent/issues/2433
=> Create a known issue for Elastic Agent

docs/en/ingest-management/commands.asciidoc
Following the merge of https://github.com/elastic/elastic-agent/pull/2380 the list of files generated by the `elastic-agent diagnostics ` command needs to be updated, This PR provides that update
=> Update elastic-agent diagnostic command files list

docs/en/ingest-management/beats-agent-comparison.asciidoc
Elastic Agent managed by fleet doesn't allow tweaking queue settings.
This should be backported to any version in the past.
Feel free to reword/edit.
=> [DOCS] Update queue statement in Elastic Agent

docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc, docs/en/ingest-management/index.asciidoc
This updates the Standalone Elastic Agent section with a `Feature flag` page, including the new FQDN setting. 
Note: Hold off on merging until https://github.com/elastic/elastic-agent/pull/2218 is merged.
See: [preview](https://observability-docs_2817.docs-preview.app.elstc.co/guide/en/fleet/master/elastic-agent-standalone-feature-flags.html)
Rel: [#1641](https://github.com/elastic/ingest-dev/issues/1641)
=> Add Feature Flag page with new FQDN setting

docs/en/ingest-management/fleet/fleet-settings.asciidoc
This adds docs for the new Host Format selector option added via https://github.com/elastic/kibana/pull/154563
Closes: https://github.com/elastic/ingest-dev/issues/1747
**Preview**
=> Add docs for Fleet UI FQDN setting

docs/en/observability/monitor-infra/explore-metrics.asciidoc, docs/en/observability/monitor-infra/monitor-servers.asciidoc
This PR closes [Issue 1935](https://github.com/elastic/observability-docs/issues/1935).
This PR updates replaces old metric fields (system.network.in.bytes, system.network.out.bytes) with new one (host.network.ingress.bytes, host.network.egress.bytes) in the docs.
=> Update metric fields

docs/en/observability/index.asciidoc, docs/en/observability/profiling-advanced-configuration.asciidoc, docs/en/observability/profiling-probabilistic-profiling.asciidoc
We have implemented probabilistic profiling in https://github.com/elastic/prodfiler/issues/3162. This PR adds the end user facing documentation so it can be configured if required.
Fixes https://github.com/elastic/prodfiler/issues/3163
=> Universal Profiling: add probabilistic profiling

docs/en/observability/synthetics-recorder.asciidoc
Set some expectations for how the Recorder should be considered when using.  Whilst we have https://github.com/elastic/observability-docs/issues/2818 to add a more detailed _best practice_ guide, this is to add some expectations directly in the recorder docs.
=> Set expectations for the Synthetics Recorder

docs/en/observability/synthetics-get-started-project.asciidoc, docs/en/observability/synthetics-get-started-ui.asciidoc
We’re clarifying expectation in the UI with [kibana#155307](https://github.com/elastic/kibana/issues/155307) but this adds some details to the docs too
=> Clarify when monitors run after creation

README.md
Remove unnecessary `=` in build command.
=> Remove unnecessary `=` in build command

docs/en/observability/grant-cases-access.asciidoc
Relates to https://github.com/elastic/kibana/issues/146864
This PR updates https://www.elastic.co/guide/en/observability/master/grant-cases-access.html to include the necessary privileges for adding alerts to cases.
=> [DOCS] List privileges to add alerts to cases

docs/en/observability/synthetics-lightweight.asciidoc
The current example shows schedules that won't be used, but will be rounded up, which is misleading
=> Update examples to valid schedules

docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc
I missed [this comment](https://github.com/elastic/observability-docs/pull/2729#pullrequestreview-1371903211) earlier. 🙈  Thanks @vigneshshanmugam!
=> [synthetics] Typo fix: `module` -> `monitor`

docs/en/observability/profiling-get-started.asciidoc
This PR adds the end user facing documentation for installing the Universal Profiling Agent integration.
Fixes elastic/prodfiler#3176
=> Universal Profiling: add integration installation

docs/en/observability/synthetics-reference/lightweight-config/common.asciidoc, docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc
Closes #2843 
Documents additional lightweight monitor config options. Based on https://github.com/elastic/integrations/pull/5798, it looks like the following options were added:
* Common options:
* [`mode`](https://observability-docs_2923.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-lightweight.html#monitor-mode)
* [`ipv4`](https://observability-docs_2923.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-lightweight.html#monitor-ipv4)
* [`ipv6`](https://observability-docs_2923.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-lightweight.html#monitor-ipv6)
* HTTP-only options:
* [`proxy_headers`](https://observability-docs_2923.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-lightweight.html#monitor-http-proxy_head …
=> [synthetics] Document additional lightweight monitor config options

docs/en/observability/index.asciidoc, docs/en/observability/synthetics-support-matrix.asciidoc
Synthetics is made up of a number of product components and is run differently to some of the other Elastic solutions, and so does not really fit in with the main [Support matrix](https://www.elastic.co/support/matrix).
This PR is intended to create a support matrix page specifically for Synthetics (similar to something similar that [APM Agent](https://www.elastic.co/guide/en/apm/guide/current/agent-server-compatibility.html) has).
=> [Synthetics] Document the support matrix for the various Synthetics components

docs/en/observability/synthetics-configuration.asciidoc
Closes #2868 
Adds a note to the [Configure Synthetics projects](https://observability-docs_2952.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-configuration.html) page about timeout types, default values, and how to change the default value in your config file. Looks like this ([preview link](https://observability-docs_2952.docs-preview.app.elstc.co/guide/en/observability/master/synthetics-configuration.html#synthetics-configuration-playwright-options)):
@vigneshshanmugam I'm not sure if this is what you had in mind -- I'm very open to suggestions on both the language used and where this information should go in the existing docs!
=> [synthetics] Add a note about timeout types and defaults

docs/en/observability/index.asciidoc, docs/en/observability/monitor-java-app.asciidoc, docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc, docs/en/shared/copied-from-beats/install-filebeat/install-widget-filebeat.asciidoc, docs/en/shared/copied-from-beats/install-heartbeat/install-widget-heartbeat.asciidoc, docs/en/shared/copied-from-beats/install-metricbeat/install-widget-metricbeat.asciidoc, docs/en/shared/copied-from-beats/shared/install.asciidoc, docs/en/shared/copied-from-beats/shared/start.asciidoc, docs/en/shared/copied-from-beats/start-filebeat/start-filebeat.asciidoc, docs/en/shared/copied-from-beats/start-filebeat/start-widget-filebeat.asciidoc, docs/en/shared/copied-from-beats/start-heartbeat/start-widget-heartbeat.asciidoc, docs/en/shared/copied-from-beats/start-metricbeat/start-widget-metricbeat.asciidoc, docs/en/shared/install-configure-filebeat.asciidoc, docs/en/shared/install-configure-metricbeat.asciidoc
This PR copies over Beats `install` and `start` widgets so we can remove the Observability Guide dependency on the `elastic/beats` repository.
* Closes https://github.com/elastic/observability-docs/issues/2969.
=> Remove Beats dependency

docs/en/observability/index.asciidoc, docs/en/observability/logs-checklist.asciidoc, docs/en/observability/logs-overview.asciidoc
This PR closes [issue 90](https://github.com/elastic/obs-docs-projects/issues/90). 
This PR aims to create a one-page cheat sheet that includes the logging user flow, a brief outline of how the pieces work together, and links to existing documentation.
=> Add the logs resource guide

docs/en/observability/redirects.asciidoc
Relates to https://github.com/elastic/kibana/issues/160045
This PR creates a hidden page for use in the Kibana doc link service. The URL can subsequently be turned into a full page.
=> [DOCS] Create stub page for threshold rule

docs/en/aws-firehose/aws-firehose-setup.asciidoc
This PR is to address confusion around `es_datastream_name` parameter for Firehose.
closes https://github.com/elastic/obs-infraobs-team/issues/1070
=> Fix firehose documentation on es_datastream_name parameter

docs/en/observability/synthetics-private-location.asciidoc, docs/en/observability/synthetics-support-matrix.asciidoc
Fixes https://github.com/elastic/beats/issues/34725
Confirms that a direct connection to Elasticsearch is needed for Synthetics
=> Clarify a direct connection to ES is required

docs/en/aws-firehose/aws-firehose-setup.asciidoc
This PR is to add missing log types into firehose documentation: Cloudtrail and CloudWatch.
=> Add missing log types into firehose documentation

docs/en/observability/synthetics-role-write.asciidoc
As per https://github.com/elastic/observability-docs/pull/3008/files#r1246607585, an additional `read` permission is needed for setting up the Agent Policy for a Private Location
=> Additional permission for creating Agent Policy

docs/en/observability/profiling-tag-data-query.asciidoc, docs/en/observability/universal-profiling.asciidoc
With this commit we update the names of two fields that users can use in Kibana filters:
* `service.name` has changed to `profiling.project.id`
* `host.ipstring` has changed to `host.ip`
=> [Profiling] Update name of filter fields

docs/en/observability/application-logs.asciidoc
go, dotnet, nodejs and ruby agents links are not covered for now as we are waiting for an agent release to update docs.
closes https://github.com/elastic/apm/issues/800
=> Update links for APM agents logs

docs/en/observability/profiling-upgrade-migrate.asciidoc
With this commit we adapt the 8.9 Universal Profiling migration script to add a new field if the respective index exists.
Relates elastic/elasticsearch#97413
=> [Profiling] Add new field to migration script

docs/en/integrations/system-testing.asciidoc
It appears the table in this documentation was using markdown, therfore it was not rendering correctly. I updated to use asciidoc format.
Not sure if these docs are generated or not but this PR will fix the table directly.
=> [Docs] Fix Table (was markdown)

docs/en/observability/synthetics-command-reference.asciidoc
Fixes https://github.com/elastic/observability-docs/issues/3041
Adds a note about the Elastic Synthetics CLI's `--tags` and `--match` flags.
=> [synthetics] Add note about `--tags` and `--match` flags

docs/en/observability/index.asciidoc, docs/en/observability/synthetics-troubleshooting.asciidoc, docs/en/observability/troubleshooting.asciidoc
Closes #2695 
I added a new troubleshooting page nested under Synthetics and added an outline with the content from #2695  and https://github.com/elastic/observability-docs/pull/3073#discussion_r1263882384. 
@paulb-elastic can you identify the best people to help with the content for "Missing / incorrect API key" and "No Agent running with the Private Location Agent Policy"? @vigneshshanmugam can you help me articulate how "Local debugging" works (I'm not sure if that's the right heading for that section)? 
cc @drewpost
=> [synthetics] Add synthetics troubleshooting page

docs/en/observability/synthetics-command-reference.asciidoc
This capability has been added back in via https://github.com/elastic/synthetics/pull/813 so adding back to the docs
=> Added the --no-headless option back in

docs/en/observability/profiling-get-started.asciidoc
I think that we should mention Elastic Agent at the top instead fo standalone, to show that Elastic Agent is the preferred way of running it.
=> Rearrange the profiler docs for UP agent

docs/en/observability/synthetics-support-matrix.asciidoc, docs/en/observability/synthetics-troubleshooting.asciidoc
Added about a direct ES connection being needed on the Support Matrix and troubleshooting pages as it has come up with users of the Service, not just with Private Locations, so need to make this message clearer.
Also added a note about scaling as mentioned in https://github.com/elastic/observability-docs/pull/3081#issuecomment-1644436758
=> Add cases to troubleshooting and support matrix pages

docs/en/observability/index.asciidoc, docs/en/observability/logs-troubleshooting.asciidoc
Create a logs troubleshooting page so we can link to it from the UI.
=> Create a logs troubleshooting page

README.md, docs/en/observability/index.asciidoc, docs/en/observability/manage-cases.asciidoc
This PR removes a tagged region to err on the side of simplicity as we migrate our content.
=> [DOCS] Remove content reuse for cases

docs/en/observability/exploratory-data-visualizations.asciidoc, docs/en/observability/index.asciidoc, docs/en/observability/ingest-traces.asciidoc, docs/en/observability/monitor-aws-beats.asciidoc, docs/en/observability/monitor-azure-beats.asciidoc, docs/en/observability/monitor-gcp.asciidoc, docs/en/observability/monitor-java-app.asciidoc, docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc, docs/en/shared/install-configure-filebeat.asciidoc, docs/en/shared/install-configure-metricbeat.asciidoc
🍷  Pairs with https://github.com/elastic/docs/pull/2735
Removes book-scoped attributes from /observability-docs using several approaches:
* Replacing file path attributes with hard-coded values.
* Moving paths to other web pages to `shared/attributes.asciidoc` in the /docs repo.
* Replacing book-scoped icon attributes with the cross-site attributes.
* Moving common term attributes to shared/attributes.asciidoc in the /docs repo.
* Moving non-Stack version attributes to shared/versions/ in the /docs repo.
Note: I expect the build to fail until https://github.com/elastic/docs/pull/2735 is merged.
=> Remove book-scoped attributes

docs/en/observability/profiling-add-symbols.asciidoc
Take advantage of the DRA process and replace the custom ela.st links with artifacts.elastic.co.
=> Profiling: replace ela.st with artifacts.elastic.co

.mergify.yml
Merge as soon as 8.10 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
=> backport: Add 8.10 branch

docs/en/observability/logs-stream.asciidoc
This PR closes [Issue 3121](https://github.com/elastic/observability-docs/issues/3121) and adds the Extract the `log.level` field to the Stream a log file documentation.
=> Add the Extract the log level field section

docs/en/observability/logs-stream.asciidoc
This PR closes [Issue 3122](https://github.com/elastic/observability-docs/issues/3122).
=> add Extract host IP section to logs stream docs

docs/en/observability/logs-stream.asciidoc
Removed links to sections for extracting specific fields. The OTP navigation takes care of this and the sections are somewhat dependent on the previous sections, so it's probably best to remove them.
=> Remove unnecessary links

docs/en/observability/profiling-get-started.asciidoc
This corrects the documentation for the minimum supported kernel version for profiling. The text further used to incorrectly state that a x86_64 machine is required, but we've also been supporting ARM64 since at least 8.9 (hence the backport). 
Corresponding universal profiling issue: https://github.com/elastic/prodfiler/issues/3833
=> [Profiling] correctly document minimum kernel for ARM64

docs/en/observability/logs-stream.asciidoc
This PR closes [Issue 3125](https://github.com/elastic/observability-docs/issues/3125) and adds a section on using the reroute processor to simplify log data management.
=> Add reroute processor to stream a log page

docs/en/observability/profiling-upgrade.asciidoc
With this commit we make sure users first disable index management so it cannot interfere with the deletion process. Then we instruct them to delete data streams first in order to avoid that the user attempts to delete underlying indices before the data streams are gone.
=> [Profiling] Clarify index cleanup instructions

docs/en/observability/logs-stream.asciidoc
I did a run through of the current logs docs and updated to make sure things were consistent and logical.
=> Update logs docs for consistency and formatting

docs/en/observability/apm.asciidoc, docs/en/observability/monitor-infra/analyze-metrics.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/tail-logs.asciidoc, docs/en/observability/user-experience.asciidoc
Removes the old, outdated videos from our documentation.
Closes https://github.com/elastic/docs-projects/issues/69.
=> docs: remove old videos

docs/en/observability/logs-troubleshooting.asciidoc
This PR closes [Issue 3116](https://github.com/elastic/observability-docs/issues/3116)
I've updated the **Troubleshoot your logs** page to include the information from @yngrdyn 's [word doc](https://docs.google.com/document/d/193N-IH8wG8Ipra0gNpa1-sceB5xefDMZ6qReZIhs7hI/edit). I'm adding this as a draft PR because I think there is still room for more discussion and information on what needs to be added. But I thought this would give us a starting point for discussion.
=> Add onboarding troubleshooting

docs/en/observability/slo-create.asciidoc
This PR closes [Issue 3150](https://github.com/elastic/observability-docs/issues/3150) and [Issue 3182](https://github.com/elastic/observability-docs/issues/3182).
In this PR, I've updated the SLI types to include Custom metrics and Histogram metrics. I have also added the Partition by option.
Preview available [here](https://observability-docs_3208.docs-preview.app.elstc.co/guide/en/observability/master/slo-create.html)
=> Add custom metrics and histogram SLIs and partition by option

docs/en/observability/profiling-get-started.asciidoc, docs/en/observability/profiling-upgrade.asciidoc
We recently discovered a problem in the setup of Universal Profiling for all customers upgrading from 7.x or earlier.
If a customer created their deployment before 8.0, so on any 7.x or earlier ESS version, they had APM server installed without a specific Fleet policy.
The Universal Profiling setup code tries to find that policy, and it was failing for these deployments.
We addressed this bug and fixed it for 8.9.3 and 8.10.0 customers.
=> Profiling: add upgrade notice of known issues for 8.9 versions

docs/en/observability/logs-stream.asciidoc
This PR closes [Issue 3228](https://github.com/elastic/observability-docs/issues/3228).
Flatten the data stream in the agent configuration in the **Stream a log file** docs.
=> Flatten data stream in agent config

docs/en/aws-firehose/aws-firehose-troubleshooting.asciidoc
**Problem:** In https://github.com/elastic/docs/pull/2752, we updated the URL prefix (`welcome-to-elastic`) and name for the "Welcome to Elastic Docs" docs. However, we still have some stray links that use the old `/welcome-to-elastic` URL prefix
**Solution:** Replace an outdated link with one that uses an attribute.
=> Update `/welcome-to-elastic` link in AWS firehose docs

docs/en/observability/profiling-get-started.asciidoc, docs/en/observability/profiling-upgrade.asciidoc
Address the non-documented case of 8.9.0 setup (faulty) trying to upgrade to a more recent version.
=> profiling: add edge case resolution in known issues

docs/en/observability/logs-stream.asciidoc
Deleted an extra comma from the stream a log index template example.
=> Fix the logs stream index template example

docs/en/observability/observability-ai-assistant.asciidoc
Relates to https://github.com/elastic/kibana/issues/166960
This PR must be merged after https://github.com/elastic/kibana/pull/167519, which renames the "Generative AI connector" and its documentation to "OpenAI connector".
=> [DOCS] Rename Generative AI connector to OpenAI

docs/en/observability/synthetics-lightweight.asciidoc
Lightweight Synthetics checks don't support multiple hosts as an array, as per https://github.com/elastic/synthetics/issues/627, but the docs suggest it can be, so updating to clarify it's a single string value.
=> Change hosts to single string non-array

docs/en/observability/create-observability-connectors.asciidoc, docs/en/observability/slo-create.asciidoc
Closes https://github.com/elastic/observability-docs/issues/3290
Updates documentation related to SLO and Cases based on issues found during our docs bug bash last week:
=> Clean up SLO and cases docs

docs/en/observability/synthetics-create-test.asciidoc
Closes #3206
Currently the docs list the supported [Jest `expect` methods](https://www.elastic.co/guide/en/observability/current/synthetics-create-test.html#synthetics-assertions-methods). As of [@elastic/synthetics v1.5.0](https://github.com/elastic/synthetics/releases/tag/v1.5.0), we use Playwright Test `expect` assertions. This replaces the list of supported Jest methods with links to the Playwright assertion docs.
👋  @vigneshshanmugam I'm not sure if I've captured everything correctly.
cc @paulb-elastic
=> [synthetics] Update docs to reflect the changes to `expect` 

docs/en/observability/profiling-upgrade.asciidoc
With this commit we amend the instructions to delete data on profiling upgrade (only required for pre-GA versions) to also include deletion of index templates, component templates and the ILM policy. This ensures a smooth upgrade without any leftovers.
=> Delete templates/ILM on profiling upgrade

.github/ISSUE_TEMPLATE/community-request.yaml, .github/ISSUE_TEMPLATE/elastic-request.yaml
Removes `Team:Docs` label as it just adds noise.
=> Small fix for new templates

docs/en/observability/synthetics-command-reference.asciidoc
+ fix https://github.com/elastic/synthetics/issues/866
+ The project ID option is used as `--id` in the synthetics agent CLI option when pushing the project based monitors.
=> fix: update synthetics agent project id CLI option

docs/en/observability/monitor-infra/inspect-metric-anomalies.asciidoc
The existing docs are confusing because they lead users to believe there should be an Anomaly detection nav item.
=> Clarify path to anomaly detection page

docs/en/observability/synthetics-configuration.asciidoc, docs/en/observability/synthetics-create-test.asciidoc, docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc, docs/en/observability/synthetics-reference/lightweight-config/icmp.asciidoc, docs/en/observability/synthetics-reference/lightweight-config/tcp.asciidoc
Following on from https://github.com/elastic/observability-docs/pull/3263, there are more places where this limitation was not reflected in the documentation.  This is also true for not supporting `ports` in Project Monitors.
The docs have also been updated to clarify that monitors cannot run in headful mode, but always headless, and cannot be overridden with Playwright Options.
=> Add documentation clarification

docs/en/observability/observability-ai-assistant.asciidoc
Connectors aren't currently available for ingesting external data into the AI Assistant knowledge base.
Actual non-whitespace deletion changes located [here](https://github.com/elastic/observability-docs/pull/3378/files#diff-2c019fd3961068e3a5b86f2abe9a7128e4b6bc0b492ddca3fe09bd34084022b8L70-R70).
=> Remove connector info for ingesting external data

docs/en/observability/redirects.asciidoc
Update the custom threshold redirect to send people to the new docs. I believe all references to threshold-alert have been updated, but in case there were any bookmarks, I think this should be updated instead of removed completely.
=> update custom threshold redirect

docs/en/observability/logs-stream.asciidoc
This PR closes Issue [3398](https://github.com/elastic/observability-docs/issues/3398).
The data stream differed between the stream a log and parse logs documentation causes some frustration for users moving through them.
=> [Logs] Update data stream for streaming logs

.mergify.yml
I thought this was automated, but I didn't see a PR open. I think this should allow us to use `backport-8.12` to backport to the `8.12` branch. @elastic/obs-docs does this look correct?
=> [mergify] Add 8.12 to `.mergify.yml`

docs/en/observability/logs-ecs-application.asciidoc, docs/en/observability/logs-plaintext.asciidoc
In https://github.com/elastic/observability-docs/commit/a9ffa532d1f451ab839bfd6270105b97f807fe4e we re-added the Beats book as a dependency (which we removed in https://github.com/elastic/observability-docs/pull/2992). I _think_ we should be able to point to the copied files in the `shared` directory instead of relying on the Beats book.
=> Point to `shared` files instead of Beats book

.github/Makefile, .github/workflows/run-minor-release.yml
Replaces https://github.com/elastic/ingest-dev/pull/2792 <-- accessible only by Elastic employees
```bash
$ CURRENT_RELEASE=8.14.0 PROJECT_OWNER=v1v \
make -C .github prepare-major-minor-release create-branch-major-minor-release create-prs-next-release prepare-next-release
```
produced https://github.com/elastic/observability-docs/pull/3429 and https://github.com/v1v/observability-docs/tree/8.14
=> release: observability-docs automation

README.md, docs/en/apm-server/anonymous-auth.asciidoc, docs/en/apm-server/api-keys.asciidoc, docs/en/apm-server/apm-distributed-tracing.asciidoc, docs/en/apm-server/common-problems.asciidoc, docs/en/apm-server/configure/outputs/elasticsearch.asciidoc, docs/en/apm-server/configure/outputs/logstash.asciidoc, docs/en/apm-server/configure/tls.asciidoc, docs/en/apm-server/getting-started-apm-server.asciidoc, docs/en/apm-server/integrations-index.asciidoc, docs/en/apm-server/jaeger-integration.asciidoc, docs/en/apm-server/manage-storage.asciidoc, docs/en/apm-server/monitor-apm-server.asciidoc, docs/en/apm-server/otel-metrics.asciidoc, docs/en/apm-server/secret-token.asciidoc, docs/en/apm-server/secure-comms.asciidoc, docs/en/apm-server/setting-up-and-running.asciidoc, docs/en/apm-server/shared-directory-layout.asciidoc, docs/en/apm-server/shared-systemd.asciidoc, docs/en/apm-server/ssl-input-settings.asciidoc, docs/en/apm-server/tls-comms.asciidoc, docs/en/apm-server/troubleshoot-apm.asciidoc, docs/en/apm-server/upgrading-to-8.x.asciidoc, docs/en/observability/apm.asciidoc, docs/en/observability/traces-get-started.asciidoc
Related to https://github.com/elastic/obs-docs-projects/issues/216
Adds APM guide pages into Observability guide. After publishing this PR, we will remove content from the APM guide and redirect APM guide pages to the Observability guide equivalent.
=> [apm docs consolidation] Copy APM guide pages into Observability guide

docs/en/apm-server/integrations-index.asciidoc, docs/en/apm-server/known-issues.asciidoc
Adds the known issues page to 8.11.
Preview: https://observability-docs_3505.docs-preview.app.elstc.co/guide/en/apm/guide/8.11/known-issues.html
=> [apm guide] Add known issues to 8.11

docs/en/observability/grant-cases-access.asciidoc
Relates to https://github.com/elastic/kibana/issues/167641
This PR updates https://www.elastic.co/guide/en/observability/current/grant-cases-access.html
=> [Cases] Add new sub feature privilege to prevent access to case settings

docs/en/observability/slo-overview.asciidoc
Brings over https://github.com/elastic/staging-serverless-observability-docs/pull/131.
Related to https://github.com/elastic/observability-docs/pull/3503 and https://github.com/elastic/staging-serverless-observability-docs/pull/210.
=> Sync Stateful SLO docs with Serverless

docs/en/observability/slo-overview.asciidoc
8.12.0 introduces a breaking change to SLOs. This PR explains how users can upgrade (reset) their SLOs to the new format required in 8.12.0+.
Closes https://github.com/elastic/observability-docs/issues/3511.
=> Explain how to upgrade SLOs out of beta

docs/en/observability/apm/otel-direct.asciidoc
Closes https://github.com/elastic/apm-server/issues/11998
=> Modernise OpenTelemetry Collector example config

docs/en/apm-server/redirects.asciidoc
Adds more redirects to subpage headings to fix build errors in https://github.com/elastic/docs/pull/2862.
=> [apm] Add more redirects

docs/en/observability/apm/apm-k8s-attacher.asciidoc, docs/en/observability/apm/features.asciidoc, docs/en/observability/apm/getting-started-apm-server.asciidoc, docs/en/observability/apm/known-issues.asciidoc, docs/en/observability/redirects.asciidoc
Related to https://github.com/elastic/obs-docs-projects/issues/216
A [few edits to the /apm-server repo's /docs directory](https://github.com/elastic/apm-server/commits/main/docs) snuck in between https://github.com/elastic/docs/pull/2873 and https://github.com/elastic/apm-server/pull/12341. This PR copies those changes to the equivalent pages in the Observability guide:
Note: Next I'll open PRs to backport to the APM guide.
cc @carsonip
=> [apm docs consolidation] Copy recent /apm-server docs edits

docs/en/apm-server/getting-started-apm-server.asciidoc, docs/en/apm-server/known-issues.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3536
Note: Does not include changes from https://github.com/elastic/apm-server/pull/12222 because it was not backported to 8.11.
=> [apm docs consolidation] Copy recent /apm-server docs edits (8.11)

docs/en/apm-server/getting-started-apm-server.asciidoc, docs/en/apm-server/known-issues.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3536
Note: Does not include changes from https://github.com/elastic/apm-server/pull/12222 because it was not backported to 8.10.
=> [apm docs consolidation] Copy recent /apm-server docs edits (8.10)

.github/Makefile, .github/workflows/run-minor-release.yml
- Tweak the scripts a bit so they don't use duplicated hardcoded values.
- Assign the reviewers
- Set the branch to be used when creating a PR
- Remove unused variables.
Given the hypothetical FF for `8.17.0` and using my forked repository then:
```bash
CURRENT_RELEASE=8.17.0 \
PROJECT_OWNER=v1v \
PROJECT_REVIEWERS=v1v \
make -C .github create-major-minor-release create-next-release
```
Produced https://github.com/v1v/observability-docs/pull/3 and https://github.com/v1v/observability-docs/tree/8.17
=> automation: update reviewers and refactor

docs/en/observability/redirects.asciidoc
Related to https://github.com/elastic/obs-docs-projects/issues/216
From the APM team:
>With the switch to https://www.elastic.co/guide/en/observability/current/apm.html , when trying to chose a previous version, e.g. 8.11 there are no redirects and the chosen version just fails with an error for every apm subpage; only the apm overview page works and links to the previous docs. Can this be improved?
This is one approach: adding redirects from the Observability guide to the APM guide for v8.11. We'll see how it works in the preview and determine how far back we should do this. 
cc @bmorelli25
=> [apm consolidation] Add temporary redirects back to APM guide (8.11)

docs/en/observability/apm.asciidoc, docs/en/observability/apm/version.asciidoc
These attributes are not used by the APM documentation. Let's clean 'em up.
=> Remove unused APM attributes

docs/en/observability/apm/aws-lambda-extension.asciidoc, docs/en/observability/apm/open-telemetry.asciidoc, docs/en/observability/apm/otel-attrs.asciidoc
Adds fixes for https://github.com/elastic/staging-serverless-observability-docs/issues/181 (not sure why I opened this in serverless staging, but 🤷)
These changes are minor but might help make it easier when we try to keep the two sources in sync.
=> Update stateful Obs docs to fix problems found during serverless testing

.github/workflows/opentelemetry.yml
Send all the GitHub action steps to the APM using OpenTelemetry; this can help with analysing the CI/CD overall behaviour at a large scale.
This particular action runs independently when the other GitHub workflows have finished.
=> github(action): enable CI/CD observability with Opentelemetry

docs/en/observability/apm/known-issues.asciidoc
Part of https://github.com/elastic/apm-server/issues/12498
=> apm: add 8.12.0 known issue about fleet ingest pipeline bug

docs/en/observability/apm/agent-server-compatibility.asciidoc, docs/en/observability/apm/known-issues.asciidoc
Closes https://github.com/elastic/apm-server/issues/12401
@simitt Can you take a look here? I'm not sure if I correctly interpreted the situation described in https://github.com/elastic/apm-server/issues/12401. Also, should I backport to 8.11?
=> [apm] Add docs on a known issue with APM Server + APM Java agent

docs/en/observability/apm/feature-roles.asciidoc
Update docs to reflect the required `allow_restricted_indices: true` for agent configuration role.
Closes https://github.com/elastic/apm-server/issues/12378
=> Add allow_restricted_indices to agentcfg privileges

.github/Makefile
And use CODEOWNERS instead
Otherwise:
```
could not request reviewer: 'elastic/obs-docs' not found
There are no changes
```
=> ci(run-minor): remove reviewer

docs/en/observability/create-alerts.asciidoc
Closes #2382.
~Should we also link to the docs about these connectors? We could in the changed paragraph that's part of this PR, but it might be better to link to the connectors documentation from the topics where we show the connector configuration. WDYT?~ Gonna defer this until later when I make other updates to the alerting docs.
=> Add missing ServiceNow connectors to list in alerting docs

docs/en/observability/index.asciidoc, docs/en/observability/logs-checklist.asciidoc, docs/en/observability/logs-index-template.asciidoc
this PR closes #3393 
Create a log@custom index template guide that also references how to update the `default_field` to `message` after an update has changed the default behavior to `[*]`.
=> Create a logs@custom index template reference

docs/en/observability/slo-create.asciidoc
Closes https://github.com/elastic/observability-docs/issues/3580 for stateful docs.
Also updates "Partition by" to "Group by" to match the 8.12 UI.
A couple of thoughts:
* I think we can improve the formatting on this page, but I didn't have time to wrestle with that during this sprint.
*  The examples would probably be clearer with screen captures, but the topic is already pretty long. If we plan to add a bunch more indicators, we might want to reconsider how this topic is structured (everything on one page) and consider breaking it down into multiple topics.
=> Add docs about timeslice SLI

docs/en/observability/logs-parse.asciidoc
Update the Parse logs docs to replace deprecated component templates with new ones.
Same changes in serverless: [Issue 223](https://github.com/elastic/staging-serverless-observability-docs/pull/223)
=> Update logs component templates in Parse logs docs

docs/en/observability/explore-logs.asciidoc
This PR closes [Issue 3629](https://github.com/elastic/observability-docs/issues/3629) and adds the required privileges for viewing Logs Explorer.
=> Add Kibana privileges for Logs Explorer

docs/en/observability/apm/known-issues.asciidoc
Add known issue for excessive rollover issue on apm integration package upgrade.
bugfix: https://github.com/elastic/apm-server/pull/12219
=> apm: Add known issue for excessive rollover

docs/en/observability/synthetics-create-test.asciidoc
Clarify `page.snapshot(...)` are not stored in Elasticsearch.
Clarify `page.snapshot({ path: '...',` will fail due to permissions.
This should be backported to all versions.
=> [DOCS] screenshot/video limitation

docs/en/observability/infrastructure-threshold-alert.asciidoc, docs/en/observability/metrics-threshold-alert.asciidoc, docs/en/observability/slo-burn-rate-alert.asciidoc
Relates to https://github.com/elastic/kibana/issues/173009
This PR updates the descriptions of the inventory, slo burn rate, and metric threshold rule to include the advanced option related to alert creation delays.
=> [DOCS] Alert creation delay

docs/en/observability/view-observability-alerts.asciidoc
Removes tech preview badge because this feature is now GA.
=> Remove tech preview badge from docs about viewing alerts

docs/en/observability/slo-burn-rate-alert.asciidoc, docs/en/observability/slo-create.asciidoc
Adds changes to stateful for https://github.com/elastic/observability-docs/issues/3600.
TODO after merging:
=> Update docs to indicate that SLO burn rate rule is created automatically

docs/en/observability/observability-ai-assistant.asciidoc
Adds changes to stateful for #3652. Note that we decided not to document "internal" functions.
Also alphabetizes the table of functions. 
Preview link: https://observability-docs_bk_3663.docs-preview.app.elstc.co/guide/en/observability/master/obs-ai-assistant.html
Question: Why don't we alphabetize the list of functions in the UI? I know we sometimes like to put the most commonly used options first, but in my experience that kind of organizational approach falls apart over time.
TODO (after merging):
If I ask the AI Assistant what functions are available, it'll give me a long list, including context and query, but that list does not show up in the UI when I click **Select a function**. _RESOLVED: We will remove the internal functions._
=> Update observability AI assistant docs with latest changes

docs/en/observability/cloud-monitoring/aws/monitor-amazon-ec2.asciidoc
Cherry-picks https://github.com/elastic/observability-docs/pull/3698 to `main`.
=> Fix URL for AWS EC2 (#3698)

.github/workflows/add-issue-to-project.yml, .github/workflows/add-pr-to-project.yml, .github/workflows/add-to-dev-projects.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …
=> security: add permissions block to workflows

docs/en/observability/redirects.asciidoc
Adds redirects from old Obs URL to new Obs URL for all APM pages updated in https://github.com/elastic/observability-docs/pull/3674.
=> Add apm prefixed redirects

docs/en/observability/observability-ai-assistant.asciidoc
Change requested by @grabowskit in slack.
After merging:
@grabowskit Let me know which releases you want this backported to.
=> Clarify AI Assistant docs about model training

docs/en/observability/synthetics-command-reference.asciidoc
+ Updates some of the Synthetics CLI flags that are outdated and brings it in part with the `--help` command. 
+ Adds docs for some of the features that we have recently added as part of https://github.com/elastic/synthetics/issues/910
=> improve synthetics push command flow docs

docs/en/observability/profiling-self-managed.asciidoc
During the first customer trial using the new docs for onprem Profiling beta, we discovered 2 problems:
1. a major flaw in the config files, they cannot be re-used for k8s manifests with the dotted notation
2. the API creation instructions are unclear
Fix both points.
=> profiling: improve self-managed section

docs/en/observability/view-observability-alerts.asciidoc
This PR updates https://www.elastic.co/guide/en/observability/current/view-observability-alerts.html#cases-observability-alerts with details about the maximum number of alerts that can be attached to a case.
https://observability-docs_bk_3738.docs-preview.app.elstc.co/guide/en/observability/master/view-observability-alerts.html#cases-observability-alerts
=> Add limit for number of alerts per case

docs/en/observability/apm/data-streams.asciidoc, docs/en/observability/apm/ingest-pipelines.asciidoc
Closes https://github.com/elastic/apm-server/issues/12375
Feel free to make big changes! Would be helpful to know if it needs better examples / more technical depth etc
=> Add APM data stream rerouting docs

docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc, docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose-troubleshooting.asciidoc
This PR copies the [Troubleshooting](https://www.elastic.co/guide/en/kinesis/current/aws-firehose-troubleshooting.html) section under [Monitor AWS with Amazon Data Firehose](https://www.elastic.co/guide/en/observability/current/monitor-aws-firehose.html) as its original place -- the [Firehose setup guide](https://www.elastic.co/guide/en/kinesis/current/index.html) -- is going to be removed.
Fixes https://github.com/elastic/observability-docs/issues/3748
=> Add the Firehose troubleshooting section to the new AWS monitoring docs

docs/en/observability/cloud-monitoring/aws/monitor-aws-esf.asciidoc
This PR fixes a wrong numbering in [Monitor AWS with Elastic Serverless Forwarder](http://localhost:8000/guide/monitor-aws-esf.html).
=> Fix numbering in AWS monitoring docs

.github/Makefile
For some reason `gh` cannot find it
> could not request reviewer: 'elastic/obs-docs' not found
And the CODEOWNERS honour the reviewers regardless.
Hence no need to use it explicitly in the script.
=> github-action(release automation): reviewers and use codeowners insteads

docs/en/observability/apm/known-issues.asciidoc
Hello! We just noticed that the recently added APM anomaly known issue doesn't mention the fact that this is fixable within the UI. Kevin had added [UI-based instructions](https://github.com/elastic/sdh-kibana/issues/4601#issuecomment-2046102364) earlier in the SDH comments. This seems like it would be a good idea to point out to folks who run into this problem. Can someone on the docs team help craft this messaging based on the instructions linked to in that SDH? 
Also, I've updated one of the cURL requests that was missing a required header.
=> Fixes known-issues: adds missing header, adds UI instructions

docs/en/integrations/build-integration.asciidoc, docs/en/integrations/elastic-package.asciidoc, docs/en/integrations/index.asciidoc, docs/en/integrations/upload-integration.asciidoc
(1) Since 8.7, Fleet supports integration installation through direct upload as a means to support integration developers or users who have created custom integrations that they don't want to commit upstream back to https://github.com/elastic/integrations. This PR adds the relevant instructions.
(2) We are adding support for "agentless" in integrations. These integrations will be deployed in fully managed agents, so the way they are configured will be slightly different. This PR defines what deployment modes are, how to enable agentless in template policies, and how to disable variables if needed.
Shout out to @kpollich and @jsoriano for their fantastic walkthroughs on these topics.
* Closes https://github.com/elastic/ingest-docs/issues/805.
* Closes …
=> Document workflow for uploading custom integrations and enabling agentless support

docs/en/observability/synthetics-private-location.asciidoc
Closes #3833.
Someone who is an SME should make sure this note is accurate and in the right place. Synthetics is not my area of expertise; I'm just trying to help out.
IMO pointing to that GitHub issue may not be the best approach because the details in the issue seem speculative. It would be much better if we could be proscriptive and tell users exactly how to work around the problem. That is beyond of the scope of what was requested in #3833 and would need some effort from folks outside of the docs team. 
TODO (after merging):
=> Add link to workaround about using custom CAs in private locations

docs/en/observability/profiling-get-started.asciidoc, docs/en/observability/profiling-self-managed-ops.asciidoc, docs/en/observability/profiling-upgrade.asciidoc
We introduced a breaking change in the name of the agent chart with https://github.com/elastic/prodfiler/issues/4286.
Update the docs referencing how to proceed in this case.
- upgrade docs amended
- include a note to display 8.15 exception of upgrade
This PR should only be merged in 8.15
=> Profiling: upgrade guide for self-hosted profiling agents

docs/en/observability/apm/known-issues.asciidoc
Since adding this known issue doc, it was decided to ship version 8.13.3, which was subsequently [released on May 2](https://www.elastic.co/blog/elastic-stack-8-13-3-released).
You can see [the files changed in the fixing PR](https://github.com/elastic/kibana/pull/180717/files#diff-03fef972515c7d0a89727756ea3868982850651d7e2861d83797999cd3a40421L72-R74) are reflected in [the v8.13.3 tag](https://github.com/elastic/kibana/blob/v8.13.3/x-pack/plugins/apm/common/rules/schema.ts#L69).
=> Update APM anomaly known issue re: 8.13.3

docs/en/observability/monitor-logs.asciidoc
An empty line is required or the bulleted list does not render as expected:
=> Fix formatting in topic about logs explorer

docs/en/observability/apm/data-model.asciidoc
Aggregations no longer support RUM global labels since https://github.com/elastic/apm-server/pull/10624
=> Document the lack of RUM global labels support in aggregations

docs/en/serverless/ai-assistant/ai-assistant.mdx
Makes invisible changes to a random MDX file to validate that the end-to-end pipeline works.
=> Trigger build for testing purposes

docs/en/apm-server/data-streams.asciidoc
traces-apm.rum is only available since 8.x. Remove it from 7.x docs.
=> Remove non-existent traces-apm.rum data stream from 7.x docs

.github/workflows/co-docs-builder.yml
This PR addresses 2 issues:
1. Ensures that the build will only be run when the 'ci:doc-build' label is added instead of every time a label is added and one of the labels is 'ci:doc-build'
2. Bypasses the label requirement if the user is part of the Elastic org
=> Update Docsmobile action to fix issues

.github/workflows/co-docs-builder.yml
It turns out that for Elastic,  github.event.pull_request.author_association == 'NONE', so this won't work
=> Remove `author_association` check in `co-docs-builder.yml`

docs/en/serverless/projects/billing.mdx, docs/en/serverless/transclusion/synthetics/global-managed-paid-for.mdx
Closes https://github.com/elastic/observability-docs/issues/3635 and updates the pricing link.
(Replaces https://github.com/elastic/staging-serverless-observability-docs/pull/254)
=> Update serverless pricing link

docs/en/apm-server/data-streams.asciidoc
This will backport the following commits from `7.17` to `7.16`:
- [Remove non-existent traces-apm.rum data stream from 7.x docs (#3934)](https://github.com/elastic/observability-docs/pull/3934)
=> [7.16] Remove non-existent traces-apm.rum data stream from 7.x docs (#3934)

docs/en/observability/monitor-nginx-ml.asciidoc, docs/en/observability/monitor-nginx.asciidoc
This PR closes #3809. 
Add a section in the nginx onboarding tutorial that shows users how to use built-in ML jobs to detect anomalies in their access logs.
=> add nginx ML module tutorial

docs/en/observability/profiling-self-managed-ops.asciidoc
Closes https://github.com/elastic/prodfiler/issues/4586.
Added tips to configure collector and symbolizer in k8s environments.
Specifically we're referencing secrets for output added in https://github.com/elastic/prodfiler/pull/4999
=> profiling: add tips for kubernetes self-managed deployment

.github/workflows/co-docs-builder.yml
In preparing for the Docsmobile 2.0 release (and the move to elastic.co/docs) it was discovered that merges on my [fork](https://github.com/elastic/observability-docs-migration-test) to main were [not making it](https://github.com/elastic/observability-docs-migration-test/actions/runs/9392009765) to [wordlake-docs](https://github.com/elastic/wordlake-docs). It is because this `if` statement is too restrictive and only triggers when the initial label is added.
=> Update co-docs-builder.yml to fix wordlake builds

docs/en/serverless/observability-overview.mdx
This is a whitespace-only change to force a build of the serverless docs. A regression was [introduced](https://github.com/elastic/observability-docs/pull/3935) when testing out the new labeling action after the migration of the serverless docs and the new serverless content has not gone live since. Merging this PR will enable the content to go live again, as a [fix](https://github.com/elastic/observability-docs/pull/3969) was recently merged.
=> Update observability-overview.mdx to force a build

docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose.asciidoc
This PR is to fix several things:
1. the destination deployment  must be on ESS AWS regions and govcloud regions
2. Remove Firehose integration is in Beta note
3. Use CloudTrail logs as an example instead of VPCflow logs because you can actually configure VPC flow logs to send to Firehose directly
=> Fix AWS Firehose documentation

docs/en/serverless/what-is-observability-serverless.mdx
This is a non-visible change to indicate that the new build pipeline is successful and live on https://www.elastic.co/docs. Safe to merge this once out of draft
=> Update what-is-observability-serverless.mdx to force a build

docs/en/observability/cloud-monitoring/aws/monitor-amazon-sqs.asciidoc
https://www.elastic.co/guide/en/observability/current/monitor-amazon-sqs.html
remove unuse var marker
=> Remove unneed code marking in monitor-amazon-sqs section

docs/en/integrations/build-integration.asciidoc
As ECS fields no longer need to be specified as part of an integration, this PR removes the ecs.yml section as requested in https://github.com/elastic/observability-docs/issues/3968.
=> Remove the `ecs.yml` section

docs/en/observability/profiling-self-managed-ops.asciidoc
During the development of https://github.com/elastic/prodfiler/pull/4999 we noticed a mismatch in the instructions.
=> profiling on-prem: fix kubernetes secret instructions

docs/en/observability/slo-privileges.asciidoc
Closes #3996.
Clarification is required because some users interpreted the screenshot to mean that `logs-*` was required.
=> Clarify index used in SLO privileges example

docs/en/observability/tutorials.asciidoc
Replacing the nav links to the nginx tutorial.
=> Add nginx tutorial to navigation

docs/en/observability/observability-introduction.asciidoc
Reverts elastic/observability-docs#4031
8.9 is still marked as Beta in the main docs, so I am reverting this backport.
=> Revert "[8.9](backport #4030) Remove BETA mention from UP"

docs/en/observability/profiling-get-started.asciidoc
With 8.14 released, none of the versions listed in the known issue section is a supported version anymore.
=> Profiling: Drop known issues section about no longer supported versions

docs/en/observability/cloud-monitoring/aws/ingest-aws-options.asciidoc, docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose.asciidoc
This PR is to add documentation for the new feature we added for ingesting metrics using Firehose.
=> Add metrics support for firehose into documentation

docs/en/observability/cloud-monitoring/aws/ingest-aws-firehose.asciidoc, docs/en/observability/cloud-monitoring/aws/monitor-amazon-intro.asciidoc, docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudtrail-firehose.asciidoc
This PR changes the name of this file https://github.com/elastic/observability-docs/blob/main/docs/en/observability/cloud-monitoring/aws/monitor-aws-firehose.asciidoc from `monitor-aws-firehose` to `ingest-aws-firehose`.
=> [Monitor AWS with Firehose] Change file name

docs/en/observability/logs-checklist.asciidoc, docs/en/observability/monitor-logs.asciidoc, docs/en/observability/tail-logs.asciidoc
This PR closes #4065.
I've added a note about switching to Logs Explorer that matches the banner in the UI.
I've also removed references to the tail logs/logs stream page in other docs.
=> Add note about Logs Stream

docs/en/observability/manage-cases.asciidoc
This PR fixes a build error related to https://github.com/elastic/observability-docs/pull/4074
In particular, the build error was:
>  INFO:build_docs:
--
  | INFO:build_docs:asciidoctor: WARNING: manage-cases-settings.asciidoc: line 78: id assigned to block already in use: observability-case-templates
  | INFO:build_docs:
=> [DOCS] Remove obsolete section

docs/en/observability/apm/known-issues.asciidoc
Add APM known issues about too many small bulk requests.
Related bugfix: https://github.com/elastic/apm-server/pull/13576
=> APM known issues: Too many small bulk requests

docs/en/observability/apm/otel-direct.asciidoc
In the Python OTel agent Authorization header content must be url encoded.
=> docs/otel-direct: add Python specific requirements

docs/en/observability/apm/otel-direct.asciidoc
Simplify text, remove a `just", fix a typo.
=> docs/otel-direct: refine python specific paragraph

docs/en/serverless/logging/view-and-monitor-logs.mdx
This PR closes [Issue 71583235](https://github.com/orgs/elastic/projects/649/views/43?pane=issue&itemId=71583235).
Adds docs about the quality issues table in the log details flyout.
=> Add docs for Quality Issues table

docs/en/serverless/projects/create-an-observability-project.mdx
Added docs for serverless cloud regions [here](https://github.com/elastic/docs-content/pull/47) - this PR adds an informational link for regions to the obs project creation doc. 
I also removed the region proximity guidance from this [on request](https://github.com/elastic/docs-content/pull/47#issuecomment-2250601601). the linked region page provides some similar guidance, just a little less prescriptive
Won't merge until the core doc is merged
=> Add region doc link

docs/en/observability/observability-ai-assistant.asciidoc
Clarify AI Assistant will spawn ML nodes
To the doc writers:
- please change wording
- backport to all versions back to AI Assistant pages got created
- add an additional paragraph if the use of AI Assistant / Knowledge Base implies ML Nodes will no more be scaled down back to 0
=> [DOCS] Clarify AI Assistant will spawn ML nodes

docs/en/integrations/quick-start.asciidoc
Fix typo on `package`
Update duplicated command. The second command should be `elastic-package format`, as per [documentation](https://github.com/elastic/elastic-package?tab=readme-ov-file#elastic-package-format), instead of `elastic-package lint`
=> Fix typo and duplication

docs/en/observability/observability-ai-assistant.asciidoc
- Add a statement about not supporting Local LLMs
- Add a statement regarding free-tier LLMs are likely not enough to power AI Assistant
=> [DOCS] Private LLMs & free-tier is not likely enough

docs/en/observability/logs-monitor-datasets.asciidoc
Fixes a few broken image links that I noticed while perusing the docs.
I didn't add an image for the degraded document icon because it doesn't exist already in our images or images/icons directory.
=> Fix broken image links in data quality topic

docs/en/observability/profiling-self-managed.asciidoc
In 8.15 we introduced a check on permissions performed by the collector.
This requires a new cluster privilege that is not included in the role.
=> Profiling: update backend API role permissions

docs/en/observability/apm-ui/api.asciidoc
Fixes https://github.com/elastic/observability-docs/issues/3419
Updates the privileges in the [Create agent key](https://www.elastic.co/guide/en/observability/current/apm-create-agent-key.html) section's example role to include access to Kibana. 
cc @joeafari
=> [apm] Update agent key privileges to include access to Kibana

docs/en/observability/monitor-java-app.asciidoc
While I was reviewing DeDe's IA PR, I just noticed in the "On this page" that the heading levels were off in the Java tutorial.
=> Fix heading levels in Java tutorial

docs/en/observability/monitor-java-app.asciidoc
This PR updates a link to unlock https://github.com/elastic/kibana/pull/191129/ that will go live for 8.16
=> Remove anchor from link to Kibana dashboards page

docs/en/observability/apm/configure/env.asciidoc
Document a way to opt-out of complex object parsing in config parsing to avoid errors.
This is a workaround to https://github.com/elastic/apm-server/issues/13893
=> Add docs on how to opt-out of complex object parsing

docs/en/observability/apm/otel-direct.asciidoc
since the presence _and_ order turns out to be important and most of us start with copy/pasting the example.
=> feat(apm/otel): include processors in pipelines example

docs/en/observability/logs-monitor-datasets.asciidoc, docs/en/serverless/logging/monitor-datasets.mdx
This PR closes [Issue 4149](https://github.com/elastic/observability-docs/issues/4149).
The data set details now open in a page instead of a flyout. I've updated the language to match this and updated the name of the "Quality issues" section.
=> Update the data set quality page

docs/en/serverless/infra-monitoring/host-metrics.mdx
This PR adds the missing field calculations to the [serverless docs](https://docs.elastic.co/serverless/observability/host-metrics)
Fixes https://github.com/elastic/observability-docs/issues/3897
Preview link: https://elastic-dot-co-docs-production-8h6qfqwwb-elastic-dev.vercel.app/current/serverless/observability/host-metrics
=> [Host metrics] Add field calculation to serverless docs

docs/en/observability/apm/known-issues.asciidoc
APM-Server switched from Index Lifecycle Management(ILM) to Datastream Lifecycle (DSL) in v8.15.0. This switch was done when we moved from APM integration (which used ILM) to APM-data plugin (which uses DSL) in ES for managing APM datastreams. As a result of the switch, any old datastreams created before the switch would be Unmanaged because the datastream will never be updated with the DSL lifecycle -- this has to be done manually by using the [PUT API](https://www.elastic.co/guide/en/elasticsearch/reference/current/tutorial-manage-existing-data-stream.html).
Related issue: https://github.com/elastic/apm-server/issues/13898
=> [apm/known_issues] Add known issues for ILM to DSL switch

docs/en/observability/apm/open-telemetry.asciidoc
Removes the preview badge from the link to the EDOT Java docs. 🎉 
cc @estolfo
=> [apm] Remove preview badge from EDOT Java

docs/en/observability/apm/known-issues.asciidoc
Closes #4212 
Adds headings to the APM known issues page to make it easier to read. The heading text is longer than we prefer, but I think it's ok for this page only (@elastic/obs-docs let me know if you disagree).
=> [apm] Add headings to APM known issues page

docs/en/observability/apm/known-issues.asciidoc
The formatting for the doc added using https://github.com/elastic/observability-docs/pull/4192 seems to be broken: https://www.elastic.co/guide/en/observability/current/apm-known-issues.html
The PR attempts to fix the formatting.
=> Fix formatting for APM known issues doc

docs/en/integrations/build-integration.asciidoc
The [hide_in_deployment_modes](https://www.elastic.co/guide/en/integrations-developer/current/define-deployment-modes.html#hide_in_deployment_modes) example in the Integrations Developer Guide uses `logfile` input rather than the newer `filestream`.
Closes: https://github.com/elastic/ingest-docs/issues/1286
=> Update 'hide_in_deployment_modes' example to use filestream

docs/en/integrations/developer-workflow-fleet.asciidoc, docs/en/observability/synthetics-private-location.asciidoc, docs/en/serverless/synthetics/synthetics-private-location.mdx
Elastic Agent Docker images are currently available under both a `beats` and `elastic-agent` namespace. For 9.0 only the latter will be available, so this will update the current (8.15) docs.
Rel: https://github.com/elastic/ingest-docs/issues/1314
=> [Observability docs] Change 'beats' namespace to 'elastic-agent'

docs/en/observability/observability-ai-assistant.asciidoc
This PR adds a more explicit description of what `function calling` is and what it does by adding the following text at the end of the section [Chat with the assistant](https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html#obs-ai-chat) and just before [Suggest functions](https://www.elastic.co/guide/en/observability/current/obs-ai-assistant.html#obs-ai-functions).
Fixes https://github.com/elastic/observability-docs/issues/4206
Here is a [doc preview](https://observability-docs_bk_4211.docs-preview.app.elstc.co/guide/en/observability/master/obs-ai-assistant.html).
=> [Observability AI Assistant] Add explicit text about function calling

docs/en/observability/apm/otel-limitations.asciidoc
Per @smith @AlexanderWert this limitation should be removed.
=> [APM] Remove limitation about host metrics in otel docs

docs/en/serverless/infra-monitoring/analyze-hosts.mdx
This PR removes the `<DocCallOut template="beta" />` as Hosts moved to GA for serverless (9th/16th sept).
Here is a [doc preview](https://elastic-dot-co-docs-production-3ufnhcnku-elastic-dev.vercel.app/current/serverless/observability/analyze-hosts).
Fixes https://github.com/elastic/observability-docs/issues/4216.
=> [Hosts documentation] Remove callout for beta

docs/en/serverless/ai-assistant/ai-assistant.mdx
Port https://github.com/elastic/observability-docs/pull/4211 to serverless docs.
Fix https://github.com/elastic/observability-docs/issues/4257.
=> Port #4211 to serverless

docs/en/serverless/apm-agents/apm-agents-opentelemetry-limitations.mdx
=> [apm/otel] Remove limitation about host metrics in OTel docs

docs/en/observability/apm/open-telemetry.asciidoc, docs/en/serverless/apm-agents/apm-agents-opentelemetry.mdx
Add links to the Elastic Distribution of OpenTelemetry PHP in both stateful and serverless docs.
cc @estolfo @elastic/apm-agent-php
=> [apm/otel] Add links to Elastic Distribution of OpenTelemetry PHP

docs/en/observability/quickstarts/monitor-hosts-with-elastic-agent.asciidoc, docs/en/observability/quickstarts/monitor-k8s-logs-metrics.asciidoc
Closes #4205 
Adds ESS as a prerequisite in Observability quickstarts. I borrowed language from other instructional content in the Observability guide.
=> Add ESS to quickstart prereqs

docs/en/serverless/quickstarts/k8s-logs-metrics.mdx, docs/en/serverless/quickstarts/monitor-hosts-with-elastic-agent.mdx
Related to #4205 
Ports https://github.com/elastic/observability-docs/pull/4277 to serverless docs.
=> [serverless] Add preq to quickstarts

docs/en/observability/apm-ui/services.asciidoc
Fixes https://github.com/elastic/observability-docs/issues/4023
Documents which fields are supported to create APM service groups and removes a note from the service groups doc.
cc @chrisdistasio @mielastic
=> [APM] Document which fields are supported to create APM Service Groups

.github/workflows/add-pr-to-project.yml
@bmorelli25 has been reworking the "Status" field in our project. This updates the workflow that auto-assigns a "Status" when a PR is opened.
=> Update status to assign to prs

docs/en/serverless/synthetics/synthetics-private-location.mdx
I _think_ https://github.com/elastic/observability-docs/pull/4234 should be ported to serverless. (Found in the audit! https://github.com/elastic/observability-docs/issues/4235)
=> [serverless] Add note about elastic-agent-complete

.github/pull_request_template.md
This is a first draft of PR template. The Serverless/Stateful section is a bit long. Thoughts?
=> First draft of PR template

docs/en/serverless/ai-assistant/ai-assistant.mdx
Ports #4130 to serverless.
N/A
N/A (This is a port)
=> Port #4130 to serverless

docs/en/serverless/apm-agents/apm-agents-opentelemetry-opentelemetry-native-support.mdx
Ports https://github.com/elastic/observability-docs/pull/4201 to serverless.
N/A
N/A (This is a port)
=> Port #4201 to serverless

docs/en/observability/apm/custom-index-template.asciidoc
Fix invalid data in apm docs
~~Closes #~~ 
_Select one._
=> Fix invalid json in apm docs

docs/en/observability/logs-ecs-application.asciidoc, docs/en/observability/logs-filter.asciidoc, docs/en/observability/logs-plaintext.asciidoc, docs/en/serverless/logging/view-and-monitor-logs.mdx
Updated the Logs Explorer name in some outdated docs.
_Select one._
=> Fix Logs Explorer naming in outdated docs

docs/en/observability/apm/custom-index-template.asciidoc, docs/en/observability/apm/data-streams.asciidoc, docs/en/observability/apm/ingest-pipelines.asciidoc
Remove mentions of integration packages as apm-server moved away from it in 8.15
Closes # 
_Select one._
=> Update docs after migrating from apm integration package to ES apm-data plugin in 8.15

docs/en/serverless/ai-assistant/ai-assistant.mdx
Ports #3957 to serverless.
Also adds a missing period.
n/a
_Select one._
=> Ports #3975 to serverless

docs/en/observability/synthetics-configuration.asciidoc, docs/en/serverless/synthetics/synthetics-configuration.mdx
Latest Synthetics version has added support for Playwright's `clientCertificates` option, which allows TLS client auth to be enabled for browser journeys. This option can be specified in project monitors or through the UI.
Closes #4335.
_Select one._
=> [Synthetics] Add client certificate reference to docs

docs/en/observability/index.asciidoc, docs/en/observability/tail-logs.asciidoc
Logs Stream is being deactivated by default. This PR addresses that, deemphasizes Logs Stream as a way to view and manage logs, but also includes instructions on activating Logs Stream if users do still want to use it.
Closes #4315 
_Select one._
=> Deprecate the Logs Stream app

docs/en/observability/monitor-infra/analyze-hosts.asciidoc
This PR removes the BETA note as Hosts move to GA in 8.16
___________
___________
Closes https://github.com/elastic/observability-docs/issues/4267
_Select one._
=> Update Hosts documentation to reflect GA

docs/en/observability/monitor-infra/analyze-hosts.asciidoc
This PR removes the feedback link inline.
Relates to https://github.com/elastic/observability-docs/pull/4371
_Select one._
=> [Hosts docs] Remove the feedback link inline

docs/en/observability/index.asciidoc, docs/en/observability/profiling-advanced-configuration.asciidoc, docs/en/observability/profiling-envs.asciidoc, docs/en/observability/profiling-no-kernel-version-check.asciidoc, docs/en/observability/profiling-probabilistic-profiling.asciidoc, docs/en/observability/profiling-tag-data-query.asciidoc
Document environment variables that can be used to configure the Universal Profiling Agent.
https://github.com/elastic/observability-docs/issues/4360
=> profiling: add information around environment variables

docs/en/observability/slo-create.asciidoc, docs/en/observability/synthetics-configuration.asciidoc, docs/en/serverless/slos/create-an-slo.mdx, docs/en/serverless/transclusion/synthetics/configuration/monitor-config-options.mdx
Document the new Synthetics availability SLI.
Preview: [Create a service-level objective (SLO) > Synthetics availability](https://observability-docs_bk_4346.docs-preview.app.elstc.co/guide/en/observability/master/slo-create.html#synthetics-availability-sli)
Closes #4299
_Select one._
=> [synthetics] Document Synthetics availability SLI

.github/Makefile
This should avoid https://github.com/elastic/observability-docs/pull/4387 and creating a new minor branch from `main`... it should be `8.x`
@elastic/obs-docs , I ran https://github.com/elastic/observability-docs/actions/runs/11383719000 but I didn't realise the branch off will be from `main` instead of `8.x`.
I need your super-power to delete the `8.16` branch 🙏
=> fix(new minor automation) change the location for `mergify` and use `8.x` instead of `main`

docs/en/observability/observability-ai-assistant.asciidoc
👋 These search connectors docs have moved to the Elasticsearch guide in 8.16.0, so updating those links. 
ℹ️ Managed or _native_ connectors still require the Enterprise Search server though so the link to the Enterprise Search docs for the _server_ is still correct.
=> Update links to search connectors docs

docs/en/observability/apm/collect-application-data/open-telemetry/otel-direct.asciidoc
Simplify otel collector sample config and make it valid.
closes #13550
closes #13551
_Select one._
=> Update Sample otelcol config

docs/en/observability/categorize-logs.asciidoc, docs/en/observability/configure-logs-sources.asciidoc, docs/en/observability/explore-logs.asciidoc, docs/en/observability/inspect-log-anomalies.asciidoc, docs/en/serverless/logging/view-and-monitor-logs.mdx
Document the new Kibana log source advanced setting that provides a centralized place to store log index patterns that other solutions can access instead of hardcoding index patterns in different places. 
This PR updates all of the places in the o11y docs where we were documenting using hardcoded log index patterns and replaces them with the logs source setting.
We will need to update the [Kibana advanced settings](https://www.elastic.co/guide/en/kibana/current/advanced-options.html) in another PR. The Discover docs may need an update as well.
Closes #4316 
_Select one._
=> Add docs for new central log source setting

docs/en/observability/monitor-infra/host-metrics.asciidoc, docs/en/serverless/infra-monitoring/host-metrics.mdx
Adds legacy section and updates CPU usage, Network Inbound, and Network Outbound to show new calculations.
Preview links:
* Stateful: https://observability-docs_bk_4386.docs-preview.app.elstc.co/guide/en/observability/master/host-metrics.html
* Serverless: https://observability-docs_bk_4386.docs-preview.app.elstc.co/guide/en/observability/master/host-metrics.html
Closes #4079 
_Select one._
=> Update metrics and add legacy section

docs/en/observability/observability-ai-assistant.asciidoc
We document Google Gemini in the connectors https://www.elastic.co/guide/en/kibana/current/gemini-action-type.html and in our release highlights https://www.elastic.co/guide/en/observability/current/whats-new.html, but it's missing from the o11y docs.
Add this mention to any place we list the supported connectors with the O11y AI Assistant.
TODO after merging:
=> O11y AI Assistant -  Google Gemini support

docs/en/observability/observability-ai-assistant.asciidoc
Minor typo I found while backporting.
n/a
No backports required because I've already fixed this in the backport PRs before merging.
_Select one._
=> Fix typo in observability-ai-assistant.asciidoc

docs/en/observability/profiling-get-started.asciidoc
Only for stack version 8.8 the v3 host agent version should be used. Starting with stack version 8.9, the host agent version is aligned to the stack version.
=> Profiling: fix stack version to profiling version alignment

.github/Makefile, .github/workflows/run-minor-release.yml
I fixed it partially, but missed that I need to set the branches correctly after. moving to 8.x
=> ci: fix branch creation and mergify file

docs/en/observability/threshold-alert.asciidoc
Adds documentation that explain new setting "no data" setting for the custom threshold rule.
Link to preview: https://observability-docs_bk_4418.docs-preview.app.elstc.co/guide/en/observability/master/custom-threshold-alert.html#trigger-alert-when-no-data
Closes #4068 
_Select one._
=> Document no data settings for custom threshold rule

docs/en/observability/observability-ai-assistant.asciidoc
=> Fix connectors links in observability-ai-assistant.asciidoc

docs/en/serverless/alerting/create-custom-threshold-alert-rule.mdx
Adds documentation about "no data" setting for custom threshold rule.
Closes https://github.com/elastic/observability-docs/issues/4429.
_Select one._
=> Port #4418 to serverless

docs/en/observability/apm/known-issues.asciidoc
Add a known issue section for APM to explain a problem occurring when upgrading to 8.15.0.
Closes # 
_Select one._
=> APM: add known issue of lazy rollover bug

docs/en/observability/apm/known-issues.asciidoc
Removes a rogue `+`.
N/A
_Select one._
=> Clean up new APM known issue

docs/en/observability/index.asciidoc, docs/en/observability/synthetics-command-reference.asciidoc, docs/en/observability/synthetics-mfa.asciidoc, docs/en/serverless/serverless-observability.docnav.json, docs/en/serverless/synthetics/synthetics-command-reference.mdx, docs/en/serverless/synthetics/synthetics-mfa.mdx
Add docs around the TOTP based MFA support in Synthetics https://github.com/elastic/synthetics/pull/957 and https://github.com/elastic/synthetics/pull/975 
Closes #4334 
=> add synthetics multi factor authentication docs

docs/en/apm-server/redirects.asciidoc, docs/en/observability/apm/api/apm-server/api-events.asciidoc, docs/en/observability/apm/api/apm-server/api-metadata.asciidoc, docs/en/observability/redirects.asciidoc
Closes https://github.com/elastic/observability-docs/issues/4479.
Needs permanent redirects too.
=> Fix 8.16 links

docs/en/serverless/apm/apm-troubleshooting/common-problems.asciidoc
Ports changes in https://github.com/elastic/observability-docs/pull/4333 to serverless docs. (Most of the changes in #4333 were not applicable to serverless docs.)
Closes #4420 
_Select one._
=> [apm] Port apm-data plugin changes from stateful docs

docs/en/serverless/apm-agents/apm-agents-aws-lambda-functions.asciidoc, docs/en/serverless/transclusion/apm/guide/install-agents/go.asciidoc, docs/en/serverless/transclusion/apm/guide/install-agents/node.asciidoc, docs/en/serverless/transclusion/apm/guide/install-agents/python.asciidoc, docs/en/serverless/transclusion/apm/guide/install-agents/ruby.asciidoc
Removes mentions of secret token in APM agent snippets in serverless docs.
Closes #4381
_Select one._
=> [apm] Remove mentions of secret token in APM agent snippets in serverless docs

docs/en/observability/profiling-get-started.asciidoc, docs/en/observability/profiling-self-managed-ops.asciidoc, docs/en/observability/profiling-self-managed.asciidoc
Remove the beta banner in the on-perm doc, cover areas of Universal Profiling documentation to allow on-perm users to operate the backend.
* host-agent telemetry
* programmatic setup
closes https://github.com/elastic/prodfiler/issues/5222 and elastic/prodfiler/issues/5319
_Select one._
=> Universal Profiling: on-prem GA additions

docs/en/observability/apm/known-issues.asciidoc
`prefer_ilm` setting was set to `false` in 8.15.1. This is not exactly a known issue but documenting it as one to raise awareness. Note that, `prefer_ilm` does not affect clusters using APM and upgrading to 8.15.x and the expectation was that the new guide would be followed for any new use-cases to customize ILM policies however, IaC based setups using the older way to customize ILM policies were affected due to the issue causing their **newly** created custom ILM configs to not apply.
NA
_Select one._
=> Raise prefer_ilm configuration as a known issue

docs/en/observability/apm/known-issues.asciidoc
Clarify that one of the suggested fix for the unmanaged indices bug introduced in 8.15.0 and fixed in 8.15.1 should only be applied for datatreams with default policies (as they are the only ones affected). If the suggested fix was applied to a datastream using custom ILM policy then the `prefer_ilm` setting needs to be added to the custom ILM policy.
Closes # 
_Select one._
=> Add reference to prefer-ilm setting for apm lifeycle known bug

docs/en/observability/observability-ai-assistant.asciidoc
There was a couple of stragglers here, they aren't broken links but they are soft redirects as of 8.16.0, so best to replace them. :)
=> Update search connectors links

docs/en/observability/whats-new.asciidoc
=> 8.16 What's new

docs/en/observability/synthetics-reference/lightweight-config/http.asciidoc, docs/en/serverless/transclusion/synthetics/reference/lightweight-config/http.asciidoc
Synthetics HTTP monitors doesnt support configuring URL endpoint via `hosts` instead its configurable via `urls`. This is a bug and only applicable to TCP and ICMP monitors. 
Raised by support https://elastic.slack.com/archives/CE4MRBU48/p1732062458578599
_Select one._
=> [Synthetics]: fix lightweight http configuration

docs/en/serverless/limitations.asciidoc, docs/en/serverless/what-is-observability-serverless.asciidoc
https://github.com/elastic/observability-docs/pull/4550
_Select one._
=> Remove stray tech preview references

.mergify.yml
Update the labels supported to backport to the just created 8.17 branch.
=> mergify: 8.17 backports

.github/Makefile
For some reason, `git checkout main` didn't run and created a PR with the wrong base branch, see https://github.com/elastic/observability-docs/pull/4553
https://github.com/elastic/observability-docs/pull/4391/files#diff-5712d072e70274b06faa283d7da2be2aeb554b214de3ba70c148664bd9c523b5R71 is the explicit checkout but it was not honoured :/
=> fix: force checkout from main

docs/en/observability/explore-logs.asciidoc
The Kibana permission Observability --> Logs (read) is also required as per internal tests on 8.16.1.
Closes # 
_Select one._
=> Update explore-logs.asciidoc missing permissions

docs/en/serverless/logging/get-started-with-logs.asciidoc, docs/en/serverless/logging/run-log-pattern-analysis.asciidoc, docs/en/serverless/logging/stream-log-files.asciidoc, docs/en/serverless/logging/troubleshoot-logs.asciidoc
Closes #4448, #4449, #4450, #4451, #4452, #4453  
_Select one._
=> Update serverless logs pages with bug bash updates

docs/en/observability/synthetics-mfa.asciidoc, docs/en/serverless/synthetics/synthetics-mfa.asciidoc
+ Fix the `mfa.totp` method which was incorrectly pointing to a method that was changed during the development process and updated incorrectly https://github.com/elastic/synthetics/pull/957#issuecomment-2496885901
=> [Synthetics]: fix MFA totp method for browser monitors

docs/en/observability/landing-page/temp/style.asciidoc
Changes the font size for hero text so that it's not glaringly large but still stands out a bit from ordinary text.
Note that I didn't make the Logs tab active as mentioned in the issue because I don't think that's the right approach. I think it introduces unexpected behavior that might be confusing to users who expect the first tab in a series to be shown by default.
Closes #3422 
_Select one._
=> Make hero text on obs landing page smaller

docs/en/serverless/alerting/create-custom-threshold-alert-rule.asciidoc
Ports #4349 to serverless.
Closes #4417 
_Select one._
=> Port #4349 to serverless

docs/en/serverless/limitations.asciidoc
Adds text to help users understand that they can reach out to support for help if they run into rate limiting or ingest failures related to severless limitations.
Closes #4583 
_Select one._
=> Tell users to contact support for rate limiting issues

docs/en/observability/configure-logs-sources.asciidoc
These logs settings only apply to the Logs Stream app, which will be deprecated in an upcoming release.
This PR adds a note that recommends people use Logs Explorer.
Closes #4540 
_Select one._
=> add logs explorer note to settings page

docs/en/observability/observability-ai-assistant.asciidoc
We no longer mention specific licenses in the docs and instead link users to the subscriptions page.
This PR adds the link to the subscriptions page and removes the mention of the Enterprise license in the prereqs.
=> Remove Enterprise subscription mention

docs/en/serverless/projects/billing.asciidoc
Adds content changes requested in #4640.
I've applied a few very minor edits to the recommended text (capitalization, comma fixes, removed redundant text).
[Preview link](https://observability-docs_bk_4641.docs-preview.app.elstc.co/guide/en/serverless/main/observability-billing.html)
Closes #4640
_Select one._
=> Update serverless billing dimensions for GA

docs/en/observability/apm/manage-storage/ilm-how-to.asciidoc
Rewords the ILM how-to guide for APM to mention revert to ILM policies (from DSL introduced in 8.15).
CC: @elastic/obs-ds-intake-services (not able to add as reviewers)
Closes https://github.com/elastic/apm-server/issues/14708
=> Reword ILM how to guide for revert to ILM policies

docs/en/observability/apm/getting-started-apm/index.asciidoc
Cleans up the [APM getting started intro page](https://observability-docs_bk_4599.docs-preview.app.elstc.co/guide/en/observability/master/apm-getting-started-apm-server.html) as discussed in #4336 including:
* **Which option is the "easiest"**: @simitt @bmorelli25 what do you think about just removing the note at the top and letting users determine which is the easiest method for their situation? If we can't say that one is easier than the other without explaining the context, then I'm not sure it makes sense to have a note at the top. 
* **What's preventing feature parity**: I moved this note to the part of the table that discusses supported outputs.
*  **Required components**: I rephrased the Elastic Agent list item (I was going to use a footnote but I was having trouble using it inside …
=> Clean up APM getting started intro page

docs/en/observability/apm/shared-docker.asciidoc
Add a note for alternative wolfi images for APM Server.
Closes # 
_Select one._
=> apm shared-docker: add note for wolfi image

docs/en/observability/apm/manage-storage/ilm-how-to.asciidoc
This PR updates `apm-ilm-how-to` page to expand DSL to ILM migration note. 
Closes # 
Needs changelog updates https://github.com/elastic/apm-server/pull/14909 to be merged first.  
_Select one._
=> apm-ilm: update apm-ilm-how-to expand dsl migration note

docs/en/observability/observability-ai-assistant.asciidoc, docs/en/serverless/ai-assistant/ai-assistant.asciidoc
Add documentation entry about for Elastic product documentation feature for the o11y AI Assistant, and add link for air-gapped installation (for stateful only)
Part of https://github.com/elastic/kibana/issues/199999
=> o11y AI assistant: add doc entry about the product doc

docs/en/observability/apm/security/data-security/custom-filter.asciidoc, docs/en/observability/apm/security/data-security/index.asciidoc
Updates custom filters page.
Closes #4314
_Select one._
=> [apm] Update custom filters page

docs/en/observability/apm/getting-started-apm/get-started-with-fleet-apm-server.asciidoc
Updates the  Fleet-managed APM Server guide to address feedback from @eedugon including:
* Let users know that they don't _have_ to set up a Fleet Server if they already have one set up.
* Let users know that that the APM integration doesn't _have_ to run in the same agent that acts as the Fleet Server, but that is the easiest way to get started.
There are some points that @eedugon brought up in https://github.com/elastic/observability-docs/issues/4668 that are not addressed here including:
* _Shouldn't we rely and refer to the Fleet documentation for the Fleet Setup (if it's not already done)?_
The content for both the [Prerequisites](https://www.elastic.co/guide/en/observability/current/get-started-with-fleet-apm-server.html#_prerequisites_5) and [Step 1: Set up …
=> [apm] Clarify requirements in the Fleet-managed APM Server guide

docs/en/observability/apm/configure/agent-config.asciidoc
In https://github.com/elastic/observability-docs/issues/4724, @eedugon brought up a couple points of confusion in [Configure APM agent configuration](https://www.elastic.co/guide/en/observability/current/apm-configure-agent-config.html):
* It's not clear that while some configuration options listed on this page are only supported for APM Server binary users, APM agent configuration as a feature is supported by all APM Server deployment methods.
* I updated the note at the beginning make this clearer.
* The title and first paragraph are confusing.
* I talked through this with @bmorelli25 today. Both [APM agent central configuration](https://www.elastic.co/guide/en/observability/current/apm-agent-configuration.html)  and [Configure APM agent …
=> [apm] Clarify doc on configuring APM agent central configuration

docs/en/observability/observability-ai-assistant.asciidoc
The connector docs are to be the source of truth for supported Generative AI providers. https://github.com/elastic/observability-docs/pull/4143 intended to remove a supported providers list from the documentation. Unfortunately, during the cherrypick process (https://github.com/elastic/observability-docs/pull/4407), conflicts prevented this deletion from making it to main. This PR syncs our AI assistant docs with the changes proposed, discussed, and merged in https://github.com/elastic/observability-docs/pull/4143.
A more recent and related comment supporting this decision is in https://github.com/elastic/observability-docs/issues/4410#issuecomment-2489615754. 
* Closes https://github.com/elastic/observability-docs/issues/4410
* Closes …
=> Remove list of supported generative AI providers

docs/en/observability/apm/configure/sampling.asciidoc, docs/en/observability/apm/data-model/transactions/sampling.asciidoc
Clarifies that tail-based sampling is only supported when writing to Elasticsearch.
Closes #4724 
_Select one._
=> Clarify that tail-based sampling is only available for ES output

docs/en/observability/apm/collect-application-data/agents/source-map-how-to.asciidoc
The nodejs snippet provided contains an error on how to pass the file content to the request method. This PR fixes that.
N/A
_Select one._
=> fix: Add changes for upload sourcemaps snippet

docs/en/observability/apm/api/apm-server/api-jaeger.asciidoc
Closes https://github.com/elastic/apm-server/issues/14767
_Select one._
=> Add deprecation warning to Jaeger API docs

docs/en/serverless/index.asciidoc, docs/en/serverless/slos/slo-troubleshoot.asciidoc, docs/en/serverless/slos/slos.asciidoc
Port PR #4486 to Serverless (SLO troubleshooting doc).
Closes https://github.com/elastic/observability-docs/issues/4603
Preview links:
- https://observability-docs_bk_4719.docs-preview.app.elstc.co/guide/en/serverless/current/slo-troubleshoot-slos.html
- https://observability-docs_bk_4719.docs-preview.app.elstc.co/guide/en/serverless/current/observability-slos.html
Closes https://github.com/elastic/observability-docs/issues/4603
_Select one._
=> SLOs troubleshoot added to serverless content (port #4486)

docs/en/observability/index.asciidoc, docs/en/observability/profiling-known-issues.asciidoc
Adds "Known Issue" section to Universal Profiling docs.
Entry in the known issue is listing the collector Helm chart problem discovered recently.
=> add known issues section to profiling docs

docs/en/observability/observability-get-started.asciidoc, docs/en/serverless/observability-get-started.asciidoc
This PR adds a link to the "Monitor hosts with OTel" quickstart to the Get started page.
_Select one._
=> Add OTel quickstart to Get started page

docs/en/observability/observability-ai-assistant.asciidoc
The Obs AI Assistant supports other models than ELSER when field type semantic_text is used and the docs need to be updated to show this.
Closes #4608 
_Select one._
=> Obs AI Assistant supports other models than ELSER when field type semantic_text is used

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
Use [`pre-commit`](https://pre-commit.com/) with a subset of checks and run in the CI.
Similarly done at https://github.com/elastic/beats/pull/42377
Help with detecting merge conflicts or shebang issues in the shell scripts
Closes # 
_Select one._
=> github-actions(pre-commit): detect merge conflicts and shebangs

docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudtrail-firehose.asciidoc, docs/en/observability/cloud-monitoring/aws/monitor-aws-cloudwatch-firehose.asciidoc, docs/en/observability/cloud-monitoring/aws/monitor-aws-firewall-firehose.asciidoc, docs/en/observability/cloud-monitoring/aws/monitor-aws-waf-firehose.asciidoc
When setting up an AWS Firehose data stream, users should use the Elasticsearch endpoint URL that contains the .es subdomain. 
While the non-.es URLs currently work and will continue to function, the URL containing the .es subdomain is designed as the dedicated endpoint for connecting to Elasticsearch. These URLs are the best option for future-proofing your setup, and we should recommend using them.
Closes # 
_Select one._
=> [AWS Firehose] Clarify where to find ES endpoint

docs/en/observability/logs-troubleshooting.asciidoc, docs/en/serverless/logging/troubleshoot-logs.asciidoc
Adding common mapping and pipeline issues to the Logs troubleshooting page.
Closes #4529 
_Select one._
=> Add common pipeline and mapping issues and mitigations

docs/en/observability/apm/collect-application-data/agents/agent-configuration.asciidoc, docs/en/observability/apm/data-model/transactions/sampling.asciidoc, docs/en/observability/apm/security/elastic-stack/feature-roles.asciidoc
Add notes to features that are not supported in serverless.
Closes #4764
_Select one._
cc @chrisdistasio
=> Note features that are not supported in serverless

docs/en/serverless/cases/manage-cases-settings.asciidoc
Relates to https://github.com/elastic/docs/pull/3160
This PR fixes the following broken link:
```
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/serverless/current/observability-case-settings.html contains broken links to:
--
  | INFO:build_docs:   - en/kibana/master/thehive-action-type.html
```
I think this PR only needs to be merged if we assume that we'll want to stop the main branch of the Kibana Guide before we stop building the only branch of the Serverless Guide.
Closes # 
_Select one._
=> [DOCS] Remove links to master

docs/en/ingest-management/elastic-agent/run-container-common/kibana-fleet-data.asciidoc, docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc, docs/en/observability/whats-new.asciidoc
Relates to https://github.com/elastic/docs/pull/3160
This PR fixes the following type of documentation build error, which occurs when we retire the master documentation:
```
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/observability/8.6/whats-new.html contains broken links to:
--
  | INFO:build_docs:   - en/kibana/master/opsgenie-action-type.html
```
Relates to https://github.com/elastic/docs/pull/3160
_Select one._
=> [DOCS] Fix hard-coded links to master

docs/en/observability/apm/security/data-security/filtering.asciidoc
Add note on APM Server about capturing personal data.
Resolves https://github.com/elastic/apm-server/issues/13622.
_Select one._
=> Add note on APM Server Personal Data

docs/en/observability/apm/security/data-security/filtering.asciidoc
Add missing backports for previous PR: https://github.com/elastic/observability-docs/pull/4825
_Select one._
=> [8.18](backport) Manual backport missing from previous PR

docs/en/observability/grant-cases-access.asciidoc
Partially addresses https://github.com/elastic/docs-content/issues/333. Makes minor changes to future-proof docs for giving full access to manage cases and settings.
Preview: [Cases requirements](https://security-docs_bk_6641.docs-preview.app.elstc.co/guide/en/security/8.x/case-permissions.html)
**Related PRs:**
- 9.0 and Serverless docs (all): https://github.com/elastic/docs-content/pull/831
- Kibana docs: https://github.com/elastic/kibana/pull/215162
- Security docs: https://github.com/elastic/security-docs/pull/6641
=> [8.18] New sub-feature priv for case assignees

docs/en/observability/apm/configure/sampling.asciidoc
Documents the metrics produced by Tail-based sampler of APM Server and adds a few tips on how to monitor storage requirements.
This PR is the 8.x version of https://github.com/elastic/docs-content/pull/852
Closes https://github.com/elastic/apm-server/issues/14996
_Select one._
=> Add docs for monitoring TBS

docs/en/observability/synthetics-create-test.asciidoc
Fix Synthetics step async declaration in provided examples.
_Select one._
=> [Synthetics] Fix step async declaration in snippets

docs/en/observability/apm/view-and-analyze/inventory.asciidoc, docs/en/observability/elastic-entity-model.asciidoc
Hides the [EEM](https://www.elastic.co/guide/en/serverless/current/observability-elastic-entity-model.html) and [Inventory](https://www.elastic.co/guide/en/serverless/current/observability-inventory.html) pages from appearing in the table of contents and from search engines. However, the pages will still be published in case any users have explicitly enabled entityCentricExperience.
Related to https://github.com/elastic/observability-docs/issues/4690, https://github.com/elastic/docs-content/pull/1057
_Select one._
=> Hide EEM and inventory pages

docs/en/observability/apm/collect-application-data/open-telemetry/index.asciidoc, docs/en/observability/quickstarts/monitor-hosts-with-otel.asciidoc, docs/en/observability/quickstarts/monitor-k8s-otel.asciidoc
Use GitHub pages links instead of links to Markdown files in the elastic/opentelemetry repo. A larger reworking of OpenTelemetry content in the Observability docs is happening in https://github.com/elastic/docs-content/pull/985, but this fixes existing broken links in the pre-9.0 docs.
N/A
_Select one._
=> [otel] Use GitHub pages links

.github/workflows/backport-active.yml, .mergify.yml
New way of backporting to active branches using new github action.
No need to support the hardcoded branches in the `.mergify.yml` file anymore.
We use a dynamic approach by fetching https://storage.googleapis.com/artifacts-api/snapshots/branches.json and filtering the branches.
Already enabled in Elastic Agent:
- https://github.com/elastic/elastic-agent/actions/workflows/backport-active.yml
=> New way of backporting

docs/en/observability/synthetics-private-location.asciidoc
Documents that synthetics private locations can now be space aware.
Related to https://github.com/elastic/observability-docs/issues/4794, https://github.com/elastic/docs-content/pull/1061
_Select one._
=> [synthetics] Document private locations space awareness
