elastic/observability-docs

- docs/en/ingest-management/troubleshooting.asciidoc
- docs/en/logs/logs-installation.asciidoc
- docs/en/metrics/metrics-installation.asciidoc
- Change links to refactored Beats getting started docs (#15)
> [7.x] Change links to refactored Beats getting started docs (#15)

- docs/en/ingest-management/getting-started.asciidoc
> Remove standalone suffix from the documentation.

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Fix errors in examples (#37)
> [7.x] Fix errors in examples (#37)

- docs/en/observability/index.asciidoc
- docs/en/observability/observability-introduction.asciidoc
- docs/en/observability/observability-ui.asciidoc
Adds Observability docs to `7.x` by cherry picking 92786f58560c95a4b051c92c9731631e89503b25 and 3662540184a3338eca816ed3bcd4611751f97848.
> [7.x] Add Obs docs to 7.x

- docs/en/observability/index.asciidoc
- docs/en/observability/observability-introduction.asciidoc
- docs/en/observability/observability-ui.asciidoc
Adds Observability docs to `7.9` by cherry picking 92786f58560c95a4b051c92c9731631e89503b25 and 3662540184a3338eca816ed3bcd4611751f97848.
> [7.9] Add Obs docs to 7.9

- docs/en/uptime/install.asciidoc
- Update link to Heartbeat quick start (#41)
> [7.x] Update link to Heartbeat quick start (#41)

- docs/en/uptime/install.asciidoc
- Update link to Heartbeat quick start (#41)
> [7.9] Update link to Heartbeat quick start (#41)

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Minor change to use asciidoctor-preferred tagging.
(I backed out my heading level changes because I think they are correct for future work.)
> Clean up heading tags in ingest management docs

- docs/en/ingest-management/troubleshooting.asciidoc
- Move content about how to stop Elastic Agent (#49)
> [7.x] Move content about how to stop Elastic Agent (#49)

- docs/en/ingest-management/troubleshooting.asciidoc
- Move content about how to stop Elastic Agent (#49)
> [7.9] Move content about how to stop Elastic Agent (#49)

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/ingest-management-limitations.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Promote ingest management docs to beta in preparation in 7.9
> [docs] Promote ingest management to beta

- docs/en/ingest-management/troubleshooting.asciidoc
- [docs] Add troubleshooting topic about running under SYSTEM for Endpoint (#68)
> [7.9] [docs] Add troubleshooting topic about running under SYSTEM for Endpoint (#68)

- docs/en/ingest-management/troubleshooting.asciidoc
- [docs] Add troubleshooting topic about running under SYSTEM for Endpoint (#68)
> [7.x] [docs] Add troubleshooting topic about running under SYSTEM for Endpoint (#68)

- docs/en/ingest-management/ingest-management-limitations.asciidoc
- Update ingest-management-limitations.asciidoc (#88)
> [7.x] Update ingest-management-limitations.asciidoc (#88)

- docs/en/ingest-management/ingest-management-limitations.asciidoc
- Update ingest-management-limitations.asciidoc (#88)
> [7.9] Update ingest-management-limitations.asciidoc (#88)

- docs/en/ingest-management/ingest-management-limitations.asciidoc
Initial attempt at documenting the limits we arrived at for 7.9 on Cloud. Would love to get your input on how to arrange it nicely @dedemorton
> document limits on Cloud for 7.9

- docs/en/ingest-management/troubleshooting.asciidoc
- Update description of Endpoint integration in troubleshooting (#101)
> [7.x] Update description of Endpoint integration in troubleshooting (#101)

- docs/en/ingest-management/troubleshooting.asciidoc
- Update description of Endpoint integration in troubleshooting (#101)
> [7.9] Update description of Endpoint integration in troubleshooting (#101)

- docs/en/ingest-management/getting-started.asciidoc
Small typo fix: Ingegrations > Integrations
> [Docs]Ingest Manager quick start guide typo

- docs/en/ingest-management/troubleshooting.asciidoc
Fixes elastic/observability-docs#95.
Related to: https://github.com/elastic/beats/pull/20700 (required before this PR will build without errors)
> [docs] Add steps for making agent persistent on macos

- docs/en/ingest-management/troubleshooting.asciidoc
- [docs] Add steps for making agent persistent on macos (#105)
> [7.x] [docs] Add steps for making agent persistent on macos (#105)

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
Minor change to fix problem described in issue #90
> Remove repetitive wording

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
- Remove repetitive wording (#112)
> [7.9] Remove repetitive wording (#112)

- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/ingest-management-overview.asciidoc
- Remove repetitive wording (#112)
> [7.x] Remove repetitive wording (#112)

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Make troubleshooting and FAQ separate topics (#120)
> [7.x] Make troubleshooting and FAQ separate topics (#120)

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Make troubleshooting and FAQ separate topics (#120)
> [7.9] Make troubleshooting and FAQ separate topics (#120)

- docs/en/observability/install-observability.asciidoc
Link fix for https://github.com/elastic/apm-server/pull/4222.
> docs: link to APM Server ref

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/tab-widgets/prereq.asciidoc
Removes old reviewer notes that should have been removed before merging the PR.
> Remove old reviewer notes

- docs/en/observability/monitor-java-app.asciidoc
This PR makes the images consistent with other topics in the observability docs.
> Add screenshot role to screen captures in the java tutorial

- docs/en/observability/monitor-java-app.asciidoc
- Add screenshot role to screens (#156)
> [7.x] Add screenshot role to screens (#156)

- docs/en/uptime/install.asciidoc
- docs/en/uptime/overview.asciidoc
> [7.x] Update links (#172)

- docs/en/uptime/install.asciidoc
- docs/en/uptime/overview.asciidoc
> [7.10] Update links (#172)

- docs/en/observability/ingest-uptime.asciidoc
Same change as to the Heartbeat docs
> add observer.geo.name for maps and machine learning

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Update endpoint-related terminology (#160)
> [7.x] Update endpoint-related terminology (#160)

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Update endpoint-related terminology (#160)
> [7.10] Update endpoint-related terminology (#160)

- docs/en/observability/index.asciidoc
- docs/en/observability/instrument-apps.asciidoc
- docs/en/observability/whats-new.asciidoc
* Fixes the broken cross-doc includes in the instrument-apps section
* Adds "what's new" placeholder content
Closes https://github.com/elastic/observability-docs/issues/186
Closes https://github.com/elastic/observability-docs/issues/179 (Tracking for content will be handled in the new issue)
> Fixes Instrument APM + Adds what's new 

- docs/en/observability/index.asciidoc
- docs/en/observability/instrument-apps.asciidoc
- docs/en/observability/whats-new.asciidoc
- Fixes Instrument APM + Adds what's new  (#188)
> [7.x] Fixes Instrument APM + Adds what's new  (#188)

- docs/en/observability/index.asciidoc
- docs/en/observability/instrument-apps.asciidoc
- docs/en/observability/whats-new.asciidoc
- Fixes Instrument APM + Adds what's new  (#188)
> [7.10] Fixes Instrument APM + Adds what's new  (#188)

- docs/en/observability/monitor-java-app.asciidoc
- docs/en/observability/tail-logs.asciidoc
- docs/en/observability/view-infrastructure-metrics.asciidoc
- docs/en/observability/view-monitor-status.asciidoc
This PR updates links within the Observability Guide. The updates are required due to build failures on this [PR](https://github.com/elastic/docs/pull/1985).
https://github.com/elastic/docs/pull/1985
https://github.com/elastic/observability-docs/issues/189
> Update internal links

- docs/en/observability/monitor-java-app.asciidoc
- docs/en/observability/tail-logs.asciidoc
- docs/en/observability/view-infrastructure-metrics.asciidoc
- docs/en/observability/view-monitor-status.asciidoc
> [7.x] Update links (#195)

- docs/en/observability/monitor-java-app.asciidoc
- Add a note about Cloud ID (#211)
> [7.10] Add a note about Cloud ID (#211)

- docs/en/observability/monitor-java-app.asciidoc
- Add a note about Cloud ID (#211)
> [7.x] Add a note about Cloud ID (#211)

- docs/en/observability/monitor-java-app.asciidoc
> [7.x] Fix broken link (#217)

- docs/en/observability/monitor-java-app.asciidoc
> [7.10] Fix broken link (#217)

- docs/en/ingest-management/fleet-limitations.asciidoc
This updates the limits 8000 for 8gb, 4k for 4gb and 2k for 1gb .
> Update limits based on effort for 7.10

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/getting-started.asciidoc
- Update installation and standalone agent content (#212)
> [7.x] Update installation and standalone agent content (#212)

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/getting-started.asciidoc
- Update installation and standalone agent content (#212)
> [7.10] Update installation and standalone agent content (#212)

- docs/en/observability/whats-new.asciidoc
Adds the Core Web Vitals release date to "What's new?"
> [7.10] docs: add CWV release date

- docs/en/ingest-management/fleet-limitations.asciidoc
- Update limits based on effort for 7.10 (#225)
> [7.10] Update limits based on effort for 7.10 (#225)

- docs/en/observability/user-experience.asciidoc
User experience was upgraded to a top-level category on Discuss. This updates the link.
> docs: update UE discuss link

- docs/en/observability/user-experience.asciidoc
- docs: update UE discuss link (#250)
> [7.x] docs: update UE discuss link (#250)

- docs/en/observability/user-experience.asciidoc
- docs: update UE discuss link (#250)
> [7.10] docs: update UE discuss link (#250)

- docs/en/ingest-management/fleet-limitations.asciidoc
- Update limits based on effort for 7.10 (#225)
> [7.x] Update limits based on effort for 7.10 (#225)

- docs/en/ingest-management/getting-started.asciidoc
Fixes minor issues found while testing on deb/rpm.
> Add fixes from deb/rpm testing

- docs/en/ingest-management/getting-started.asciidoc
- Add fixes from deb/rpm testing (#263)
> [7.10] Add fixes from deb/rpm testing (#263)

- docs/en/ingest-management/getting-started.asciidoc
- Add fixes from deb/rpm testing (#263)
> [7.x] Add fixes from deb/rpm testing (#263)

- docs/en/observability/synthetics-quickstart.asciidoc
- Update synthetics quickstart (#260)
> [7.10] Update synthetics quickstart (#260)

- docs/en/observability/synthetics-quickstart.asciidoc
- Update synthetics quickstart (#260)
> [7.x] Update synthetics quickstart (#260)

- docs/en/observability/monitor-java-app.asciidoc
As part of the 7.10 Kibana docs changes, I've updated this link to match the section title.
Related to elastic/kibana#84000.
> [DOCS] Updates link to Kibana Lens

- docs/en/observability/infrastructure-threshold-alert.asciidoc
- docs/en/observability/logs-threshold-alert.asciidoc
- docs/en/observability/metrics-threshold-alert.asciidoc
> [7.10] Add settings info (#291)

- docs/en/observability/infrastructure-threshold-alert.asciidoc
- docs/en/observability/logs-threshold-alert.asciidoc
- docs/en/observability/metrics-threshold-alert.asciidoc
> [7.x] Add settings info (#291)

- docs/en/ingest-management/fleet-overview.asciidoc
- Add info about namespace length limit (#148)
> [7.10] Add info about namespace length limit (#148)

- docs/en/ingest-management/fleet-overview.asciidoc
- Add info about namespace length limit (#148)
> [7.11] Add info about namespace length limit (#148)

- docs/en/ingest-management/fleet-overview.asciidoc
- Add info about namespace length limit (#148)
> [7.x] Add info about namespace length limit (#148)

- docs/en/observability/analyze-metrics.asciidoc
- docs/en/observability/apm.asciidoc
- docs/en/observability/monitor-logs.asciidoc
- docs/en/observability/user-experience.asciidoc
- docs: Add quickstart videos (#324)
> [7.11] docs: Add quickstart videos (#324)

- docs/en/observability/analyze-metrics.asciidoc
- docs/en/observability/apm.asciidoc
- docs/en/observability/monitor-logs.asciidoc
- docs/en/observability/user-experience.asciidoc
- docs: conditionally display videos in obs-docs (#350)
> [7.10] docs: conditionally display videos in obs-docs (#350)

- docs/en/observability/analyze-metrics.asciidoc
- docs/en/observability/apm.asciidoc
- docs/en/observability/monitor-logs.asciidoc
- docs/en/observability/user-experience.asciidoc
- docs: conditionally display videos in obs-docs (#350)
> [7.x] docs: conditionally display videos in obs-docs (#350)

- docs/en/ingest-management/faq.asciidoc
- Update FAQ info about agent policies (#343)
> [7.x] Update FAQ info about agent policies (#343)

- docs/en/ingest-management/faq.asciidoc
- Update FAQ info about agent policies (#343)
> [7.11] Update FAQ info about agent policies (#343)

- docs/en/ingest-management/faq.asciidoc
- Update FAQ info about agent policies (#343)
> [7.10] Update FAQ info about agent policies (#343)

- docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
- docs: fix Filebeat config step 5 (#373)
> [master] docs: fix Filebeat config step 5 (#373)

- docs/en/ingest-management/troubleshooting.asciidoc
> Add troubleshooting problem about telemetry issue in 7.11

- docs/en/ingest-management/troubleshooting.asciidoc
- Add troubleshooting problem about telemetry issue in 7.11 (#374)
> [7.x] Add troubleshooting problem about telemetry issue in 7.11 (#374)

- docs/en/ingest-management/troubleshooting.asciidoc
- Add troubleshooting problem about telemetry issue in 7.11 (#374)
> [7.11] Add troubleshooting problem about telemetry issue in 7.11 (#374)

- docs/en/ingest-management/fleet-overview.asciidoc
Closes https://github.com/elastic/beats/issues/23554 and #319.
> Adds short blurb with pointer about agent self-protection

- docs/en/ingest-management/fleet-overview.asciidoc
- Adds short blurb with pointer about agent self-protection (#372)
> [7.11] Adds short blurb with pointer about agent self-protection (#372)

- docs/en/ingest-management/fleet-overview.asciidoc
- Adds short blurb with pointer about agent self-protection (#372)
> [7.x] Adds short blurb with pointer about agent self-protection (#372)

- docs/en/ingest-management/faq.asciidoc
Reading through the docs and I find a few items I had meant to help update after some recent feature work was updated.
> Small FAQ updates for Fleet / Agent based on recent feature work

- docs/en/ingest-management/faq.asciidoc
- Small FAQ updates for Fleet / Agent based on recent feature work (#403)
> [7.x] Small FAQ updates for Fleet / Agent based on recent feature work (#403)

- docs/en/ingest-management/faq.asciidoc
- Small FAQ updates for Fleet / Agent based on recent feature work (#403)
> [7.12] Small FAQ updates for Fleet / Agent based on recent feature work (#403)

- docs/en/ingest-management/faq.asciidoc
- Small FAQ updates for Fleet / Agent based on recent feature work (#403)
> [7.11] Small FAQ updates for Fleet / Agent based on recent feature work (#403)

- docs/en/observability/ingest-logs.asciidoc
- [DOCS] Updates Kibana main menu path (#413)
> [7.12] [DOCS] Updates Kibana main menu path (#413)

- docs/en/observability/ingest-metrics.asciidoc
- [DOCS] Updates Kibana path for Metricbeat (#414)
> [master] [DOCS] Updates Kibana path for Metricbeat (#414)

- docs/en/observability/ingest-metrics.asciidoc
- [DOCS] Updates Kibana path for Metricbeat (#414)
> [7.x] [DOCS] Updates Kibana path for Metricbeat (#414)

- docs/en/observability/ingest-logs.asciidoc
- [DOCS] Updates Kibana main menu path (#413)
> [master] [DOCS] Updates Kibana main menu path (#413)

- docs/en/observability/ingest-logs.asciidoc
- [DOCS] Updates Kibana main menu path (#413)
> [7.x] [DOCS] Updates Kibana main menu path (#413)

- docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
- Update elastic-agent-command-line.asciidoc (#406)
> [7.x] Update elastic-agent-command-line.asciidoc (#406)

- docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
- Update elastic-agent-command-line.asciidoc (#406)
> [master] Update elastic-agent-command-line.asciidoc (#406)

- docs/en/ingest-management/elastic-agent/elastic-agent-command-line.asciidoc
- Update elastic-agent-command-line.asciidoc (#406)
> [7.12] Update elastic-agent-command-line.asciidoc (#406)

- docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- Added docs for capabilities (#422)
> [7.x] Added docs for capabilities (#422)

- docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- Added docs for capabilities (#422)
> [7.12] Added docs for capabilities (#422)

- docs/en/observability/explore-metrics.asciidoc
Updates the TSVB links to the new location in the Kibana Product Guide.
> Updates TSVB links

- docs/en/observability/explore-metrics.asciidoc
> [7.12] Updates TSVB links (#456)

- docs/en/observability/explore-metrics.asciidoc
> [7.x] Updates TSVB links (#456)

- docs/en/observability/synthetics-command-reference.asciidoc
- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- 7.12 Synthetics Docs Changes (#431)
> [7.x] 7.12 Synthetics Docs Changes (#431)

- docs/en/observability/synthetics-command-reference.asciidoc
- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- 7.12 Synthetics Docs Changes (#431)
> [7.12] 7.12 Synthetics Docs Changes (#431)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- Update install-elastic-agent.asciidoc (#462)
> [7.x] Update install-elastic-agent.asciidoc (#462)

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
This PR is required before we can merge elastic/docs#2097.
> [7.9] Add discrete tags to prep for book changing chunk level

- docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
This PR is required before we can merge elastic/docs#2097.
> [7.x] Refactor files to prep for book changing chunk level

- docs/en/observability/configure-uptime-settings.asciidoc
- Update security note for configuring uptime settings (#485)
> [7.12] Update security note for configuring uptime settings (#485)

- docs/en/observability/configure-uptime-settings.asciidoc
- Update security note for configuring uptime settings (#485)
> [7.11] Update security note for configuring uptime settings (#485)

- docs/en/observability/tail-logs.asciidoc
- docs: add logs app video (#470)
> [7.12] docs: add logs app video (#470)

- docs/en/observability/tail-logs.asciidoc
- docs: add logs app video (#470)
> [7.x] docs: add logs app video (#470)

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Closes https://github.com/elastic/beats/issues/23597
I tesed on macOS, but extrapolated for other platforms. Please confirm that the paths are correct.
> Document location of Beats logs

- docs/en/ingest-management/elastic-agent/elastic-agent-capabilities.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-conditions.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-functions.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-providers.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/upgrade-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
The PR containing fixes for this problem in master is stalled waiting for dev input (https://github.com/elastic/observability-docs/pull/424), so let's add the discrete tags now. I don't want folks who are contributing content in master to think that the book structure is changing.
> Add discrete tags to fix chunk level

- docs/en/ingest-management/tab-widgets/download.asciidoc
- Update download.asciidoc (#455)
> [master] Update download.asciidoc (#455)

- docs/en/ingest-management/tab-widgets/download.asciidoc
- Update download.asciidoc (#455)
> [7.x] Update download.asciidoc (#455)

- docs/en/ingest-management/tab-widgets/download.asciidoc
- Update download.asciidoc (#455)
> [7.12] Update download.asciidoc (#455)

- docs/en/observability/create-alerts.asciidoc
Current PR contains the changes in the alerting links, which is required for merging upcoming [PR](https://github.com/elastic/kibana/pull/95004) for improving Alerting documents structure.
> [Alerting] Changed alerting management links due to the upcoming changes in the alerting docs.

- docs/en/ingest-management/agent-policies.asciidoc
- Update agent-policies.asciidoc (#532)
> [7.12] Update agent-policies.asciidoc (#532)

- docs/en/ingest-management/agent-policies.asciidoc
- Update agent-policies.asciidoc (#532)
> [7.x] Update agent-policies.asciidoc (#532)

- docs/en/ingest-management/fleet-overview.asciidoc
Hi - I don't know if you've gotten far into it yet, but it may be helpful to push super small and incremental Docs in as the whole Engineering team will be looking at this as of BC1 and we'll have lots of questions.  
Anything accurate we can get in place may be helpful and can certainly be changed as desired...
> quick fleet server blurb

- docs/en/ingest-management/fleet-overview.asciidoc
- quick fleet server blurb (#539)
> [7.x] quick fleet server blurb (#539)

- docs/en/fleet-developer/fleet-architecture.asciidoc
- docs/en/fleet-developer/fleet-ports.asciidoc
- docs/en/fleet-developer/fleet-security-model.asciidoc
- docs/en/fleet-developer/index.asciidoc
Adds small set of placeholder files to get the book building.
> Add placeholder files for Fleet Developer Guide

- docs/en/ingest-management/troubleshooting.asciidoc
This is a pretty rough start at updates, but it is content.  And I trust the Docs team to take it and make it more better for our users, hope it helps!
attempt at contributing towards:
https://github.com/elastic/observability-docs/issues/526
https://observability-docs_616.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-troubleshooting.html
> Fleet server: updating the troubleshooting info

- docs/en/ingest-management/fleet/fleet-server.asciidoc
implementing a suggestion to help alleviate:
https://github.com/elastic/observability-docs/issues/620
feedback and further updates welcome.  I don't want the initial paragraph to get too long, but feel the importance to call out its 'one to many' nature up front, as well as proving the nuance that it is part of the stack, but lives on the 'edge' hosts and acknowledge it is called to life from an Agent itself, while being a special component. : /  I'm sure we can do more, just incrementally pushing up achievable updates!  :)
> Quick update to Fleet Server main paragraph

- docs/en/ingest-management/troubleshooting.asciidoc
- Fleet server: updating the troubleshooting info (#616)
> [7.x] Fleet server: updating the troubleshooting info (#616)

- docs/en/ingest-management/troubleshooting.asciidoc
- Fleet server: updating the troubleshooting info (#616)
> [7.13] Fleet server: updating the troubleshooting info (#616)

- docs/en/ingest-management/fleet/fleet-server.asciidoc
- Quick update to Fleet Server main paragraph (#621)
> [7.x] Quick update to Fleet Server main paragraph (#621)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add placeholder file for release notes (#614)
> [7.x] Add placeholder file for release notes (#614)

- docs/en/observability/synthetics-command-reference.asciidoc
- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- docs: update synthetics with zip support (#609)
> [7.x] docs: update synthetics with zip support (#609)

- docs/en/observability/synthetics-command-reference.asciidoc
- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- docs: update synthetics with zip support (#609)
> [7.13] docs: update synthetics with zip support (#609)

- docs/en/fleet-developer/fleet-architecture.asciidoc
- docs/en/fleet-developer/fleet-security-model.asciidoc
This doc changes describes the different API Keys that are used by Fleet and fleet-server.
> [Fleet Server] Add details related to API Keys

- docs/en/observability/configure-uptime-settings.asciidoc
- docs/en/observability/create-alerts.asciidoc
- docs/en/observability/infrastructure-threshold-alert.asciidoc
- docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
- docs/en/observability/logs-threshold-alert.asciidoc
- docs/en/observability/metrics-threshold-alert.asciidoc
- docs/en/observability/monitor-status-alert.asciidoc
- docs/en/observability/observability-introduction.asciidoc
- docs/en/observability/observability-ui.asciidoc
- docs/en/observability/synthetics-visualize.asciidoc
- docs/en/observability/uptime-duration-anomaly-alert.asciidoc
- docs/en/observability/uptime-tls-alert.asciidoc
- docs/en/observability/view-monitor-status.asciidoc
- Update alerting terminology (#679)
> [7.13] Update alerting terminology (#679)

- docs/en/observability/synthetics-create-test.asciidoc
Clarify that dependencies cannot be added via imports with inline scripts.
> Clarify no import dependencies can be used with inline scripts

- docs/en/ingest-management/overview.asciidoc
This PR adds an overview of EPR. 
https://observability-docs_678.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-overview.html#package-registry-intro
Closes https://github.com/elastic/observability-docs/issues/524
> Add Elastic Package Registry (EPR) overview

- docs/en/ingest-management/overview.asciidoc
- Add Elastic Package Registry (EPR) overview (#678)
> [7.13] Add Elastic Package Registry (EPR) overview (#678)

- docs/en/ingest-management/overview.asciidoc
- Add Elastic Package Registry (EPR) overview (#678)
> [7.x] Add Elastic Package Registry (EPR) overview (#678)

- docs/en/ingest-management/fleet/fleet-limitations.asciidoc
- Updating limitations for 7.13 (#694)
> [master] Updating limitations for 7.13 (#694)

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- docs/en/ingest-management/index.asciidoc
Closes #525 
Please respond to questions that appears inline as comments. There is likely some fiction here. Please help me flesh this out with more detail.
> Add topic about Fleet settings

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- docs/en/ingest-management/index.asciidoc
- Add topic about Fleet settings (#673)
> [7.x] Add topic about Fleet settings (#673)

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- docs/en/ingest-management/index.asciidoc
- Add topic about Fleet settings (#673)
> [7.13] Add topic about Fleet settings (#673)

- docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Clean up release notes and add items from Kibana (#702)
> [7.13] Clean up release notes and add items from Kibana (#702)

- docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Clean up release notes and add items from Kibana (#702)
> [7.x] Clean up release notes and add items from Kibana (#702)

- docs/en/observability/whats-new.asciidoc
This PR fixes a Kibana attribute that has been rendered incorrectly.
[What's new]() --available soon
> [7.13][DOCS] Fixes an attribute in what's new

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
Adds a link to more info about Fleet settings.
> Add link to Fleet settings topic

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- Add link to Fleet settings topic (#713)
> [7.13] Add link to Fleet settings topic (#713)

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Fixes:
https://github.com/elastic/observability-docs/issues/722
https://github.com/elastic/observability-docs/issues/723
Thank you to QAS team for finding them, all of the fixes we can put in make the docs easier and experience better.
> Fixes two small errors in Fleet Server Docs

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
- Fixes two small errors in Fleet Server Docs (#728)
> [7.x] Fixes two small errors in Fleet Server Docs (#728)

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- docs/en/ingest-management/tab-widgets/install-layout.asciidoc
- Fixes two small errors in Fleet Server Docs (#728)
> [7.13] Fixes two small errors in Fleet Server Docs (#728)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
Adds known issue item (related to https://github.com/elastic/fleet-server/issues/380) to the release notes.
> Add Elastic Agent unenrollment issue

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add Elastic Agent unenrollment issue (#727)
> [7.13] Add Elastic Agent unenrollment issue (#727)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add Elastic Agent unenrollment issue (#727)
> [7.x] Add Elastic Agent unenrollment issue (#727)

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/tab-widgets/remove-endpoint-files/content.asciidoc
- docs/en/ingest-management/tab-widgets/remove-endpoint-files/widget.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Closes #382 
In this PR, I show the commands from a security-related PR (rather than 382) to be consistent with the security docs. Let me know if this makes sense.
> Update manual and endpoint uninstall steps

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/tab-widgets/remove-endpoint-files/content.asciidoc
- docs/en/ingest-management/tab-widgets/remove-endpoint-files/widget.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Update manual and endpoint uninstall steps (#718)
> [7.13] Update manual and endpoint uninstall steps (#718)

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/tab-widgets/remove-endpoint-files/content.asciidoc
- docs/en/ingest-management/tab-widgets/remove-endpoint-files/widget.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Update manual and endpoint uninstall steps (#718)
> [7.x] Update manual and endpoint uninstall steps (#718)

- docs/en/ingest-management/troubleshooting.asciidoc
- Update troubleshooting.asciidoc (#734)
> [7.13] Update troubleshooting.asciidoc (#734)

- docs/en/ingest-management/troubleshooting.asciidoc
- Update troubleshooting.asciidoc (#734)
> [7.x] Update troubleshooting.asciidoc (#734)

- docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
- Document Agent/Fleet Server environment variables (#671)
> [7.13] Document Agent/Fleet Server environment variables (#671)

- docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes.asciidoc
- Document Agent/Fleet Server environment variables (#671)
> [7.x] Document Agent/Fleet Server environment variables (#671)

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
fixes: https://github.com/elastic/observability-docs/issues/733
just a quick edit to align to final product naming.  naming is hard!  :)
> update name to Elastic Cloud agent

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- Add note about removing system extension during uninstall (#742)
> [7.13] Add note about removing system extension during uninstall (#742)

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- Add note about removing system extension during uninstall (#742)
> [7.x] Add note about removing system extension during uninstall (#742)

- docs/en/observability/monitor-aws.asciidoc
- Update monitor-aws.asciidoc (#652)
> [7.13] Update monitor-aws.asciidoc (#652)

- docs/en/observability/monitor-aws.asciidoc
- Update monitor-aws.asciidoc (#652)
> [7.x] Update monitor-aws.asciidoc (#652)

- docs/en/ingest-management/troubleshooting.asciidoc
- Fleet troubleshooting: update Kibana config file settings (#772)
> [7.x] Fleet troubleshooting: update Kibana config file settings (#772)

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- update name to Elastic Cloud agent (#759)
> [7.x] update name to Elastic Cloud agent (#759)

- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- update name to Elastic Cloud agent (#759)
> [7.13] update name to Elastic Cloud agent (#759)

- docs/en/ingest-management/troubleshooting.asciidoc
- Update troubleshooting.asciidoc (ef5a03de)
> [7.x] Update troubleshooting.asciidoc (ef5a03de)

- docs/en/ingest-management/release-notes/release-notes-7.13.asciidoc
- Add release notes for 7.13.2 (#787)
> [7.13] Add release notes for 7.13.2 (#787)

- docs/en/ingest-management/getting-started.asciidoc
Fixes tagged region that is causing page formatting to break.
> Fix formatting error caused by addition of tagged region

- docs/en/ingest-management/getting-started.asciidoc
> [7.x] Fix formatting error (#797)

- docs/en/ingest-management/getting-started.asciidoc
> [7.13] Fix formatting error (#797)

- docs/en/observability/logs-threshold-alert.asciidoc
Adds some recommendations for group by configurations.
> [Logs] Add some performance recommendations for the log threshold rule type

- docs/en/observability/index.asciidoc
- docs/en/observability/synthetics-params-secrets.asciidoc
Fixes https://github.com/elastic/observability-docs/issues/805
Adds docs for params and secrets.
> [Synthetics] Docs on secrets and params

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/tab-widgets/uninstall.asciidoc
Closes #724 
This should be backported to 7.13.
> Fix uninstall commands

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/tab-widgets/uninstall.asciidoc
- Fix uninstall commands (#822)
> [7.13] Fix uninstall commands (#822)

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/tab-widgets/uninstall.asciidoc
- Fix uninstall commands (#822)
> [7.14] Fix uninstall commands (#822)

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/tab-widgets/uninstall.asciidoc
- Fix uninstall commands (#822)
> [7.x] Fix uninstall commands (#822)

- docs/en/observability/metrics-threshold-alert.asciidoc
- Make more clear in the example that conditions accumulate (#836)
> [7.x] Make more clear in the example that conditions accumulate (#836)

- docs/en/observability/metrics-threshold-alert.asciidoc
- Make more clear in the example that conditions accumulate (#836)
> [7.14] Make more clear in the example that conditions accumulate (#836)

- docs/en/observability/metrics-threshold-alert.asciidoc
- Make more clear in the example that conditions accumulate (#836)
> [7.13] Make more clear in the example that conditions accumulate (#836)

- docs/en/observability/metrics-threshold-alert.asciidoc
Addressing comment from @immon on a previous PR https://github.com/elastic/observability-docs/pull/836#discussion_r664446022
> Metric threshold alert improvement

- docs/en/observability/metrics-threshold-alert.asciidoc
- Metric threshold alert improvement (#841)
> [7.x] Metric threshold alert improvement (#841)

- docs/en/observability/metrics-threshold-alert.asciidoc
- Metric threshold alert improvement (#841)
> [7.14] Metric threshold alert improvement (#841)

- docs/en/observability/metrics-threshold-alert.asciidoc
- Metric threshold alert improvement (#841)
> [7.13] Metric threshold alert improvement (#841)

- docs/en/observability/index.asciidoc
- docs/en/observability/synthetics-configuration.asciidoc
- docs/en/observability/synthetics-params-secrets.asciidoc
- add synthetics configuration docs (#847)
> [7.14] add synthetics configuration docs (#847)

- docs/en/observability/index.asciidoc
- docs/en/observability/synthetics-command-reference.asciidoc
- docs/en/observability/synthetics-configuration.asciidoc
- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
+ Includes latest changes available in the synthetics agent and also updated playwright API's URL.
> [Synthetics] update docs with new api's

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- Add pointer to docs about kibana.yml settings (#821)
> [7.13] Add pointer to docs about kibana.yml settings (#821)

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
- Add pointer to docs about kibana.yml settings (#821)
> [7.x] Add pointer to docs about kibana.yml settings (#821)

- docs/en/observability/index.asciidoc
- docs/en/observability/synthetics-command-reference.asciidoc
- docs/en/observability/synthetics-configuration.asciidoc
- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- [Synthetics] update docs with new api's (#861)
> [7.14] [Synthetics] update docs with new api's (#861)

- docs/en/observability/index.asciidoc
- docs/en/observability/synthetics-command-reference.asciidoc
- docs/en/observability/synthetics-configuration.asciidoc
- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- [Synthetics] update docs with new api's (#861)
> [7.x] [Synthetics] update docs with new api's (#861)

- .github/ISSUE_TEMPLATE/docs-request.md
Proposed initial template for new requests.
> Initial issue template

- docs/en/observability/user-experience-visualizations.asciidoc
This PR adds content for Core Web Vitals to the Create user experience visualizations topic of Exploratory view.
https://observability-docs_879.docs-preview.app.elstc.co/guide/en/observability/master/user-experience-visualizations.html
Closes https://github.com/elastic/observability-docs/issues/860
> Add core web vitals

- docs/en/observability/user-experience-visualizations.asciidoc
> [7.x] Add core web vitals (#879)

- docs/en/observability/user-experience-visualizations.asciidoc
> [7.14] Add core web vitals (#879)

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent-in-a-container.asciidoc
- docs/en/ingest-management/elastic-agent/elastic-agent.asciidoc
> [Elastic Agent] Document usage inside a container

- docs/en/ingest-management/faq.asciidoc
Just an idea we decided might be nice to have doc'ed after a brief conversation in slack:
https://elastic.slack.com/archives/CNMNXV4RG/p1627384694155700
> example for resetting a package to bring back the dashboard assets

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Closes #760 
Also adds placeholder for 7.14 release notes.
> Add known issue about secrets entered in Kibana

- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/getting-started-traces.asciidoc
- docs/en/ingest-management/getting-started.asciidoc
- docs/en/ingest-management/tab-widgets/install.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
Closes #802
Please respond to any questions embedded as comments in the source files.
> Add info about --insecure flag to agent install docs

- docs/en/ingest-management/beats-agent-comparison.asciidoc
Forgot to clean out questions.
> Remove review comments and add missing support statement

- docs/en/ingest-management/data-streams.asciidoc
For https://github.com/elastic/observability-docs/issues/842.
> docs: update APM data stream naming scheme

- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Copies Fleet-related Kibana release notes to the Fleet User Guide.
> Add Fleet-related Kibana relnotes

- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
Documents known issue for https://github.com/elastic/beats/issues/27114 and https://github.com/elastic/beats/issues/27187
> Add known issue about problem with agents enrolled through a proxy

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Add known problem about default policy setup (#950)
> [7.x] Add known problem about default policy setup (#950)

- docs/en/ingest-management/faq.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- docs/en/ingest-management/troubleshooting.asciidoc
- Add known problem about default policy setup (#950)
> [7.14] Add known problem about default policy setup (#950)

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
> [7.x] Clarify topic title (#969)

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
> [7.14] Clarify topic title (#969)

- docs/en/ingest-management/troubleshooting.asciidoc
Please backport to all versions affected.
> Remove SDH reference in documentation

- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add skeleton files for 7.14.1 release notes (#1010)
> [7.x] Add skeleton files for 7.14.1 release notes (#1010)

- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add skeleton files for 7.14.1 release notes (#1010)
> [7.14] Add skeleton files for 7.14.1 release notes (#1010)

- docs/en/ingest-management/release-notes/release-notes-7.14.asciidoc
- Add skeleton files for 7.14.1 release notes (#1010)
> [7.15] Add skeleton files for 7.14.1 release notes (#1010)

- docs/en/ingest-management/fleet/fleet-server.asciidoc
Closes #825 
The cloud updates were merged today, so I've added a link to the docs that will provide more info for ECE users.
> Update Fleet Server docs with link to related ECE info

- docs/en/ingest-management/fleet/fleet-server.asciidoc
- Update Fleet Server docs with link to related ECE info (#1020)
> [7.15] Update Fleet Server docs with link to related ECE info (#1020)

- docs/en/ingest-management/fleet/fleet-server.asciidoc
- Update Fleet Server docs with link to related ECE info (#1020)
> [7.14] Update Fleet Server docs with link to related ECE info (#1020)

- docs/en/integrations/air-gapped.asciidoc
- docs/en/integrations/asset-testing.asciidoc
- docs/en/integrations/build-integration.asciidoc
- docs/en/integrations/dashboards.asciidoc
- docs/en/integrations/elastic-package.asciidoc
- docs/en/integrations/index.asciidoc
- docs/en/integrations/integration-example.asciidoc
- docs/en/integrations/package-spec.asciidoc
- docs/en/integrations/pipeline-testing.asciidoc
- docs/en/integrations/publish-integration.asciidoc
- docs/en/integrations/quick-start.asciidoc
- docs/en/integrations/static-testing.asciidoc
- docs/en/integrations/system-testing.asciidoc
- docs/en/integrations/testing.asciidoc
- docs/en/integrations/what-is-an-integration.asciidoc
- Integrations developer guide (#769)
> [7.15] Integrations developer guide (#769)

- docs/en/integrations/air-gapped.asciidoc
- docs/en/integrations/asset-testing.asciidoc
- docs/en/integrations/build-integration.asciidoc
- docs/en/integrations/dashboards.asciidoc
- docs/en/integrations/elastic-package.asciidoc
- docs/en/integrations/index.asciidoc
- docs/en/integrations/integration-example.asciidoc
- docs/en/integrations/package-spec.asciidoc
- docs/en/integrations/pipeline-testing.asciidoc
- docs/en/integrations/publish-integration.asciidoc
- docs/en/integrations/quick-start.asciidoc
- docs/en/integrations/static-testing.asciidoc
- docs/en/integrations/system-testing.asciidoc
- docs/en/integrations/testing.asciidoc
- docs/en/integrations/what-is-an-integration.asciidoc
- Integrations developer guide (#769)
> [7.x] Integrations developer guide (#769)

- docs/en/observability/monitor-aws.asciidoc
- Update monitor-aws.asciidoc (#1025)
> [7.14] Update monitor-aws.asciidoc (#1025)

- docs/en/observability/monitor-aws.asciidoc
- Update monitor-aws.asciidoc (#1025)
> [7.x] Update monitor-aws.asciidoc (#1025)

- docs/en/observability/monitor-aws.asciidoc
- Update monitor-aws.asciidoc (#1025)
> [7.15] Update monitor-aws.asciidoc (#1025)

- .github/ISSUE_TEMPLATE/docs-request.md
We need to identify which person can provide information about what is being documented.
> Add contact person to issue template

- docs/en/observability/index.asciidoc
- docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
- [Uptime] Add troubleshooting page for Uptime guide (#1046)
> [7.x] [Uptime] Add troubleshooting page for Uptime guide (#1046)

- docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
- [Uptime] Clarify docs around mapping issues / standalone agent (#1085)
> [7.x] [Uptime] Clarify docs around mapping issues / standalone agent (#1085)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.15.asciidoc
- Add 7.15 release notes (#1080)
> [7.x] Add 7.15 release notes (#1080)

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-7.15.asciidoc
- Add 7.15 release notes (#1080)
> [7.15] Add 7.15 release notes (#1080)

- docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Update elastic-agent-container.asciidoc Url for docker official repository
> Update elastic-agent Url docker official repo

- docs/en/observability/synthetics-create-test.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- Favor synthetics-demo repo over synthetics/examples. (#1108)
> [7.x] Favor synthetics-demo repo over synthetics/examples. (#1108)

- docs/en/observability/whats-new.asciidoc
This PR updates a link to fix the docs in https://github.com/elastic/docs/pull/2242.
> Update link to fix docs build

- docs/en/observability/analyze-monitors.asciidoc
- docs/en/observability/categorize-logs.asciidoc
- docs/en/observability/configure-logs-sources.asciidoc
- docs/en/observability/configure-metrics-sources.asciidoc
- docs/en/observability/configure-uptime-settings.asciidoc
- docs/en/observability/infrastructure-threshold-alert.asciidoc
- docs/en/observability/ingest-logs.asciidoc
- docs/en/observability/ingest-metrics.asciidoc
- docs/en/observability/ingest-uptime.asciidoc
- docs/en/observability/inspect-log-anomalies.asciidoc
- docs/en/observability/inspect-metric-anomalies.asciidoc
- docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
- docs/en/observability/instrument-apps.asciidoc
- docs/en/observability/logs-threshold-alert.asciidoc
- docs/en/observability/metrics-app-fields.asciidoc
- docs/en/observability/metrics-threshold-alert.asciidoc
- docs/en/observability/monitor-aws-services.asciidoc
- docs/en/observability/monitor-status-alert.asciidoc
- docs/en/observability/synthetics-params-secrets.asciidoc
- docs/en/observability/synthetics-quickstart-fleet.asciidoc
- docs/en/observability/synthetics-visualize.asciidoc
- docs/en/observability/tail-logs.asciidoc
- docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
- docs/en/observability/uptime-duration-anomaly-alert.asciidoc
- docs/en/observability/uptime-tls-alert.asciidoc
- docs/en/observability/view-infrastructure-metrics.asciidoc
- docs/en/observability/view-monitor-status.asciidoc
- Add discrete markers (#1134)
> [7.10] Add discrete markers (#1134)

- docs/en/observability/analyze-monitors.asciidoc
- docs/en/observability/categorize-logs.asciidoc
- docs/en/observability/configure-logs-sources.asciidoc
- docs/en/observability/configure-metrics-sources.asciidoc
- docs/en/observability/configure-uptime-settings.asciidoc
- docs/en/observability/infrastructure-threshold-alert.asciidoc
- docs/en/observability/ingest-logs.asciidoc
- docs/en/observability/ingest-metrics.asciidoc
- docs/en/observability/ingest-uptime.asciidoc
- docs/en/observability/inspect-log-anomalies.asciidoc
- docs/en/observability/inspect-metric-anomalies.asciidoc
- docs/en/observability/inspect-uptime-duration-anomalies.asciidoc
- docs/en/observability/instrument-apps.asciidoc
- docs/en/observability/logs-threshold-alert.asciidoc
- docs/en/observability/metrics-app-fields.asciidoc
- docs/en/observability/metrics-threshold-alert.asciidoc
- docs/en/observability/monitor-aws-services.asciidoc
- docs/en/observability/monitor-servers.asciidoc
- docs/en/observability/monitor-status-alert.asciidoc
- docs/en/observability/synthetics-visualize.asciidoc
- docs/en/observability/tail-logs.asciidoc
- docs/en/observability/uptime-duration-anomaly-alert.asciidoc
- docs/en/observability/uptime-tls-alert.asciidoc
- docs/en/observability/view-infrastructure-metrics.asciidoc
- docs/en/observability/view-monitor-status.asciidoc
- Add discrete markers (#1134)
> [7.12] Add discrete markers (#1134)

- docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
- docs/en/ingest-management/integrations.asciidoc
- docs/en/ingest-management/quick-starts.asciidoc
- docs/en/ingest-management/redirects.asciidoc
- docs/en/observability/ingest-splunk.asciidoc
- docs/en/observability/synthetics-quickstart-fleet.asciidoc
Follow up to #1149. Removes temporary sections and replaces links.
> Replace temporary links to finalize pr#1149

- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/redirects.asciidoc
- docs/en/ingest-management/security/certificates.asciidoc
- docs/en/ingest-management/troubleshooting/faq.asciidoc
Reverts elastic/observability-docs#1177
> Revert "[7.x] Remove redirects page for 7.16 (#1168)"

- docs/en/observability/apm.asciidoc
- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
- docs/en/observability/monitor-k8s/monitor-k8s-application-performance.asciidoc
- docs/en/shared/configure-apm-server/content.asciidoc
- docs/en/shared/spin-up-the-stack/content.asciidoc
- docs: update APM links (#1181)
> [8.0] docs: update APM links (#1181)

- docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
- Add tip about ECK to Fleet-managed Agent section (#1150)
> [master] Add tip about ECK to Fleet-managed Agent section (#1150)

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
Remove the agent.logging.ecs and agent.logging.json config attributes for the 8.0 release.
> remove agent.logging.ecs and json

- docs/en/ingest-management/beats-agent-comparison.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/standalone-note.asciidoc
Adds the following disclaimer to the docs:
> Add disclaimer to standalone docs

- docs/en/ingest-management/beats-agent-comparison.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/standalone-note.asciidoc
- Add disclaimer to standalone docs (#1230)
> [7.16] Add disclaimer to standalone docs (#1230)

- docs/en/ingest-management/beats-agent-comparison.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/run-elastic-agent-standalone.asciidoc
- docs/en/ingest-management/standalone-note.asciidoc
- Add disclaimer to standalone docs (#1230)
> [7.15] Add disclaimer to standalone docs (#1230)

- docs/en/ingest-management/beats-agent-comparison.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
- docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
- docs/en/ingest-management/standalone-note.asciidoc
- Add disclaimer to standalone docs (#1230)
> [8.0] Add disclaimer to standalone docs (#1230)

- docs/en/observability/index.asciidoc
- docs/en/observability/monitor-uptime-synthetics.asciidoc
- docs/en/observability/monitor-uptime.asciidoc
- docs/en/observability/synthetic-monitoring.asciidoc
- docs/en/observability/synthetics-quickstart-fleet.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
- Consolidate synthetics and uptime content (#1171)
> [7.16] Consolidate synthetics and uptime content (#1171)

- docs/en/observability/index.asciidoc
- docs/en/observability/monitor-uptime-synthetics.asciidoc
- docs/en/observability/monitor-uptime.asciidoc
- docs/en/observability/synthetic-monitoring.asciidoc
- docs/en/observability/synthetics-quickstart-fleet.asciidoc
- docs/en/observability/synthetics-quickstart.asciidoc
- docs/en/observability/troubleshoot-uptime-mapping-issues.asciidoc
- Consolidate synthetics and uptime content (#1171)
> [8.0] Consolidate synthetics and uptime content (#1171)

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
> Backport (#1212) Add elastic-agent diagnostics to troubleshooting section

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
> Backport (#1208) remove agent.logging.ecs and json

- .github/ISSUE_TEMPLATE/docs-request.md
Helps reduce confusion over 'incomplete tasks'
> Replace Tasks with bullets in issue template

- docs/en/ingest-management/fleet/add-fleet-server.asciidoc
- docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc
- docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
- docs/en/ingest-management/fleet/fleet-server.asciidoc
- docs/en/ingest-management/index.asciidoc
- Reorganize Fleet Server content (#1274)
> [7.16] Reorganize Fleet Server content (#1274)

- docs/en/ingest-management/fleet/add-fleet-server.asciidoc
- docs/en/ingest-management/fleet/fleet-server-deployment-models.asciidoc
- docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
- docs/en/ingest-management/fleet/fleet-server.asciidoc
- docs/en/ingest-management/index.asciidoc
- Reorganize Fleet Server content (#1274)
> [8.0] Reorganize Fleet Server content (#1274)

- docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
* Change agent pprof default to false
* Apply suggestions from code review
Co-authored-by: DeDe Morton <dede.morton@elastic.co>
Co-authored-by: DeDe Morton <dede.morton@elastic.co>
> [Backport] Change agent pprof default to false (#1289)

- docs/en/ingest-management/troubleshooting/faq.asciidoc
> [7.16] Update faq.asciidoc (#1113)

- docs/en/ingest-management/troubleshooting/faq.asciidoc
> [8.0] Update faq.asciidoc (#1113)

- docs/en/observability/ingest-splunk.asciidoc
> [7.14] docs: fix bad link (#1320)

- docs/en/observability/ingest-splunk.asciidoc
> [7.13] docs: fix bad link (#1320)

- docs/en/ingest-management/troubleshooting/faq.asciidoc
Backports the following commits to main:
- Update faq.asciidoc (#1113)
> [main] Update faq.asciidoc (#1113)

- docs/en/observability/ci-cd-observability.asciidoc
- Update ci-cd-observability.asciidoc (#1338)
> [7.16] Update ci-cd-observability.asciidoc (#1338)

- docs/en/observability/ci-cd-observability.asciidoc
- Update ci-cd-observability.asciidoc (#1338)
> [8.0] Update ci-cd-observability.asciidoc (#1338)

- docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
Fixes link to match changes in https://github.com/elastic/kibana/pull/121351
> Fix link to Kibana role management docs

- .mergify.yml
> Add 7.17 to mergify

- docs/en/ingest-management/fleet/fleet-server.asciidoc
Backports the following commits to 7.17:
- Update fleet-server.asciidoc (#1396)
> [7.17] Update fleet-server.asciidoc (#1396)

- docs/en/ingest-management/overview.asciidoc
Backports the following commits to 7.17:
- Update overview.asciidoc (#1368)
> [7.17] Update overview.asciidoc (#1368)

- docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Adding section "Known issues" to Fleet 7.16
> [Fleet] Add known issue to Fleet 7.16

- docs/en/ingest-management/commands.asciidoc
Closes #918 
I tried to be somewhat generic here so that we are not committing to specific types of images.
> Document command-line flag for delaying enrollment

- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Relates to:
- https://github.com/elastic/fleet-server/pull/995
- https://github.com/elastic/beats/pull/29434
> Add deprecation notices for username/passwords for env vars

- docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
- docs/en/ingest-management/fleet/fleet.asciidoc
- docs/en/ingest-management/fleet/set-elastic-agent-enrollment-timeout.asciidoc
- docs/en/ingest-management/index.asciidoc
Closes #901 
Link to preview: https://observability-docs_1407.docs-preview.app.elstc.co/guide/en/fleet/master/set-enrollment-timeout.html 
Todo:
> Add topic about setting enrollment timeout for Fleet-managed agents

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Closes #1294 
Really sorry about the delay. This got lost in my inbox.
> Add workaround for Fleet Server integration policy upgrade problem

- docs/en/ingest-management/commands.asciidoc
> Add documentation for the elastic agent "status" command

- docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
> Add relnotes for 7.16.3 and missing patch releases

- docs/en/ingest-management/beats-agent-comparison.asciidoc
> Remove stale list of integrations from the Fleet/Agent docs

- docs/en/observability/synthetics-command-reference.asciidoc
Resolves #1412.
Adds a new entry to the existing synthetics command line flags page for playwright options.
> Create new entry to synthetics commands docs page for `--playwright-options`

- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Update deprecation messages to indicate that the behaviour will change.
> agent kibana env vars update deprecation notices

- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
> [backport] Update deprecation notices (#1476)

- docs/en/ingest-management/release-notes/release-notes-7.16.asciidoc
Closes #1343.
@spong  Sorry this got lost in our work queue. :-/
> Add note to 7.16 release notes about requirement for unique integration policy names

- docs/en/ingest-management/commands.asciidoc
Closes https://github.com/elastic/beats/issues/27244
> Clarify command syntax for elastic-agent commands

- docs/en/ingest-management/integrations/upgrade-integration.asciidoc
- docs/en/ingest-management/troubleshooting/faq.asciidoc
> Clarify internet requirements in the Fleet FAQ

- docs/en/observability/synthetics-quickstart-fleet.asciidoc
We should better describe that the whole idea is to support git repos.
> Better communicate the point of the `zip_url` feature

- docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
> Add 8.0.1 release notes for Fleet and Elastic Agent

- docs/en/observability/observability-ui.asciidoc
Backports the following commits to main:
- Correct improper capitalization (#1600)
> [main] Correct improper capitalization (#1600)

- docs/en/ingest-management/commands.asciidoc
Update the install command docs to correspond with rpm/deb detection changes in https://github.com/elastic/beats/pull/30289
> Update install command for rpm/deb detection

- docs/en/ingest-management/release-notes/release-notes-8.0.asciidoc
MERGE BEFORE RUNNING FINAL 8.0.1 build
> Remove coming tags for 8.0.1

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Closes #1612 
DO NOT MERGE UNTIL THE CODE REPO IS SWITCHED - target March 4.
> Update link to the Elastic Agent code repository

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
- docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
- docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
Also removes a few mentions of the default policy missed in #1489
> Add missing description for FLEET_SERVER_POLICY_ID env var

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Also removes a troubleshooting topic that is old and should have been removed in 7.15.
> Clarify that extra privileges are required to delete system indices

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Adds release notes for 7.17.2 and fixes commented out template.
> Add Fleet/Agent release notes for 7.17.2

- docs/en/ingest-management/elastic-agent/install-fleet-managed-agent.asciidoc
- docs/en/ingest-management/index.asciidoc
> [Backport] [8.0] [1741] add minimal agent install docs

- docs/en/ingest-management/tab-widgets/start.asciidoc
- docs/en/ingest-management/tab-widgets/stop.asciidoc
Closes https://github.com/elastic/elastic-agent/issues/296
@narph Just want to confirm that the change you requested in [296](https://github.com/elastic/elastic-agent/issues/296) is still accurate. I can test, if necessary.
> Fix Elastic Agent start/stop commands on win

- docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
- docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
- docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
Closes #1743 
I've updated the links. Please verify that the URLs are correct and let me know if anything else needs to be changed. I'm not sure when these topics were last verified for technical accuracy. Now might be a good time to do that.
> Update path to Elastic Agent repo in docs

- docs/en/ingest-management/release-notes/release-notes-8.1.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Note that I've also added a 8.1.2 release notes change that wasn't in main. There's no need to review those changes again unless you want to.
> Adds Elastic Agent and Fleet 8.1.3 release notes

- docs/en/ingest-management/fleet/add-fleet-server.asciidoc
- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
- docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
> Change APM & Fleet to Integrations Server

- docs/en/ingest-management/index.asciidoc
- docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Closes https://github.com/elastic/observability-docs/issues/1805.
Please respond to questions that start with `//REVIEWERS` inline in the source files.
I'll keep creating these release notes until someone tells me we have automation in place.
> Add Fleet and Elastic Agent 8.2.0 relnotes

- docs/en/ingest-management/migrate-beats-to-agent.asciidoc
- docs/en/observability/monitor-k8s/monitor-k8s-logs.asciidoc
This PR lints all *.asciidoc files for repeated words.
> Lint all docs for for repeated words

- docs/en/ingest-management/fleet/fleet-settings.asciidoc
> Mention that Fleet Server must be running before configuring Fleet Settings

- .github/workflows/add-pr-to-project.yml
This _should_ fix the failing PR actions.
> use `pull_request_target`

- .github/workflows/add-issue-to-project.yml
- .github/workflows/add-pr-to-project.yml
> Remove add label step

- .github/workflows/add-pr-to-project.yml
- .github/workflows/add-to-dev-projects.yml
When this label is added         | Add to this board                                                  
---|---
`Team:Elastic-Agent-Control-Plane` | `Elastic Agent Control Plane`
`Team:Fleet`                       | `Fleet UI`                               
`Team:Elastic-Agent-Data-Plane`    | `Elastic Agent Data Plane`
> Add board automation for other teams

- docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc
Didn't see any changes for Elastic Agent or Fleet, but please let me know if I've missed something.
> Add Fleet and Elastic Agent 8.2.2 release notes

- docs/en/ingest-management/beats-agent-comparison.asciidoc
> update Beats capability for DStreams (#1964)

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
These may be useful for our scaling efforts, thought making them public made sense as well. Would like @ph to confirm before we publish these.
> Document some Fleet Server timeout configs

- docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
- docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
- docs/en/observability/ingest-logs-metrics-uptime.asciidoc
Adds some signposts for users who encounter the new step-based workflow added by https://github.com/elastic/kibana/pull/133664 
Updates the observability and Fleet/Agent guides to address https://github.com/elastic/observability-docs/issues/1920
> Update docs for step-based workflow

- docs/en/ingest-management/troubleshooting/faq.asciidoc
Closes #1939 
Whoever reviews this should also read through the full FAQ to see if any of the other info is outdated.
Preview link: https://observability-docs_1983.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-faq.html
> Remove old FAQ description about secure communications

- docs/en/ingest-management/release-notes/release-notes-8.3.asciidoc
> Add Fleet/Agent 8.3.3 release notes

- docs/en/ingest-management/overview.asciidoc
> Fix typo in attribute reference

- docs/en/ingest-management/commands.asciidoc
> Update commands.asciidoc (#2093)

- docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Fixes the numbering issue here by removing whitespace between steps.
> Fix numbering issue caused by linter comment

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Note that I've had to modify the variables at the top of the page to account for the existence of issues in the elastic-agent repo, but code backported to the beats repo.
> Add Fleet and Elastic Agent 7.17.6 release notes

- docs/en/observability/uptime-set-up-app.asciidoc
Adds a note on required privileges for monitor management. I'm not sure about the phrasing -- suggestions are very welcome!
> [synthetics] Add note on required privileges for enabling monitor management

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Forward ports #2158 to main branch.
> Update fleet-server-scaling.asciidoc (#2158)

- docs/en/observability/synthetics-configuration.asciidoc
Ref https://github.com/elastic/kibana/pull/140044#discussion_r965698973
Fixes a link to Playwright.
> Fix Playwright link

- docs/en/ingest-management/fleet/air-gapped.asciidoc
> Add missing binary download

- docs/en/ingest-management/commands.asciidoc
Fixes a few things we missed in #2093
> Add non-interactive flag to syntax example

- docs/en/ingest-management/commands.asciidoc
Backports #2100 to 8.5 branch (manual cherry-pick)
> Add non-interactive flag to syntax example (#2100)

- docs/en/observability/uptime-set-up-heartbeat.asciidoc
- fix docker image name
- add missing backslash in docker run command
> Docfix uptime-set-up-heartbeat.asciidoc

- docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
Forward ports #2204 to main.
Note that this change is already merged into the 8.4 branch.
> Update output-configuration.asciidoc (#2204)

- docs/en/ingest-management/integrations/view-integration-policies.asciidoc
Forwardports #2236 to main branch.
> Update view-integration-policies.asciidoc (#2236)

- docs/en/ingest-management/migrate-auditbeat-to-agent.asciidoc
Presents an alternative format to the info in https://github.com/elastic/observability-docs/pull/2270.
> Create reference table for easy scanning (alternative to #2270)

- docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
> Add 7.17.7 Fleet/Agent release notes

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Clarify PProf settings must be enabled prior to collecting the diag with pprof.
I would kindly ask the documentation team to:
- Improve the wording and format
- Backport this to any applicable version
> [DOCS] Diagnostic Pprof

- docs/en/ingest-management/agent-policies.asciidoc
Closes https://github.com/elastic/observability-docs/issues/2310
> Remove redundant jump link

- docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
Closes https://github.com/elastic/observability-docs/issues/2311
> Fix typo in topic about creating agent policy

- docs/en/ingest-management/beats-agent-comparison.asciidoc
- docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
- docs/en/ingest-management/migrate-auditbeat-to-agent.asciidoc
- docs/en/ingest-management/overview.asciidoc
- docs/en/ingest-management/troubleshooting/faq.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
> Change Endpoint and Cloud Security to Elastic Defend in Fleet docs

- docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
> Add Fleet/Agent 8.5.1 release notes

- docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
> Clarify that Fleet Server certs are managed by cloud

- docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
Step 5 was pointing to the git manifest, instead of the locally modified one.
> Correction on step 5

- docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Replaces https://github.com/elastic/observability-docs/pull/2396
Reminder to give co-author credit to @herrBez when merging.
> Update wget command

- docs/en/ingest-management/fleet/air-gapped.asciidoc
Since https://github.com/elastic/package-registry/pull/151
> Add mention to Package Registry dedicated /health endpoint

- docs/en/observability/manage-cases.asciidoc
Relates to https://github.com/elastic/kibana/issues/141371
This PR updates https://www.elastic.co/guide/en/observability/8.6/manage-cases.html to mention the bulk actions that you can perform on cases. It uses the same text from https://github.com/elastic/kibana/pull/148358
> [DOCS] Bulk actions in Cases

- docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
> Remove relontes entry for Kibana #142369 in 8.6

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
> remove conf `xpack.security.enabled: true` (#2467)

- docs/en/ingest-management/fleet/air-gapped.asciidoc
> Fix list formatting in air gapped docs

- docs/en/ingest-management/processors/processors.asciidoc
just a small clarification. thanks
> Correction to the processor document for agent

- docs/en/ingest-management/elastic-agent/run-container-common/download-elastic-agent.asciidoc
Add a paragraph to explain the granted permissions the elastic-agent daemonset gets by default
> Document elastic-agent required resources

- docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
Add a paragraph to explain the granted permissions the elastic-agent daemonset gets by default
> Document elastic-agent required resources for KSPM

- .github/workflows/add-pr-to-project.yml
Follow up to https://github.com/elastic/observability-docs/pull/2559.
> Update GitHub actions project ID

- docs/en/observability/application-logs.asciidoc
For https://github.com/elastic/observability-docs/issues/2362.
> docs: link to new java docs

- docs/en/ingest-management/migrate-auditbeat-to-agent.asciidoc
Added docs & references for System Audit package.
> Added system audit reference docs

- .github/workflows/add-issue-to-project.yml
Fixes our automation that adds new issues to our project board. The current automation is failing due to a deprecation in the GitHub API.
> docs: fix add issue to project automation

- docs/en/observability/synthetics-private-location.asciidoc
Obs-docs counterpart to https://github.com/elastic/beats/pull/34307 . CC @paulb-elastic . 
Fixes https://github.com/elastic/observability-docs/issues/2550
> Add docs for scaling private locations

- docs/en/ingest-management/agent-policies.asciidoc
> max number of policies

- docs/en/ingest-management/release-notes/release-notes-8.5.asciidoc
Copies changes from #2642  into 8.5 docs.
> Add ventura installation known issue

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Missed this while reviewing https://github.com/elastic/observability-docs/pull/1292
> Fix TOC for troubleshooting

- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Manual backport of #2678 into 7.17 branch.
> [7.17](backport #2678) Fix TOC for troubleshooting

- docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Based on our recent testing results, modifying the fleet server resource consumption values. Also removing the various parameter values that have been confusing to the users. Instead keying everything from the number of agents configured.
> Updating the fleet server scalability resources

- docs/en/ingest-management/commands.asciidoc
- docs/en/ingest-management/fleet-agent-proxy-support.asciidoc
- docs/en/ingest-management/security/certificates.asciidoc
- docs/en/ingest-management/tab-widgets/upgrade-fleet.asciidoc
- docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
> Remove -f option from elastic-agent install commands

- docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc
Add https://github.com/elastic/elastic-agent/issues/2343 as a known issue for 8.6.x releases
> Add known issue entry for elastic-agent#2343

- docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
> Remove experimental banner on Fleet API docs page

- docs/en/ingest-management/processors/processor-copy_fields.asciidoc
Adds improvements from https://github.com/elastic/beats/pull/34798 to the agent processor docs.
> Clarify behavior of copy fields processor

- docs/en/observability/aws-deploy-elastic-serverless-forwarder.asciidoc
- docs/en/observability/aws-elastic-serverless-forwarder-configuration.asciidoc
- docs/en/observability/aws-elastic-serverless-forwarder.asciidoc
- docs/en/observability/aws-serverless-transform.asciidoc
- docs/en/observability/aws-serverless-troubleshooting.asciidoc
- docs/en/observability/index.asciidoc
- docs/en/observability/redirects.asciidoc
Reverts elastic/observability-docs#2848
> Revert "Remove Elastic Serverless Forwarder source files from the obs guide (main branch only)"

- docs/en/observability/universal-profiling.asciidoc
Added a missing period and fixed some confusing wording.
> Fix formatting and wording

- docs/en/observability/profiling-troubleshooting.asciidoc
Fixes AsciiDoc source block markup.
> Universal Profiling: Fix markup

- docs/en/observability/synthetics-recorder.asciidoc
> Update recorder download location

- docs/en/observability/tab-widgets/add-apm-integration/content.asciidoc
Required for https://github.com/elastic/apm-server/pull/10750#discussion_r1200766559
> Add secret token to step two

- docs/en/observability/redirects.asciidoc
Updates redirects.asciidoc for changes we made during spacetime.
I want to keep the entries that redirect to a different book for now. Might be nice to give users a little time to adjust to the changes we made.
Related issue:  #2919
> Update redirects file

- docs/en/observability/synthetics-role-write.asciidoc
Update required permissions as a result of https://github.com/elastic/kibana/pull/159378
> Update permissions for private locations

- docs/en/observability/create-alerts.asciidoc
Update the list of rules to include a link to the APM rules.
> Add APM rules to list of rules

- docs/en/observability/profiling-get-started.asciidoc
This PR fixes a typo and updates information to match the current UI.
> Update the profiling agent integration section

- docs/en/observability/logs-stream.asciidoc
This PR closes [Issue 3120](https://github.com/elastic/observability-docs/issues/3120) and closes [Issue3119](https://github.com/elastic/observability-docs/issues/3119)
[Preview here](https://observability-docs_3118.docs-preview.app.elstc.co/guide/en/observability/master/logs-stream.html#logs-stream-enhance-logs)
> add enhance logs and extract timestamp docs

- README.md
- docs/en/observability/index.asciidoc
- docs/en/observability/manage-cases.asciidoc
Backports https://github.com/elastic/observability-docs/pull/3135
> [8.8][DOCS] Remove content reuse for cases (#3135)

- README.md
- docs/en/observability/index.asciidoc
- docs/en/observability/manage-cases.asciidoc
Backports https://github.com/elastic/observability-docs/pull/3135
> [8.7][DOCS] Remove content reuse for cases (#3135)

- README.md
- docs/en/observability/index.asciidoc
- docs/en/observability/manage-cases.asciidoc
Backports https://github.com/elastic/observability-docs/pull/3135
> [8.6][DOCS] Remove content reuse for cases (#3135)

- docs/en/observability/profiling-upgrade.asciidoc
With this commit we apply a suggestion made in https://github.com/elastic/observability-docs/pull/3179 and improve the rendering of a related console snippet.
Co-authored-by: Mike Birnstiehl <114418652+mdbirnstiehl@users.noreply.github.com>
> [Profiling] Improve wording in upgrade docs

- docs/en/observability/observability-get-started.asciidoc
Related: https://github.com/elastic/docs/pull/2749
> Add links to other Observability guides

- docs/en/observability/profiling-get-started.asciidoc
The known issues section of Profiling > Get Started is inaccurate.
> Profiling: improve known issues

- docs/en/observability/logs-filter.asciidoc
- docs/en/observability/logs-parse.asciidoc
Remove comma to fix code block and update with some changes from serverless update.
> [Logs] Update filter docs

- docs/en/observability/logs-stream.asciidoc
Reroute processor query should be `GET logs-critical-default/_search`
> [Logs] update reroute processor query

- docs/en/observability/logs-troubleshooting.asciidoc
Fixes [Issue 172](https://github.com/elastic/staging-serverless-observability-docs/issues/172) in the classic docs.
> [Logs] update host connection troubleshooting

- docs/en/observability/monitor-infra/analyze-hosts.asciidoc
- docs/en/observability/monitor-infra/configure-metrics-sources.asciidoc
- docs/en/observability/monitor-infra/inspect-metric-anomalies.asciidoc
- docs/en/observability/monitor-infra/view-infrastructure-metrics.asciidoc
Applies fixes found during serverless testing (from this commit: https://github.com/elastic/staging-serverless-observability-docs/pull/188/commits/870bed7fbe1eb105a0ba323a15fb76fb8bd554ae)
> Fix minor issues found during testing

- docs/en/observability/observability-ai-assistant.asciidoc
Flagged in Slack that we might want to change link. ~Drafting PR in anticipation of confirmation.~ [_edit:confirmed_]
> Update connectors link in AI assistant guide

- docs/en/observability/traces-get-started.asciidoc
Related to #3432 #3433 #3434 #3435
> [apm docs consolidation] Update `apm-server-root` references (main-8.10)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3438
> [apm docs consolidation] Update apm-server-root references 7.16

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3438
> [apm docs consolidation] Update apm-server-root references 7.17

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.0)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.1)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.2)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.3)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.4)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.5)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.6)

- docs/en/observability/ingest-traces.asciidoc
- docs/en/observability/instrument-apps.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.7)

- docs/en/observability/ingest-traces.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.8)

- docs/en/observability/ingest-traces.asciidoc
> [apm docs consolidation] Update `apm-server-root` references (8.9)

- docs/en/apm-server/legacy/guide/opentelemetry-elastic.asciidoc
- docs/en/apm-server/open-telemetry.asciidoc
I am baffled as to why these four images don't resolve. I've tried everything and cannot get this to build locally with images. I'm removing them in this PR.
For the errors in https://github.com/elastic/docs/pull/2873.
> 7.16: remove images

- docs/en/apm-server/getting-started-apm-server.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3536
Note: Does not include changes from https://github.com/elastic/apm-server/pull/12222 or https://github.com/elastic/apm-server/pull/12196 because they were not backported to 8.8.
> [apm docs consolidation] Copy recent /apm-server docs edits (8.8)

- docs/en/apm-server/getting-started-apm-server.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3536
Note: Does not include changes from https://github.com/elastic/apm-server/pull/12222 or https://github.com/elastic/apm-server/pull/12196 because they were not backported to 8.9.
> [apm docs consolidation] Copy recent /apm-server docs edits (8.9)

- docs/en/observability/observability-ai-assistant.asciidoc
Closes https://github.com/elastic/observability-docs/issues/3423
Closes https://github.com/elastic/observability-docs/issues/3427
Closes https://github.com/elastic/observability-docs/issues/3428
This PR prepares AI assistant content for the 8.12 release including:
See the preview here: https://observability-docs_3512.docs-preview.app.elstc.co/guide/en/observability/master/obs-ai-assistant.html
> [ai assistant] Update product status for 8.12, add known issues

- docs/en/observability/redirects.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3559
> [apm consolidation] Add temporary redirects back to APM guide (8.10)

- docs/en/observability/redirects.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3559
> [apm consolidation] Add temporary redirects back to APM guide (8.9)

- docs/en/observability/redirects.asciidoc
- docs/en/observability/whats-new.asciidoc
Related to https://github.com/elastic/observability-docs/pull/3559
> [apm consolidation] Add temporary redirects back to APM guide (8.8)

- docs/en/observability/apm/otel-direct.asciidoc
Fix OTLP header ApiKey casing in APM docs.
> Fix OTLP header ApiKey casing

- docs/en/observability/threshold-alert.asciidoc
Closes #3549 for classic docs.
> Make custom threshold rule GA in the docs

- .github/workflows/run-minor-release.yml
Otherwise:
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
> ci: grant permissions and set the secret to create the minor branch

- docs/en/observability/logs-checklist.asciidoc
Fix for heading error in the Logs Checklist.
> Update the Logs Checklist headings

- docs/en/apm-server/redirects.asciidoc
This is required to merge https://github.com/elastic/apm-server/pull/12820.
These links will be updated and re-added after https://github.com/elastic/apm-server/pull/12820 is merged.
> Temporarily comment out release note redirects

- docs/en/observability/synthetics-params-secrets.asciidoc
+ Clarify and add additional details to section on synthetics security / working with sensitive values. Also document how synthetics app privileges can be used for accessing these values.
> Clarify synthetics params / secrets docs

- docs/en/observability/apm/upgrading-to-8.x.asciidoc
Closes https://github.com/elastic/apm-server/issues/12796
> docs: remove false deprecation note for standalone apm-server

- docs/en/integrations/build-integration.asciidoc
Small addition to the explanation of what each file in the data_stream/fields directory does. 
- agent.yml provides the fields the Elastic agent uses.
- fields.yml are additional fields the integration uses.
> Complete the explanation for the files in the integration field directory

- .github/dependabot.yml
> dependabot: keep github actions up-to-date

- docs/en/observability/synthetics-command-reference.asciidoc
https://github.com/elastic/staging-serverless-observability-docs/pull/242/commits/86f58d9dcfd47b5c79c6270c6fa82651473b3f6c
> Add DeDe’s serverless suggestions

- docs/en/observability/profiling-get-started.asciidoc
Just recently .Net support was merged and will be part of the next release.
> profiling: add .Net to supported interpreters

- docs/en/observability/observability-ai-assistant.asciidoc
Closes #3715 
TODO:
After merging:
> Remove Claude 3.0 restriction

- docs/en/observability/observability-ai-assistant.asciidoc
- docs/en/shared/alerting-connectors.asciidoc
Adds active link to the reference docs about the connector.
> Add link to published Obs AI Assistant docs

- .github/workflows/run-minor-release.yml
> github-actions: use github secrets

- docs/en/observability/cloud-monitoring/aws/monitor-amazon-sqs.asciidoc
This will backport the following commits from `8.14` to `main`:
- [Update monitor-amazon-sqs.asciidoc (#4007)](https://github.com/elastic/observability-docs/pull/4007)
> [main] Update monitor-amazon-sqs.asciidoc (#4007)

- docs/en/observability/observability-introduction.asciidoc
This PR will need to be backported to all versions back to 8.9.
Please check with PM for confirmation.
> Remove BETA mention from UP

- docs/en/observability/cloud-monitoring/azure/monitor-azure-openai-apm.asciidoc
This PR updates the Monitor Azure OpenAI docs to include @xrmx's improvements to the example app.
> Update the Azure OpenAI docs to include example app updates

- docs/en/observability/uptime-intro.asciidoc
Add deprecation note for Uptime
> Add deprecation note for Uptime

- docs/en/observability/apm/otel-direct.asciidoc
> docs/otel-direct: fix code snippet rendering in table

- docs/en/observability/apm-ui/api.asciidoc
- docs/en/observability/apm/configure/outputs/console.asciidoc
- docs/en/observability/apm/configure/outputs/elasticsearch.asciidoc
- docs/en/observability/apm/configure/outputs/kafka.asciidoc
- docs/en/observability/apm/configure/outputs/logstash.asciidoc
- docs/en/observability/apm/configure/outputs/output-cloud.asciidoc
- docs/en/observability/apm/configure/outputs/redis.asciidoc
- docs/en/observability/apm/sampling.asciidoc
Clean up float tags in advance of bumpting the chunk level to 4.
required before merging https://github.com/elastic/docs/pull/3045.
> Add tags to fix chunking in obs guide

- docs/en/observability/apm-ui/apm-app-users.asciidoc
- docs/en/observability/apm/feature-roles.asciidoc
Fix stuff missed in https://github.com/elastic/observability-docs/pull/4147.
> Add tags to fix chunking

- docs/en/observability/profiling-get-started.asciidoc
The hint is relevant only for version 8.9 and below, but doesn't mention the version.
> Update profiling upgrade hint

- docs/en/observability/apm/jaeger-integration.asciidoc
Update Jaeger integration docs with a deprecation warning.
> Jaeger deprecation warning

- docs/en/observability/logs-add-service-name.asciidoc
- docs/en/serverless/logging/add-logs-service-name.mdx
The new experience isn't available in 8.15, so I'm removing this mention and will add it for 8.16.
> Remove mention of new experience

- docs/en/serverless/apm-agents/apm-agents-opentelemetry.mdx
Ports #4220 to serverless docs.
> Remove technical preview badge for otel java

- docs/en/serverless/apm/apm-ui-services.mdx
Ports https://github.com/elastic/observability-docs/pull/4198 to serverless.
> [serverless] Remove note, add list of dimensions

- docs/en/observability/elastic-entity-model.asciidoc
- docs/en/serverless/elastic-entity-model.mdx
Adds limitations to EEM docs in both the stateful (8.16) and serverless doc sets.
Closes #4177
> Add limitations to EEM docs

- .github/ISSUE_TEMPLATE/elastic-request.yaml
> Update versions in our issue template

- docs/en/observability/apm/access-api-keys.asciidoc
Align with feature-roles.asciidoc
> Fix apm agentcfg api key privileges

- docs/en/serverless/ai-assistant/ai-assistant.mdx
Ports #4143 to serverless
n/a
_Select one._
> Port #4143 to serverless

- docs/en/serverless/ai-assistant/ai-assistant.mdx
Trigger MDX build
Closes # 
_Select one._
> Trigger MDX build

- docs/en/apm-server/redirects.asciidoc
- docs/en/observability/redirects.asciidoc
Fixes a mistake in https://github.com/elastic/observability-docs/pull/4493
> Fix 8.16 redirects (part two)

- docs/en/observability/apm/manage-storage/data-streams.asciidoc
- docs/en/observability/profiling-manage-storage.asciidoc
Preview:
* https://observability-docs_bk_4657.docs-preview.app.elstc.co/guide/en/observability/master/apm-data-streams.html
* https://observability-docs_bk_4657.docs-preview.app.elstc.co/guide/en/observability/master/profiling-manage-storage.html
> Add Synthetic `_source` callout to APM + UP docs

- docs/en/observability/grant-cases-access.asciidoc
> Manual backport of 4850 targeting 8.18

- .mergify.yml
> mergify: support 8.18 backports
